### ISSUE TITLE
Inform users regarding Set-ExecutionPolicy RemoteSigned in README

### ISSUE THREAD

**Issue by ryder203** [badabing2005/PixelFlasher#1]
Hi badabing2005, maybe give users a hint in the howto so they can enable PowerShell Scripts if it's disabled by default like it was for me.
I had to execute _Set-ExecutionPolicy RemoteSigned_ and enable scripts in a PowerShell as admin to even start the script.

**Comment by badabing2005** [comment]
Thanks for the feedback @ryder203, good point, things like that I tend to forget and take it for granted as I had done it long time ago.
I will update the notes /  readme to reference the details provided by Microsoft.

**Comment by badabing2005** [comment]
Updated readme
