### ISSUE TITLE
Flagged by Windows Defender

### ISSUE THREAD

**Issue by Tomadock** [badabing2005/PixelFlasher#101]
Attempting to download PixelFlasher.exe gets flagged and blocked by Windows Defender with the following message:

Detected: Trojan:Win32/Wacatac.B!ml

**Comment by badabing2005** [comment]
Please see [this](https://www.virustotal.com/gui/url/ef083fb5b7859dbb07f3713e63670ef4ea18bd5002995532f5e9ddfb35ba70a6?nocache=1) and #57, and #41.
There is nothing I could do for false positives.
There are more tickets and forums discussions about it than just the above listed one.
