### ISSUE TITLE
Malicious code detected! > DO NOT DOWNLOAD

### ISSUE THREAD

**Issue by spreak** [badabing2005/PixelFlasher#102]
PixelFlasher.exe
https://www.virustotal.com/gui/file/57dba22913a0005f5839df470657e8ffe3020e9650b53a779b175dd365c7ede1

**Comment by badabing2005** [comment]
https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/post-89090938
