### ISSUE TITLE
Backup Manager is Grey on Pixel 6 (oriole) and cannot create backups as it does not believe there is root.

### ISSUE THREAD

**Issue by AlexS2412** [badabing2005/PixelFlasher#103]
So after messing around with this i have concluded it cannot detect magisk 26.3, and the other versions appear to be for pixel 7 or much earlier builds. it results in this

![image](https://github.com/badabing2005/PixelFlasher/assets/14182708/a8f6cc38-bde6-4cdd-b528-b0c27a200b51)

![image](https://github.com/badabing2005/PixelFlasher/assets/14182708/271cf5ff-7299-4da4-a034-cf05aa85f964)

i have tried both changing the package name and even using the default name but the button remains grey.

![image](https://github.com/badabing2005/PixelFlasher/assets/14182708/f0afdc3f-34b2-42c0-a9f2-fd7ebcbc4062)

 since TWRP does not exist for these devices i was hopeful about this backup tool incase of user error that caused bootloops. any suggestions?

**Comment by AlexS2412** [comment]
![Screenshot_20231025-143456](https://github.com/badabing2005/PixelFlasher/assets/14182708/a62a4143-24a0-45bb-b97a-b9a8869c7852)
![Screenshot_20231025-143507](https://github.com/badabing2005/PixelFlasher/assets/14182708/04bd45b3-4152-470f-a8be-8c3c1afb05b6)
![Screenshot_20231025-143526](https://github.com/badabing2005/PixelFlasher/assets/14182708/5e72b1d2-a700-4eda-9c7d-012a0218651d)

To elaborate further, i only have a few modules enabled that shouldnt cause issues, just simply to pass safetynet and disable signature verification so i do not have to sign my own apks. i am unsure if this is relevant. i did try the package name shown in the picture but it seems the application doesnt recognize it or that there is even root despite it very clearly being rooted. sorry for confusion in advance.

**Comment by AlexS2412** [comment]
this is the result with the package named being used. 
![image](https://github.com/badabing2005/PixelFlasher/assets/14182708/40d913cb-43ff-4784-bcf7-c5604cd5d707)

it seems to find the path but does not believe there is root.

**Comment by badabing2005** [comment]
Please check, Basic Usage | step 3 | bullet 1

**Comment by badabing2005** [comment]
This issue was closed due to inactivity.

**Comment by AlexS2412** [comment]
im unsure what ShellUID package even is... or if it's a part of magisk or not. i am sorry for pestering you with such a small bug, the magisk backup tool seemed like something needed before i experiment further with my device as without any forms of custom recovery on the pixel 6 theres no good way to recover from magisk related bootloops like you typically would in TWRP

**Comment by badabing2005** [comment]
Did you check if you have granted root access to ShellUID 
If you don't PF will not detect root, PF uses shell to invoke adb / fastboot commands, 
If you don't grant root, then it will disable all parts that require root, as simple as that.

**Comment by AlexS2412** [comment]
> Did you check if you have granted root access to ShellUID If you don't PF will not detect root, PF uses shell to invoke adb / fastboot commands, If you don't grant root, then it will disable all parts that require root, as simple as that.

I cannot find this ShellUID in the first place, is it a magisk feature, or some other standalone application? theres not much documentation so i am lost as what i am meant to do.

**Comment by badabing2005** [comment]
This is part of basic functionality of Magisk.
You grant / revoke root access by clicking on Superuser tab in Magisk
You see all the applications that had requested root, and their whether they are granted or denied.
Just make sure you allow [SharedUID] Shell.
<img width="127" alt="shell-root" src="https://github.com/badabing2005/PixelFlasher/assets/22603312/3b24f28c-dc2f-4ad3-888d-d94e36afda2b">

**Comment by AlexS2412** [comment]
> This is part of basic functionality of Magisk. You grant / revoke root access by clicking on Superuser tab in Magisk You see all the applications that had requested root, and their whether they are granted or denied. Just make sure you allow [SharedUID] Shell. <img alt="shell-root" width="127" src="https://user-images.githubusercontent.com/22603312/278625069-3b24f28c-dc2f-4ad3-888d-d94e36afda2b.png">

oh i found it thank you so much! is there a reason its not on by default normally?

**Comment by badabing2005** [comment]
Yep
Allowing root requires the user's approval, otherwise apps would request root and be granted without your knowledge.
PF has no way of setting that.
