### ISSUE TITLE
ERROR: recovery: Timeout waiting for messages from minadbd

### ISSUE THREAD

**Issue by benjamin-kirkbride** [badabing2005/PixelFlasher#104]
Sorry, can't take a screenshot obviously and also don't have another device to take a photo.

I am using the Ubuntu 22 version of the program.

I went through the steps outlined [here](https://github.com/badabing2005/PixelFlasher#basic-mode) with my pixel 6 and my phone now says the following:

(in orange)
> Android Recovery
> google/oriole/oriole
> 14/UP1A.231005.007.A1/10762838
> Use volume up/down and power.
> [a bunch of options]
> ....

then at the bottom:
> Now send the package you want to apply
> to the device with "adb sideload <filename>"...
> ERROR:    recovery: Timeout woiting for messages from minadbd
>
> Install from ADB complete (status: 1).

**Comment by benjamin-kirkbride** [comment]
the program says that it would appear that it wasn't doing anything but to have faith (paraphrased) but I figured this is probably not what I should expect?

**Comment by benjamin-kirkbride** [comment]
Trying again, this is what it looks like before I send it:
![image](https://github.com/badabing2005/PixelFlasher/assets/3373830/8b6dc01f-6b75-4287-8274-002926e12ab4)

**Comment by benjamin-kirkbride** [comment]
New error:
![image](https://github.com/badabing2005/PixelFlasher/assets/3373830/4a8b7327-4798-404d-bb96-87b5087c2d01)

pushing forward regardless though...

**Comment by benjamin-kirkbride** [comment]
The phone did not reboot immediately this time. Got these errors in the console

![image](https://github.com/badabing2005/PixelFlasher/assets/3373830/7d480b8c-65c3-4e54-8180-1172ae43d5fa)

**Comment by benjamin-kirkbride** [comment]
Even running PixelFlasher as root I get the error.
![image](https://github.com/badabing2005/PixelFlasher/assets/3373830/34140ded-9d9f-4b3c-a8a6-7e7d322a5109)

I ensured my user is part of `plugdev` and I installed `android-sdk-platform-tools-common`.

It did not seem to work, but I will restart my computer and my phone and try again.

**Comment by benjamin-kirkbride** [comment]
I restarted everything and tried again from scratch; I no longer get the "Your phone is:" error, nor the udev/permissions errors, and have progressed past the "Now send the package you want to apply..." stage. I can see the percentage increasing in the console. 

So far so good!

**Comment by benjamin-kirkbride** [comment]
Okay, so it seems to have worked? at least it finished and said success and restarted, but magisk says "N/A" under "installed" and I can't change any of the modules. Not sure what's up with that.

**Comment by benjamin-kirkbride** [comment]
> Your phone's bootloader does not have to be unlocked to be able to flash full OTA image (stock boot only).

Does this mean that the flashed / patched / Magisk img is not actually able to be used without unlocking the bootloader? That makes sense, but was not clear to me initially.

**Comment by badabing2005** [comment]
Can you please provide a support.zip file which can be generated from the app.
That will tell help me troubleshoot and understand what is going on.

**Comment by benjamin-kirkbride** [comment]
[support_2023-10-26_18-22-39.zip](https://github.com/badabing2005/PixelFlasher/files/13183323/support_2023-10-26_18-22-39.zip)

**Comment by badabing2005** [comment]
You started with:
```
Selected Device on 2023-10-26 15:22:21:
    Device ID:                       REDACTED
    Device Model:                    oriole
    Device Active Slot:              a
    Device Mode:                     adb
    Has init_boot partition:         False
    Device is Rooted:                False
    Device Build:                    UP1A.231005.007.A1
    Device API Level:                34
    Device Architecture:             arm64-v8a
    Device Kernel Version:           5.10
    sys_oem_unlock_allowed:          0
    ro.boot.flash.locked:            1
    ro.boot.vbmeta.device_state:     locked
    vendor.boot.vbmeta.device_state: 
    ro.product.first_api_level:      31
    ro.boot.warranty_bit:            
    ro.boot.veritymode:              enforcing
    ro.boot.verifiedbootstate:       green
    vendor.boot.verifiedbootstate:   
    ro.warranty_bit:                 
    ro.secure:                       1
    ro.zygote:                       zygote64_32
    ro.vendor.product.cpu.abilist:   arm64-v8a,armeabi-v7a,armeabi
    ro.vendor.product.cpu.abilist32: armeabi-v7a,armeabi
    Device Bootloader Version:       slider-1.3-10674934
    Magisk Manager Version:          26.3:26300
    Magisk Path:                     /data/app/~~t4OTbJo8WAQdQkUf1Q9Xug==/com.topjohnwu.magisk-eBfa9bAiegQfCm0Zxcqk-A==/base.apk
        Checked for Package:         com.topjohnwu.magisk
```

Your device is locked, hence you can only flash stock OTA

The first issue you ran into was
`adb: sideload connection failed`
Current version of PF reboots to sideload and then waits 20 seconds before starting to sideload.
There is no known way to detect if the device is in sideload mode, that is why there is that 20 seconds wait.
It turns out that on some devices 20 seconds is not enough
I increased 20 to 40 seconds and that will be in the next release.

The second error: `ERROR: Android device model  does not match firmware Model oriole` that you encountered was because your device was still in sideload mode from previous state, hence PF had no way of getting the model.

You rebooted back to system, selected patched boot and tried to flash again

It flashed OTA ok, but couldn't flash the patch because your phone is locked.
```
Writing 'boot_b'                                   FAILED (remote: 'command (flash:) is not allowed when locked')
fastboot: error: Command failed
```

This effectively got you on slot b because OTA flashing was successful.
```
Selected Device on 2023-10-26 16:13:54:
    Device ID:                       REDACTED
    Device Model:                    oriole
    Device Active Slot:              b
    Device Mode:                     adb
    Has init_boot partition:         False
    Device is Rooted:                False
    Device Build:                    UP1A.231005.007.A1
    Device API Level:                34
    Device Architecture:             arm64-v8a
    Device Kernel Version:           5.10
    sys_oem_unlock_allowed:          1
    ro.boot.flash.locked:            1
    ro.boot.vbmeta.device_state:     locked
    vendor.boot.vbmeta.device_state: 
    ro.product.first_api_level:      31
    ro.boot.warranty_bit:            
    ro.boot.veritymode:              enforcing
    ro.boot.verifiedbootstate:       green
    vendor.boot.verifiedbootstate:   
    ro.warranty_bit:                 
    ro.secure:                       1
    ro.zygote:                       zygote64_32
    ro.vendor.product.cpu.abilist:   arm64-v8a,armeabi-v7a,armeabi
    ro.vendor.product.cpu.abilist32: armeabi-v7a,armeabi
    Device Bootloader Version:       slider-1.3-10674934
    Magisk Manager Version:          26.3:26300
```

You tried again, selecting a patch and flashing OTA
OTA sideloading worked, but just like before flashing the patch failed because it requires an unlocked phone.
This flash switched you back to slot a

```
Selected Device on 2023-10-26 16:24:35:
    Device ID:                       REDACTED
    Device Model:                    oriole
    Device Active Slot:              a
    Device Mode:                     adb
    Has init_boot partition:         False
    Device is Rooted:                False
    Device Build:                    UP1A.231005.007.A1
    Device API Level:                34
    Device Architecture:             arm64-v8a
    Device Kernel Version:           5.10
    sys_oem_unlock_allowed:          1
    ro.boot.flash.locked:            1
    ro.boot.vbmeta.device_state:     locked
    vendor.boot.vbmeta.device_state: 
    ro.product.first_api_level:      31
    ro.boot.warranty_bit:            
    ro.boot.veritymode:              enforcing
    ro.boot.verifiedbootstate:       green
    vendor.boot.verifiedbootstate:   
    ro.warranty_bit:                 
    ro.secure:                       1
    ro.zygote:                       zygote64_32
    ro.vendor.product.cpu.abilist:   arm64-v8a,armeabi-v7a,armeabi
    ro.vendor.product.cpu.abilist32: armeabi-v7a,armeabi
    Device Bootloader Version:       slider-1.3-10674934
    Magisk Manager Version:          26.3:26300
```

You next tried Live booting, which also requires unlocked phone hence it failed as well
You kept on trying few more times with the same results.

At this point you have a perfectly unrooted phone that should be able to boot to either slot, however if you need to root, you need to unlock it first.

Hope this clarifies the situation.

**Comment by benjamin-kirkbride** [comment]
Thanks for the detailed response.

Would it make sense for there to be a more overt error/info message if the bootloader is still locked?

**Comment by badabing2005** [comment]
I thought about that, and actually wanted to add it, however the check whether a device is locked or not is not reliable as it can be faked.
By the way it is one of the [prerequisites](https://github.com/badabing2005/PixelFlasher#prerequisites) and stated in the documentation.

**Comment by benjamin-kirkbride** [comment]
Thanks so much for your help!
