### ISSUE TITLE
After Backing Up Paritions All device free space is empty.

### ISSUE THREAD

**Issue by AlexS2412** [badabing2005/PixelFlasher#105]
im unsure what i did but it reports 63mb of free space. i am very confused...

**Comment by AlexS2412** [comment]
it seems to have left an incomplete userdata.img in /data/local/tmp/. i deleted it and the space returned. is it not able to backup this partition as it is larger than device storage? i was confused why it results in an error and i believe this may be why. how odd it doesnt stream the backup of one of the more important partitions.

**Comment by badabing2005** [comment]
It's a partitions manager not a backup manager, you will not benefit from dumping userdata partition even if it is successful, because you won't be able to restore it.
