### ISSUE TITLE
List Magisk Modules crash

### ISSUE THREAD

**Issue by chriss158** [badabing2005/PixelFlasher#11]
Hi badabing2005,
Thanks for creating this tool 👍 This tool makes it really easy to flash pixel images.

Using latest version (2.4).
When i list the magisk modules, i get following error:
![image](https://user-images.githubusercontent.com/12832850/164317818-f53a762f-9950-4256-adab-cbbffcb9af33.png)

Thank you for looking at this 👍 
Regards
Chris

**Comment by badabing2005** [comment]
Thanks for the report.
Just so I understand you correctly.
You got this error when you clicked on the Magisk icon to manage the Magisk modules?
Can you try something, turn on verbose on the console
reload devices, and select your device again, do you get the same error?

In the above screenshot, I see that you have 3 modules, can you confirm if that is all the 3 modules you have?

Everything points to one of the modules not having an id, which I never expected to be the case.
I'll try to install those modules and see if I can reproduce it.

**Comment by chriss158** [comment]
> You got this error when you clicked on the Magisk icon to manage the Magisk modules?

Yes

> reload devices, and select your device again, do you get the same error?

Same error.
![image](https://user-images.githubusercontent.com/12832850/164326667-a9cb89b4-8785-4ebc-b592-c9738b51a07c.png)

> I'll try to install those modules and see if I can reproduce it.
Yes you are right. The AK3 Helper Module does not have an ID. This one is bundle with the kirisakura kernel.

**Comment by badabing2005** [comment]
I searched for `De-bloater` and `ak3-helper` with FoxMM
I couldn't find a direct match, and searching debloater on Google comes with so many hits and different things, can you please share the source of these modules so that I could inspect them?

The verbose option should display details about the modules if it does not encounter problems.

**Comment by chriss158** [comment]
> I searched for `De-bloater` and `ak3-helper` with FoxMM I couldn't find a direct match, and searching debloater on Google comes with so many hits and different things, can you please share the source of these modules so that I could inspect them?
> 
> The verbose option should display details about the modules if it does not encounter problems.

Have a look at my last post. There is the modules.prop of the AK3-helper module

**Comment by badabing2005** [comment]
ok that's what I thought, it should have an ID.
I'll add safety measures into the code to account for modules that are not following the standard.

Thanks

**Comment by badabing2005** [comment]
Should be fixed now in [v2.4.1](https://github.com/badabing2005/PixelFlasher/releases/tag/v2.4.1)
Thanks for reporting.
