### ISSUE TITLE
the Free Space Checker is most likely borked on BTRFS 

### ISSUE THREAD

**Issue by Pogogo007** [badabing2005/PixelFlasher#113]
Currently it thinks my Systems space is full when in reality i have roughly 660GB free on my machine
Oh and also get_free_space() < 5 or get_free_space(get_config_path()) < 5
Less than? is that intentional?

**Comment by badabing2005** [comment]
Support file please, and yes that is intentional, as one can choose to change where firmware / ota files get unpacked to, whereas the system is always used for processes that use temp space.

**Comment by Pogogo007** [comment]
[support_2023-11-13_15-55-07.zip](https://github.com/badabing2005/PixelFlasher/files/13341581/support_2023-11-13_15-55-07.zip)

**Comment by badabing2005** [comment]
Thank you for the support file.
Please try 6.0.1.0, I expect it to report properly, furthermore if it doesn't at least you can disable the enforcement.

Let me know how it goes.
Thanks

**Comment by badabing2005** [comment]
Should be really fixed in 6.0.1.1
