### ISSUE TITLE
any adb-tools throws an error 

### ISSUE THREAD

**Issue by NastyaGrifon** [badabing2005/PixelFlasher#114]
Selecting any adb-tools version throws an error: 
`2023-11-13 22:25:22 ERROR: /bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_trim_arg_from_keyseq
2023-11-13 22:25:22 ERROR: Android Platform Tools version is not available or is too old.
                           For your protection, disabling device selection.
                           Please select valid Android SDK.`

Back in October 2023, the tool worked just fine and was used to patch and flash October OTA to barbet (Google Pixel 5a). The adb-tools version that worked last time is 33.0.3-linux

OS: Linux Manjaro

Tested Pixel Launcher Versions:

- Version 6.0.0.0
- Version 5.8.1.0
- Version 5.8.0.3

Tested adb-tools versions:

- 34.0.5-linux
- 34.0.4-linux
- 33.0.3-linux

simillar issues: #111 #109 

removing libreadline* does fix the issue

[support_2023-11-09_17-00-12.zip](https://github.com/badabing2005/PixelFlasher/files/13337542/support_2023-11-09_17-00-12.zip)

**Comment by badabing2005** [comment]
you don't have to remove manually, just add it to the new setting.s
