### ISSUE TITLE
Windows Security: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by rfgamaral** [badabing2005/PixelFlasher#115]
Windows Security detects the latest release v6.0.1.0 with a trojan... 😱

![image](https://github.com/badabing2005/PixelFlasher/assets/96476/1f2319cb-1795-4887-9321-f7e0e3122c76)

**Comment by badabing2005** [comment]
Please see [this](https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/page-88#post-89090938), nothing I can do about it.

**Comment by rfgamaral** [comment]
Thanks for the links, but why only on the latest version?

**Comment by badabing2005** [comment]
It's not only on the latest version, as you can see from the forum discussions, it's an old post, and actually there many older posts as well, and some in here as reported issues.
It happens with every release, some AV clients are worse than others.

I understand the concern, and if you don't feel comfortable , build it from source.

**Comment by rfgamaral** [comment]
> It's not only on the latest version

Well, for me, it only happens with the latest version. If I download the previous version, Windows doesn't complain about it, if I downloaded the latest one it does. That's what prompted me to create this issue, because I never had this problem until the recently released version.
