### ISSUE TITLE
Incorrect path passed

### ISSUE THREAD

**Issue by adepssimius** [badabing2005/PixelFlasher#118]
Version: 6.0.1.3 DMG artifact (labelled as 6.0.1.2 in the application)
OS: Mac OSX 12.7 Monterey

I ran into an issue while flashing a patched init_boot where it appears to not find the patched file due to an incomplete path. The relevant line in the logs belog is `Stderr: fastboot: error: cannot load '/Users/REDACTED/Library/Application': No such file or directory`, which is a file that correctly does not exist. It appears that the space in the directory name was not correctly handled, as I believe the correct path to be in `/Users/REDACTED/Library/Application Support/...`

Support file for further reference:
[support_2023-11-16_13-53-32.zip](https://github.com/badabing2005/PixelFlasher/files/13382310/support_2023-11-16_13-53-32.zip)

I promise I'm not out here just looking for issues 😃 

```
Resizing 'vendor_dlkm_b'                           OKAY [  0.018s]
Sending 'vendor_dlkm_b' (42600 KB)                 OKAY [  0.984s]
Writing 'vendor_dlkm_b'                            OKAY [  0.291s]
archive does not contain 'vendor_other.img'
Finished. Total time: 214.830s
2023-11-16 12:31:24 Done script flashing!
Sleeping 10 seconds ...

2023-11-16 12:31:34 Getting device: REDACTED state  ...
Currently the device is in fastboot mode.

2023-11-16 12:31:34 Getting device: REDACTED state  ...
Rebooting device: REDACTED to bootloader ...
Fastboot waiting device: REDACTED for bootloader ...
device: REDACTED is now in bootloader mode.
Updating connected devices ...


Selected Device on 2023-11-16 12:31:53:
    Device ID:                       REDACTED
    Device Model:                    felix
    Device Active Slot:              b
    Device Mode:                     f.b
    Has init_boot partition:         True
    Device Bootloader Version:       felix-14.0-10529422
    Device Unlocked:                 True
    slot-retry-count:a:              2
    slot-unbootable:a:               yes
    slot-successful:a:               yes
    slot-retry-count:b:              3
    slot-unbootable:b:               no
    slot-successful:b:               no

Flashing patched init_boot ...

2023-11-16 12:31:54 ERROR: Encountered an error while flashing the patch.
Return Code: 1.
Stdout: .
Stderr: fastboot: error: cannot load '/Users/REDACTED/Library/Application': No such file or directory
.
Aborting ...

2023-11-16 12:31:54 INFO: Flashing was aborted.
This could be user initiated or a problem encountered during flashing.

2023-11-16 12:31:54 Getting device: REDACTED state  ...
Current device mode: fastboot
You might need to manually reboot your device.
```

**Comment by adepssimius** [comment]
FYI I was able to work around this by manually flashing the patch boot file with the button next to the boot file selector.

**Comment by badabing2005** [comment]
> I promise I'm not out here just looking for issues 
Actually I don't feel bad at all and am grateful that you're finding these issues before the masses hit it which gives me a chance to fix.

You're right, when I refactored the flashing code, I forgot to put quotation marks around the boot file path, in fact your logs exposed another bug which I haven't realized, with dry run, PF is not supposed to flash anything, and in your case it had attempted to flash the patch but had failed.

Fixed both issues, should be ok in the next release (hopefully today)

Thanks
