### ISSUE TITLE
Flash pixel phone crash

### ISSUE THREAD

**Issue by chriss158** [badabing2005/PixelFlasher#12]
Hi badabing2005,

Using latest version (2.4).
When i try to flash the phone using the dry run option (I would first like to see if everything works), i get following error:
![image](https://user-images.githubusercontent.com/12832850/164318690-56f690c1-6ab2-45b6-b57f-b45a88e1258a.png)

ADB looks fine:
![image](https://user-images.githubusercontent.com/12832850/164318780-030fb37b-7c6c-4fc9-92e2-1c9eee28b2a8.png)

Version 2.2.2 does work. Bug was introduced with version 2.3

Thank you for looking at this 👍 
Regards
Chris

**Comment by badabing2005** [comment]
Sorry about that, an oversight of moving code around.
Fix is on the way, but let me see if I can find the issue for #11 before I push the fix.

**Comment by badabing2005** [comment]
Should be fixed now in [v2.4.1](https://github.com/badabing2005/PixelFlasher/releases/tag/v2.4.1)
Thanks for reporting.
