### ISSUE TITLE
can not run Pixelflasher 6.2.1.2

### ISSUE THREAD

**Issue by MichaelSMVogel** [badabing2005/PixelFlasher#123]
after downloading and allowing the downloaded file to be executed, I get the following error message for any version after 6.1 (which runs fine and flashed my P6 and P8 successfully)

Windows cannot access the specified device, path, or file. You may not have the appropriate
permissions to access the item.

If I go back to 6.1 it works.

**Comment by MichaelSMVogel** [comment]
the different versions are in the same dedicated, non system folder, one can be executed, the following versions can not
Win11, up to date

**Comment by badabing2005** [comment]
please check the checksum to make sure you got it intact and set the properties to unblock if Windows is blocking.
