### ISSUE TITLE
KernelSU Support? (Enhancement)

### ISSUE THREAD

**Issue by aryanmcr** [badabing2005/PixelFlasher#124]
### **KernelSU Support**

Maybe you could add KernelSU support? I get this will probably take a long time to program **but maybe you could make it so it checks your phones kernel and finds the boot image you have to download and downloads it** and then flash it_(You can already do that)._

- Basically just make it so it can automatically install the app and get the boot image for your version.
- You could make it so you could automatically add things like Zygisk Next (Which is not built in to KernelSU) to the modules

**Comment by badabing2005** [comment]
My test device does not support KernelSU, so it's kind of hard to code without being able to test, not knowing what to expect at what stage, check for the responses, handle the exceptions ...

**Comment by ac-tu** [comment]
It'd be nice to have this also to easily test build.prop files due to the lastest PIF not providing one, or else it has to be done manually, I understand you don't have a suitable test device but perhaps a custom rom has ksu built in you could use?

**Comment by badabing2005** [comment]
Testing build.prop is already there.
Check under Magisk.
https://github.com/badabing2005/PixelFlasher/blob/main/images/magisk-settings.png

**Comment by badabing2005** [comment]
> Without magisk, the most I can do is process a build.prop, not edit the pif.json or use play integrity check

To be able to install this module (which is a Magisk module) you need root.
Why would you even attempt to edit pif if you're not rooted?

Whether you're rooted with Magisk or KernelSU has no relevance here when it comes to editing pif.json
You need root access.

**Comment by badabing2005** [comment]
@Lu5ck support file and a screenshot please

**Comment by nyakze** [comment]
I used this since day0 of pif edit support with ksu and it worked fine (except not showing the version number), I don't understand what this issue is about?

**Comment by Azuriye** [comment]
Using ksu, can't create pif.json and check it.

![image](https://github.com/badabing2005/PixelFlasher/assets/75412786/e89b52a2-00f9-4f02-af23-5aa9c2355ac1)

**Comment by badabing2005** [comment]
Closing the issue, using the program as with KernelSU rooted devices is supported.

**Comment by nyakze** [comment]
Just a follow-up on this: recently I've changed kernel to a different one and pixelflasher stopped seeing root even though shell has root permissions. Was working perfectly on the other kernel.
For anyone interested:
Was working on: Melt Kernel 2.4
Not working on: Silvercore 20231223 official
ROM: XEU 14.0.25.0 / 14.0.27.0
Device: marble

**Comment by badabing2005** [comment]
Curious
Do you have /data/adb directory?
if so, what do you get when you issue this command
`adb shell "su -c 'ls -l /data/adb/'"`

**Comment by nyakze** [comment]
Where do you want me to run it?
In termux it's fine:
`~ $ su
:/data/data/com.termux/files/home # ls -l /data/adb
total 6751
drwx------  4 root root       3452 2023-12-24 01:05 ksu
-rwxr-xr-x  1 root root    3667440 2023-12-27 21:15 ksud
drwxrwxrwx  5 root root       3452 2023-12-27 21:09 lspd
drwxr-xr-x 13 root root       1024 2023-12-24 01:05 modules
drwx------  2 root root       3452 2023-11-30 14:54 modules_update
-rw-r--r--  1 root root 2097152000 2023-11-30 14:50 overlay`

**Comment by badabing2005** [comment]
Perhaps su is not in the path.
Can you type in termux
`which su` or `where su`

**Comment by nyakze** [comment]
> Perhaps su is not in the path. Can you type in termux `which su` or `where su`

~ $ which su
/data/data/com.termux/files/usr/bin/su

**Comment by nyakze** [comment]
btw feel free to pm me on telegram https://t.me/ekzeshka we can figure it out much quicker then ^^

**Comment by badabing2005** [comment]
I don't use telegram.
That is an su provided by termux
Uninstall termux and you won't have root.

In a future version I'll consider adding a configuration option to define the path to su, but that will involve quite a bit of code change as su without full path is utilized in many parts of the code.
This is the first time I see unconventional su without symbolic link.

You can create a symbolic link in /system/bin
su -> /data/data/com.termux/files/usr/bin/su

Do you have any Magisk modules?
How do they work?

**Comment by nyakze** [comment]
I have plenty of modules and they work without issues.
If I create a link for su, won't then root be found by different apps?
![Screenshot_2023-12-27-22-33-53-998_me weishu kernelsu](https://github.com/badabing2005/PixelFlasher/assets/10108639/695e943a-05c2-4532-b531-210b5f7c9a0e)
![Screenshot_2023-12-27-22-34-04-373_me weishu kernelsu](https://github.com/badabing2005/PixelFlasher/assets/10108639/e3e81ed3-5a48-4725-9e15-c4c682a90f45)
![Screenshot_2023-12-27-22-34-08-233_me weishu kernelsu](https://github.com/badabing2005/PixelFlasher/assets/10108639/52d3773b-f0a3-497b-84dc-f67da9643e23)
![Screenshot_2023-12-27-22-34-11-113_me weishu kernelsu](https://github.com/badabing2005/PixelFlasher/assets/10108639/141f4cc0-6fc6-4905-9f37-796c92b21451)

**Comment by nyakze** [comment]
Ok so I've reflashed melt kernel. `which su` still gives the same response, but pixelflasher is now seeing root.

**Comment by badabing2005** [comment]
which su in termux might be finding its own as it would be earlier in its path, but you must get a result (most likely a different result) when running with adb shell, otherwise PF will not find it.

**Comment by nyakze** [comment]
yes, that's true, it shows /system/bin/su in pixelflasher adb shell now. Could it be entirely kernel related? That's literally the only thing I changed...

**Comment by nyakze** [comment]
BTW, checking of fingerprints doesn't work with ksu. It does open the app but that's it. Have to execute and check the result myself on the phone.

**Comment by badabing2005** [comment]
> If I create a link for su, won't then root be found by different apps?
You would do it through a Magisk module, take a look at systemless hosts, and you can do something similar.

> BTW, checking of fingerprints doesn't work with ksu. It does open the app but that's it. Have to execute and check the result myself on the phone.
That is a function of uiautomator, see #137 

> yes, that's true, it shows /system/bin/su in pixelflasher adb shell now. Could it be entirely kernel related? That's literally the only thing I changed...
I don't know

**Comment by xlukas1337** [comment]
For anyone also having trouble to get it to work with KernelSU, you have to grant root to com.android.shell for PixelFlasher to properly detect root

**Comment by nyakze** [comment]
> For anyone also having trouble to get it to work with KernelSU, you have to grant root to com.android.shell for PixelFlasher to properly detect root

It's granted obviously
