### ISSUE TITLE
Magisk button errors out when trying to use it

### ISSUE THREAD

**Issue by xhemp** [badabing2005/PixelFlasher#125]
Just upgraded to the latest Pixel Flasher 6.3.0.0 (using a Pixel 7 Pro)  and when I go and push the Magisk button, I get the following:

```
Traceback (most recent call last):
  File "Main.py", line 2949, in _on_magisk
  File "magisk_modules.py", line 176, in __init__
  File "magisk_modules.py", line 302, in PopulateList
AttributeError: 'Magisk' object has no attribute 'updateAvailable'
```

Is this because I use Magisk Alpha and/or because it's hidden or there's something else going on?

Thank you!

**Comment by badabing2005** [comment]
It sounds like one your modules update link is returning bad data.
I need to support file to be able to see what is going on.

Are you on Linux / Mac?

**Comment by xhemp** [comment]
> It sounds like one your modules update link is returning bad data.
> I need to support file to be able to see what is going on.
> 
> Are you on Linux / Mac?

Interesting, I think I know which one, let me disable it and retry, will let you know.
I'm on Mac.

**Comment by badabing2005** [comment]
It probably would still fail, as the link would still be there even if it is disabled, and when it is processed, it runs into the issue.
I thought I had handled encountering exceptions when checking updates, I guess I missed some.

**Comment by xhemp** [comment]
Ran a few tests but they all came inconclusive, the only test that worked is when I remove all modules and then I can press Magisk and it works fine, very interesting :)

**Comment by badabing2005** [comment]
Don't worry, I have a fix, I'll push it out later today.

**Comment by xhemp** [comment]
No worries, man, take your time.
Thanks a lot!

**Comment by xhemp** [comment]
Thanks for fixing that. 
Don't want to be a pain but just tried with 6.3.0.1 and now it errors out with with a different attribute:

```
Traceback (most recent call last):
  File "Main.py", line 2950, in _on_magisk
  File "magisk_modules.py", line 176, in __init__
  File "magisk_modules.py", line 282, in PopulateList
AttributeError: 'str' object has no attribute 'id'
```

Is there anything I can run on a terminal to get all the attributes for each module?

**Comment by badabing2005** [comment]
Please enable debug in PF and try this version
https://github.com/badabing2005/PixelFlasher/actions/runs/7053776176

Let me know

**Comment by xhemp** [comment]
This one works fine, @badabing2005 ! 
Do you want me to run to get the support file again with this version or you know what is going on already?

**Comment by badabing2005** [comment]
Thanks
If there are no errors in the console, we're good.
If you see any errors, even if the ui appears to be working, then I'd like to take a look at support file please.

**Comment by xhemp** [comment]
No errors at all, just the normal:

`Checking for /data/adb/pif.json on the device as root ...
File: /data/adb/pif.json is found on the device.

Opening Magisk Modules Manager ...`

Thanks for looking into this and sorting it out!
