### ISSUE TITLE
Pixel 7. Factory image 2023-12-05. sqlite3.IntegrityError: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by ToddTheOdd** [badabing2005/PixelFlasher#133]
[support_2023-12-09_18-14-12.zip](https://github.com/badabing2005/PixelFlasher/files/13625112/support_2023-12-09_18-14-12.zip)

This is what i get when i try to process the file. Where should i start looking to try to fix it?

2023-12-09 18:19:49 User initiated Process firmware

==============================================================================
 2023-12-09 18:19:49 PixelFlasher 6.3.2.1         Processing firmware file ...
==============================================================================
Low memory option: False
Available Free Memory: 7.23 GB / 15.91 GB
debug: Looking for flash-all.bat in file C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with nested: False
debug: Looking for flash-all.bat in zipfile C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with zip-nested: False
debug: Found: panther-uq1a.231205.015/flash-all.bat

debug: Looking for flash-all.sh in file C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with nested: False
debug: Looking for flash-all.sh in zipfile C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with zip-nested: False
debug: Found: panther-uq1a.231205.015/flash-all.sh

debug: Looking for boot.img in file C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with nested: True
debug: Looking for boot.img in zipfile C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with zip-nested: True
debug: Found: panther-uq1a.231205.015/image-panther-uq1a.231205.015.zip/boot.img

debug: Looking for init_boot.img in file C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with nested: True
debug: Looking for init_boot.img in zipfile C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with zip-nested: True
debug: Found: panther-uq1a.231205.015/image-panther-uq1a.231205.015.zip/init_boot.img

debug: Looking for vbmeta.img in file C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with nested: True
debug: Looking for vbmeta.img in zipfile C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip with zip-nested: True
debug: Found: panther-uq1a.231205.015/image-panther-uq1a.231205.015.zip/vbmeta.img

Detected Pixel firmware
debug: Unzipping Image: C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip into C:\Users\Redacted\AppData\Roaming\PixelFlasher\factory_images\panther-uq1a.231205.015 ...
debug: "C:\Temp\_MEI56562\bin\7z.exe" x -bd -y -o"C:\Users\Redacted\AppData\Roaming\PixelFlasher\factory_images" "C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip"
7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
Scanning the drive for archives:
1 file, 2898219863 bytes (2764 MiB)
Extracting archive: C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip
--
Path = C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip
Type = zip
Physical Size = 2898219863
Everything is Ok
Folders: 1
Files: 6
Size:       2915549351
Compressed: 2898219863
Extracting init_boot.img from C:\Users\Redacted\AppData\Roaming\PixelFlasher\factory_images\panther-uq1a.231205.015\image-panther-uq1a.231205.015.zip ...
debug: "C:\Temp\_MEI56562\bin\7z.exe" x -bd -y -o"C:\Users\Redacted\AppData\Roaming\PixelFlasher\tmp" "C:\Users\Redacted\AppData\Roaming\PixelFlasher\factory_images\panther-uq1a.231205.015\image-panther-uq1a.231205.015.zip" boot.img init_boot.img vbmeta.img
sha1 of init_boot.img: bd65f0ef723b2a3ddeba2cb245d213db5aae5a21
Checking for cached copy of init_boot.img
Found a cached copy of firmware init_boot.img sha1=bd65f0ef723b2a3ddeba2cb245d213db5aae5a21
Checking DB entry for PACKAGE: C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip
Creating DB entry for PACKAGE: C:\PixelFlasher\panther-uq1a.231205.015-factory-9bc852a1.zip
Package ID: 0
Checking DB entry for BOOT: bd65f0ef723b2a3ddeba2cb245d213db5aae5a21
Found a previous BOOT record id=12 for boot_hash: bd65f0ef723b2a3ddeba2cb245d213db5aae5a21
Boot_ID: 12
Checking DB entry for PACKAGE_BOOT: package_id = '0' AND boot_id = '12
Creating PACKAGE_BOOT record, package_id: 0 boot_id: 12
Record PACKAGE_BOOT record, package_id: 0 boot_id: 12 already exists
Traceback (most recent call last):
  File "modules.py", line 941, in process_file
sqlite3.IntegrityError: FOREIGN KEY constraint failed

Please Process the firmware!
Process firmware time: 13 seconds

**Comment by badabing2005** [comment]
Can you please provide a support file generated by PixelFlasher.

**Comment by ToddTheOdd** [comment]
Already provided it in the first message but i can add it again.

[support_2023-12-09_18-14-12.zip](https://github.com/badabing2005/PixelFlasher/files/13626890/support_2023-12-09_18-14-12.zip)

**Comment by badabing2005** [comment]
What you previously provided is not a support file, it is a portion of console log, which is not enough to troubleshoot the issue you reported.

Looking at the support file, you database is corrupted, it is missing records, I don't know how you got into that state, and I can't perceive that PF would have been capable of causing that type of a corruption, in any case to resolve your issue.
- Start PF, and click on the help menu and select **Open Configuration folder**
- Exit PixelFlasher
- Delete `PixelFlasher4.db`
- Start PixelFlasher and you should be fine.

**Comment by ToddTheOdd** [comment]
I have provided the support file from the beginning. Anyhow it now works when i deleted the db-file that you suggested. And the only thing i have been doing is update PixelFlasher when a new version is arriving so i haven't touched that db-file by myself so if it have gone corrupted it isn't me.

![1](https://github.com/badabing2005/PixelFlasher/assets/49440324/ffa963a4-a6a4-4fdd-9cc5-8c2a2ae4c391)
![2](https://github.com/badabing2005/PixelFlasher/assets/49440324/b29ac1c2-34c7-4050-b51b-bf7858924b2d)
![3](https://github.com/badabing2005/PixelFlasher/assets/49440324/04ec797e-ebb2-4853-ba09-08dc638e841f)

**Comment by badabing2005** [comment]
> I have provided the support file from the beginning.

Oh shoot, I'll be damned, I see it now, I see you had a link, and I was looking for an attachment, sorry about that.
Thanks for confirming that everything is working now.
