### ISSUE TITLE
大神 请问能否开发一个救黑砖的功能，设置付费都没问题，感谢，升级安卓14后死机了没任何方法能启动。

### ISSUE THREAD

**Issue by MIKIDIGMON** [badabing2005/PixelFlasher#134]
![QQ截图20231210203757](https://github.com/badabing2005/PixelFlasher/assets/153434399/5383e843-e98e-46b6-a00d-60cbca4c0448)
pixel7 连接电脑只在设备管理器显示端口，按键组合无论怎么按都进不了rec和fastboot，希望能开发救砖功能，类似高通的9008模式

**Comment by badabing2005** [comment]
I'm sorry, I don't see a question in there, nor an explanation of what problems you're encountering, what are you performing, what outcome you're expecting and what are you getting instead.
Nor I do see a support file. All I see is a screenshot of Device manager in a language I don't understand.

**Comment by MIKIDIGMON** [comment]
Sorry, I thought you were speaking Chinese. My pixel7 became bricked after it crashed after upgrading to Android 14. I hope the software can add a function to repair the bricking. If you need to pay for it, I can help.
The screenshot is of my pixel7 being bricked and connected to the computer. The device manager only shows the port and can no longer recognize the Android device.

**Comment by badabing2005** [comment]
If your device is truly bricked, I'm afraid your only option is to contact Google and RMA, there is no known method to repair a bricked Pixel.
