### ISSUE TITLE
Build.prop parsing does not work on Windows

### ISSUE THREAD

**Issue by eikaramba** [badabing2005/PixelFlasher#135]
Using 6.3.3.0 on windows 10 x64.

after selecting a single build.prop file the loading indicator spins forever and nothing happens. the log does not show anything, just:

```
2023-12-14 16:48:30 User presses Process build.prop
Selected files: ['E:\\xxxxx\\fingerprints\\xxxxx\\build.prop']
```

i tried multiple and also changed the encoding and file endings of the file.

**Comment by eikaramba** [comment]
it was because i was using the 2019 exe release. with the normal exe it works ;)

**Comment by badabing2005** [comment]
Thanks for reporting.
I think in-place union feature used in that part of the code is not supported in the older versions of Python.
I'll make a change so that it would work.
