### ISSUE TITLE
PlayIntegrityNEXT support

### ISSUE THREAD

**Issue by nyakze** [badabing2005/PixelFlasher#136]
Hey! Thanks for all your work!
Could you please add support for https://github.com/daboynb/PlayIntegrityNEXT
It has the same custom pif.json location as the original module (/data/adb/pif.json)

**Comment by badabing2005** [comment]
I'm confused, if that module downloads fp automatically, what would you use PixelFlasher for?

**Comment by nyakze** [comment]
To clarify, the module itself doesn't do this, the supplied apk does. Someone might choose to use their own fingerprint instead of the one supplied by apk sometime in the future, so added support in pixelflasher would be appreciated just to easily replace the pif. (just so pixelflasher would recognize that pif is installed and allow reading and replacing pif,json)

**Comment by badabing2005** [comment]
If fetching of fp is done by the apk, what is the point of the module? @chiteroman or @osm0sis modules could be used.
I see that it is two commits ahead and 110 commits behind.
So the only change that this module has over @chiteroman's is that it has a donation link, but it is way behind and not maintained.

I can add support for sure, but I don't want to go on chasing adding support for every fork unless the fork actually adds value that people would be interested in.
And from the looks of it, the value added is in the apk and not the module.

Am I missing something?

**Comment by nyakze** [comment]
I think you are essentially correct for now. But in the future (in our terms that's days, not even weeks, with how fast things are progressing), I see a lot of people using this module (just because it's convenient and they didn't learn that apk can be used with the chiteroman version) and wanting to tryout custom fp. So they find a PixelFlasher, boot it up and it wouldn't find pif module, so they won't be able to easily exchange fingerprints. That's my only concern.

**Comment by nyakze** [comment]
Actually, it seems that apk will only with the next module

**Comment by badabing2005** [comment]
I'll add support for it in the next version.

**Comment by osm0sis** [comment]
I'd advise against supporting projects that delete all the commit history like that.

I reimplemented their core benefit in a 4 line script which you can run on your device now instead of waiting for some dude to update his GitHub repo:

https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/page-387#post-89233630

**Comment by badabing2005** [comment]
In the spirit of open source projects, I decided not to support projects that go against that openness, specially if the project is a fork of an open source project.
In my opinion deleting commit history is a faux pas.
I will reconsider my position if the situation changes.
