### ISSUE TITLE
Add Dark Theme Support

### ISSUE THREAD

**Issue by HennyBro** [badabing2005/PixelFlasher#14]
Dear developer,

It's 2022 and all programs should have a dark theme. Though I understand that this is a free software that you provide without monetising it in any way, so it's really only up to you if you think a dark theme should be implemented or not. But I think every software (regardless of what it is) should support this feature for feature-parity and a more consistent UX.

In love,
A great fan of your program :)

**Comment by badabing2005** [comment]
Thanks for the feedback and the request.
I'm totally with you.
There was a similar request at XDA forums.
See the full details and the reasons why there is no Dark theme support for Windows.
Details follow this post.
https://forum.xda-developers.com/t/pixelflasher-for-google-pixel-6-pro-support-thread.4419561/post-86850735
