### ISSUE TITLE
Detected as Malware by NordVPN

### ISSUE THREAD

**Issue by superbats** [badabing2005/PixelFlasher#140]
For some reason, I cannot download any of the latest versions as it's being detected as malware.

I've attached a screenshot of what NordVPN is saying whenever I try to download a Windows executable file.

![2023-12-27 - PixelFlasher Download](https://github.com/badabing2005/PixelFlasher/assets/155029056/06c98dc9-db7e-45a2-9ceb-e36b9e81878a)

**Comment by badabing2005** [comment]
https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/page-88#post-89090938

You can also see many similar issues here on Github with false positives.
