### ISSUE TITLE
Windows defender detect Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by otraver** [badabing2005/PixelFlasher#141]
I downloaded latest update v6.5.1.1 and windows defender detects it as a  Trojan:Win32/Wacatac.H!ml
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FWacatac.H!ml&threatid=2147814523

**Comment by badabing2005** [comment]
Please see [this](https://github.com/badabing2005/PixelFlasher/tree/v6.5.1.1#troubleshooting).
It's false positive.
