### ISSUE TITLE
v6.5.3.1

### ISSUE THREAD

**Issue by TTA1326** [badabing2005/PixelFlasher#142]
BitDefender is suddenly jumping up and down claiming PixelFlasher.exe is infected with Gen:Variant.Tedy.507685.  I tried the two previous versions as well and have the same problem.  It's never done this before.

**Comment by badabing2005** [comment]
See Readme
![image](https://github.com/badabing2005/PixelFlasher/assets/22603312/5a315586-d0c5-4ea2-99c2-be88a50fb2df)

Same as many other issues #141, #140 ...
