### ISSUE TITLE
I tried to relock the bootloader by using PF 6.5.3.1

### ISSUE THREAD

**Issue by supermansaga** [badabing2005/PixelFlasher#143]
Upon relocking, the device enters this "no valid operating system could be found. The device will not boot. Visit this link on another device: g.co/ABH. ID: e5362ddf. Code: 3." It asks me to "press power button to power off." But it doesn't work. 

I then tried to hold down volume Down key + power key for 30 seconds, but nothing happens either. I am freaking out. Thanks.

**Comment by badabing2005** [comment]
Did you unroot / restore to stock your device on both slots prior to locking the bootloader?

**Comment by badabing2005** [comment]
Closing the issue, please update if this is still an issue.

**Comment by supermansaga** [comment]
No more issue as you had already taught in the forum. Many thanks.
