### ISSUE TITLE
6.6.1.0 crashing when selecting firmware

### ISSUE THREAD

**Issue by nekolifestyle** [badabing2005/PixelFlasher#146]
I tried both linux builds but issue persists

**Comment by badabing2005** [comment]
I'm sorry what issue are you talking about?

**Comment by badabing2005** [comment]
Please provide support file and exact steps.

**Comment by badabing2005** [comment]
@nekolifestyle 
Without support file, and additional details I'm inclined to close this issue.
Please check #111, if you have newer Linux like in #111 you might want to add the exclusion in PF settings.

**Comment by nekolifestyle** [comment]
Once the application is open and select the location of the sdk platform tools is set. I download the firmware of my phone I want to update. Device is detected and when I select the firmware to update the device. Pixel flasher crashes and double checked to make such the file downloaded properly.

**Comment by nekolifestyle** [comment]
Load time: 9 seconds
2024-01-16 00:43:22 The following firmware is selected:
raven-uq1a.240105.002-factory-2bb682a7.zip
Selected Firmware raven-uq1a.240105.002-factory-2bb682a7.zip SHA-256: 2bb682a7c5c0f94f090b24ddff44877b66898a6147aa65bfa3f7be0b7bec4e69
Expected to match 2bb682a7 in the filename and did. This is good!

Please Process the firmware!

2024-01-16 00:43:41 User initiated Process firmware

==============================================================================
 2024-01-16 00:43:41 PixelFlasher 6.6.1.0         Processing firmware file ...
==============================================================================
Low memory option:     False
Available Free Memory: 56.71 GB / 62.69 GB
Factory File:          /home/user/Downloads/raven-uq1a.240105.002-factory-2bb682a7.zip
Detected Pixel firmware

**Comment by badabing2005** [comment]
@nekolifestyle 
Did you check #111 

Please create a support file in PixelFlasher and submit that.
Don't try to process anything, just open the app, create support file and provide the zip it creates.
