### ISSUE TITLE
Automatically select firmware after downloading

### ISSUE THREAD

**Issue by mkomko** [badabing2005/PixelFlasher#147]
When downloading the device image with PixelFlasher, the newly downloaded image is not set in the Device image path text box. Instead, the previously selected device image remains there. So when downloading a new device image and then clicking process, the old firmware may be processed or, in my case, an exception occurred because I had already deleted the old device image.

Please consider this small inconvenience for further improvement. If you have any questions please let me know.

Thank you and much love for this wonderful tool!

**Comment by badabing2005** [comment]
It all depedns on the use case.
I had thought about that.
The fact that the download happens in the background and the file is not available until download completes makes it tricky.
When you have background processes running, you could be using PF to do other things, and those operations are blocking (serial) operations, you don't want or sometimes can't trigger another operation  that could potentially break what you're doing.

For example when there are downloads available, I initiate download for all my devices, and they run as background process,
Then I could also be processing one of them or rebooting or even flashing one.

On the surface it sounds simple, but implementing something robust that accounts for all cases, and of course doesn't confuse the user is easier said than done.

Technically, I can also process, create patch and even flash all automatically.
Do you want that?

Let me know what you think.

**Comment by mkomko** [comment]
Thank you for your thoughtful reply. I haven't really thought about other use cases, I'm sorry about that.

I would not be a fan of even more running automatically, actually. I would be too afraid of something going wrong or some option being set wrong, even though it's probably irrational since so much is happening automatically anyway.

Another idea: Maybe you could make the background download optional? For my use case (and I suspect it might be the most-used case) a blocking download would suffice:
Download the newest full OTA image, process it, patch the boot image, select the boot image, flash it.

**Comment by badabing2005** [comment]
Download thake quite a while, and blocking an application for the duration of such download is bad, the app will appear frozen.
I don't have any plans to block the app while such a large download is happening.

I'll see if I can find a different solution, but it's low on my priority list as you have to weigh that against the user having to select the downloaded file with the file selector.

**Comment by mkomko** [comment]
I was thinking more along the lines of a popup with a progress bar, not just blocking the UI without anybody knowing what's going on. Since it's not so simple you can disregard my request entirely, no problem at all. I just hope you don't get many "support cases" where people unknowingly processed their old image and re-flashed that 😉

**Comment by badabing2005** [comment]
I took a stab at it, and realized that it's even more trouble than initially anticipated, unless I totally block, which I don't plan to as the user experience would be really suffer, the background thread won't be able to update the database unless I refactor the code.
`SQLite objects created in a thread can only be used in that same thread.`

Simply not enough ROI.
