### ISSUE TITLE
Lock / Unlock Bootloader Backwards?

### ISSUE THREAD

**Issue by zQueal** [badabing2005/PixelFlasher#15]
I'm sending my phone back to Google for a hardware issue. I flashed stock firmware, and went to relock the bootloader through PixelFlasher. Pressing "lock bootloader" actually unlocked it. I tried it a few times, and it unlocked it every time. Only when I pressed "unlock bootloader" did I get the message to lock my bootloader.

Could these be backward or something in the app?

**Comment by zQueal** [comment]
```cmd
2022-06-25 00:20:19 Unlock Bootloader
WARNING!!! THIS WILL ERASE ALL USER DATA FROM THE DEVICE

Make sure you first read either of the guides linked in the help menu.
Failing to follow the proper steps could potentially brick your phone.

Note: Pressing OK button will invoke a script that will utilize
fastboot commands, if your PC fastboot drivers are not propely setup,
fastboot will wait forever, and PixelFlasher will appear hung.
In such cases, killing the fastboot process will resume to normalcy.

      Do you want to continue to Unlock the device bootloader?
              Press OK to continue or CANCEL to abort.

2022-06-25 00:20:28 User Pressed Ok.
Unlocking bootloader for device 1B021JEG502001 ...
debug: "C:\Utilities\adb\fastboot.exe" -s 1B021JEG502001 flashing lock
```

**Comment by badabing2005** [comment]
Thank you for bringing this up, you are right, it turns out the lock button was calling the unlock function  and vice versa.
I'll push a fix soon.
Good thing you figured it out.
