### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by DroidFreak32** [badabing2005/PixelFlasher#151]
On MacOS version 6.7.1.0 the PIF utility is generating SSL errors

```
2024-02-02 19:11:15 ERROR: Exception during getUpdateDetails url: https://raw.githubusercontent.com/osm0sis/PlayIntegrityFork/main/update.json processing
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1096, in _validate_conn
  File "urllib3/connection.py", line 642, in connect
  File "urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
  File "urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1383, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 844, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /osm0sis/PlayIntegrityFork/main/update.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

```

**Comment by badabing2005** [comment]
Please create and provide support file.

**Comment by DroidFreak32** [comment]
Here you go
[support_2024-02-03_03-25-04.zip](https://github.com/badabing2005/PixelFlasher/files/14145883/support_2024-02-03_03-25-04.zip)

**Comment by badabing2005** [comment]
Thanks
For whatever reasons, your MacOS doesn't seem to have the proper certificate authorities in the certificate store.
I'll make sure the next version  will make all http requests fallback to SSL verification false if it encounters SSL errors.

**Comment by DroidFreak32** [comment]
You are right, it's my VPN that is performing TLS Inspection causing this problem, thanks for pointing out
I tried `curl -v 'https://raw.githubusercontent.com/osm0sis/PlayIntegrityFork/main/update.json'` 
And the TLS Handshake indicate Cisco Certificate and not DigiCert.
```
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cisco Systems, Inc.; CN=raw.githubusercontent.com
*  start date: Feb  1 08:29:12 2024 GMT
*  expire date: Feb  6 08:29:12 2024 GMT
*  subjectAltName: host "raw.githubusercontent.com" matched cert's "raw.githubusercontent.com"
*  issuer: O=Cisco; CN=Cisco Umbrella Secondary SubCA sin-SG
```

Also,
> I'll make sure the next version will make all http requests fallback to SSL verification false if it encounters SSL errors.

This is an issue on my side, I don't think doing this is necessary as it could have other security implications.

**Comment by badabing2005** [comment]
I'll have a warning like [the following](https://github.com/badabing2005/PixelFlasher/blob/d914cff58764d7b133b7f98bfed12e23459eada7/runtime.py#L2265-L2267).

I've made the changes, it will be part of the next release.
I don't know if I want to go as far as importing a certificate, mainly because when you launch the app, it unpacks it into a new temporary space for the executable and the certificate will not be there.
Either you'd have to import it on each use which is not practical, or I'd have to persist it externally and load it each time, it can be done, but too much hassle for little gain.

**Comment by DroidFreak32** [comment]
Understood, thank you for addressing this.
