### ISSUE TITLE
feature request for application selection

### ISSUE THREAD

**Issue by seriousfreedom** [badabing2005/PixelFlasher#152]
i think it would be nice to be able to select all user apps  separetly from the systems apps in stead of just check all something like check all user,  check all system, and check all

and also the ability to backup magisk modules as well

**Comment by badabing2005** [comment]
You want check all user app and check all system apps?
Or you prefer filtering to show all user and or all system?

Backing up Magisk modules was discussed [here](https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/post-89271668).
See my comments further down in that thread and provide your feedback based on that please.

**Comment by badabing2005** [comment]
Done, will be available in the next release.
![image](https://github.com/badabing2005/PixelFlasher/assets/22603312/f5425304-ea86-4afb-8160-e7632cd4d789)

**Comment by badabing2005** [comment]
Done
