### ISSUE TITLE
Error when checking for unlocker bootloader with Android Platform Tools 34.0.4

### ISSUE THREAD

**Issue by ssorgatem** [badabing2005/PixelFlasher#153]
I attack the full log
[PixelFlasher_2024-02-05_22h52m50s.log](https://github.com/badabing2005/PixelFlasher/files/14172573/PixelFlasher_2024-02-05_22h52m50s.log)

**Comment by badabing2005** [comment]
It looks like when your device is in bootloader mode it is not detected.
I can add a check for that to avoid the error and abort.
But you will need to make sure that proper USB drivers are installed, in fastboot mode as well.
Can you do the following test?

reboot to bootloader
`adb reboot bootloader`
check what you get with 
`fastboot devices`

**Comment by ssorgatem** [comment]
I'm on Linux 6.1.71-1-MANJARO.
fastboot on the command line works without problems. If I manually execute the flash script generated by PixelFlasher it works.
`fastboot devices` outputs `3A211FDJG006R0`

**Comment by badabing2005** [comment]
Please update Android platform tools to the latest 34.0.5 and try again.

**Comment by ssorgatem** [comment]
Seems to be working now.

Maybe PixelFlasher could give a warning if it detects version 34.0.4?
