### ISSUE TITLE
BUG: "AttributeError: 'PifManager' object has no attribute 'first_api'"

### ISSUE THREAD

**Issue by timothylcooke** [badabing2005/PixelFlasher#157]
When I try to process a build.prop on 6.7.1.0 on Windows 10 x64, the log outputs:

    AttributeError: 'PifManager' object has no attribute 'first_api'

Workaround is to check then uncheck the "Force First API to 25" CheckBox. Then, I get the error:

    AttributeError: 'PifManager' object has no attribute 'keep_unknown'

Workaround is to check then uncheck the "Keep All keys" CheckBox. After checking/unchecking both of those CheckBoxes, it works.

**Comment by badabing2005** [comment]
Thanks for reporting this, I had noticed this possibilty and had already updated the local development code (part of next release) to address this.
It will definitely be part of the next release,

**Comment by timothylcooke** [comment]
I discovered later there are similar bugs with all four checkboxes, when smart pasting. Thanks for the great tool!

**Comment by badabing2005** [comment]
Hmmm, I only detected an issue with 3 of the 4
Add Missing Keys shouldn't cause an issue, if it does, I apreciate if you could reproduce the issue and create a support file so that I can see how it's happening.

Thanks

**Comment by timothylcooke** [comment]
I probably didn't run into missing keys. Sorry, likely a bad error report on that front. I remember the sorting one was necessary to get one of the paste buttons to work. Thanks again for the wonderful project!
