### ISSUE TITLE
v6.8.0.3 still points to v6.8.0.2 ?

### ISSUE THREAD

**Issue by ko3st** [badabing2005/PixelFlasher#158]
After clicking on Help > About PixelFlasher, the Message window still says:  
Update Version v6.8.0.3 is available.
I think a minor thing is not updated yet, since this is supposed to be version v6.8.0.3 already.
Perhaps the current link https://github.com/badabing2005/PixelFlasher/releases/download/v6.8.0.3/PixelFlasher.exe
still points to the previous version? Can you replace the previous exe version with the newest one please?

**Comment by krugm0f0** [comment]
Same

**Comment by badabing2005** [comment]
Thanks folks, I'll get it fixed soon, I think I forgot to increment the version in the app.

**Comment by ko3st** [comment]
OK I thought it was a minor thing (not even a bug) anyway :-).
Keep up the good work. 

I know this is nit the right place but... 
I do hope you can help me with my (soft) bricked Pixel 8 Pro. Most checkboxes in v6.8.0.2 are not available to me. To me it looks like the (expensive 512 GB) P8P phone is now redy to go into the bin :-(.
Please see https://xdaforums.com/t/pixelflasher-for-google-pixel-8-pro-support-thread.4635555/page-19#post-89346009

**Comment by badabing2005** [comment]
Fixed

**Comment by ko3st** [comment]
Hi badabing2005,

Nice work.

Kind regards,
Kees

Op za 17 feb 2024 om 16:44 schreef badabing2005 ***@***.***>:
