### ISSUE TITLE
Bricked my device by attempting to install a patched boot image...

### ISSUE THREAD

**Issue by dinosoup1** [badabing2005/PixelFlasher#160]
[support_2024-02-21_18-54-44.zip](https://github.com/badabing2005/PixelFlasher/files/14367553/support_2024-02-21_18-54-44.zip)
<img width="1512" alt="SCR-20240221-quqx" src="https://github.com/badabing2005/PixelFlasher/assets/45948999/fb29875f-7834-41b5-b2bb-aaf54e6385fc">

I used the tool to download the update file that properly matched my device and I used a known good USB C cable to do the flash. I wanted to just update my phone to the newest firmware while keeping data and root intact. I did not disable any Magisk modules but I could not find any info about the ones I had installed causing issues. After I got the output in the little terminal window, I figured that I needed to just manually reboot my device myself using the recovery menu (as it was stuck on the recovery menu) so that is what I did. The device then rebooted to fastboot, then showed the Google logo quickly after, then went back to fast boot again. Then it redid that same process and the phone became completely bricked. I am on Mac and I speculate this might be part of the problem but I am not entirely sure. 

It might be that my Mac constantly asks me to "allow connection" to my USB devices any time it recognizes a new one (sometimes this seems to be even the same device just in a different "mode" like fastboot or whatever). I have done flashes with other tools also on Mac and this has not been a problem before. However, when this happens, it blocks the connection. It did come up during installation earlier on in the process but I quickly allowed it and the tool seemed to have carried on as though nothing happened. From there I will let the logs do the talking. I followed all the instructions from the guide otherwise. I get it my phone was rooted and it was at my own risk so I take responsibility. I should have just rebooted back to fastboot and wiped my phone to be safe but I was confused. Just wanted to share the logs to prevent this from happening to someone else.

**Comment by badabing2005** [comment]
See this in your logs
```
Sending sparse 'product_a' 7/12 (262124 KB)        OKAY [  6.657s]
Writing 'product_a'                                OKAY [  1.173s]
Sending sparse 'product_a' 8/12 (262124 KB)        OKAY [  6.701s]
Writing 'product_a'                                OKAY [  1.148s]
Sending sparse 'product_a' 9/12 (262124 KB)        OKAY [  6.792s]
Writing 'product_a'                                ERROR: usb_read failed with status e00002ed
FAILED (Status read failed (Undefined error: 0))
fastboot: error: Command failed
```
This is a communication problem,
It could be any of:
- USB Cable
- USB drivers (not applicable for you as you're on MAC)
- USB Port
- The connection

If the device is getting into bootloader mode, you can try again, or alternately you can sideload the OTA image (recommended) if the device is able to get into recovery mode.

**Comment by dinosoup1** [comment]
Could it be included as part of the guide for Mac or mentioned by the tool as a popup when the user starts the tool on Mac: https://support.apple.com/en-us/102282 ? As in, notifying users they should disable the request process temporarily before they use the tool? Yeah unfortunately my device ended up fully bricked, it's going to Google as we speak but live and learn.

**Comment by TheVisual** [comment]
> Could this be included as part of the guide for Mac or mentioned by the tool as a popup when the user starts the tool on Mac: https://support.apple.com/en-us/102282 ? As in, notifying users they should disable the request process temporarily before they use the tool? Yeah unfortunately my device ended up fully bricked, it's going to Google as we speak but live and learn.

same black screen bricked

**Comment by badabing2005** [comment]
Added into the readme pre-requisities.
