### ISSUE TITLE
Error when parsing pi.xml using Pif manager (Chinese characters in pi.xml)

### ISSUE THREAD

**Issue by lupohan44** [badabing2005/PixelFlasher#161]
Console logs:

> Traceback (most recent call last):
>   File "pif_manager.py", line 943, in PlayIntegrityCheck
>   File "runtime.py", line 2570, in process_pi_xml_piac
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 3466: illegal multibyte sequence

pi.xml file contains Chinese characters
position 3466 related XML:

`<node index="1" text="" resource-id="" class="android.widget.ImageView" package="gr.nikolasspyr.integritycheck" content-desc="更多选项" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[1300,158][1440,326]" />`

In the [process_pi_xml_piac function](https://github.com/badabing2005/PixelFlasher/blob/main/runtime.py#L2569-L2570), open did not specify encoding, causing it to use gbk on Windows.

In my pi.xml's header, it declares the encoding should be UTF-8 `<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>`

I think you should either use UTF-8 as default encoding or using some charset detection library to detect the encoding before open it

**Comment by badabing2005** [comment]
Done in v6.8.1.0
