### ISSUE TITLE
Clear Find My Device -> Secure Device Admin passwd without having to Factory Reset and lose all data

### ISSUE THREAD

**Issue by YDB2** [badabing2005/PixelFlasher#163]
badabing,

I love your PixelFlasher tool! It has made the monthly update process so much faster, cleaner and reliable! 

This request comes after doing something stupid (setting my Pixel 8 on the ground, driving off and not realizing it until home ~100Km away) and then doing another stupid thing on top of that (setting the Find My Device -> Secure Device Admin passwd and then accidentally deleting the passwd from my passwd manager app). Now I have a phone that can only receive calls, but I can't make calls of do anything else with because I can't get the display unlocked, and I have some valuable (to me) data on it that's not 'cloud backed' or I would probably just boot to Recovery and Factory Reset it. 

Since you've done so much with your PixelFlasher and it gets better all the time, is that a possibility? Currently when I boot it to Recovery  I can Mount /system and thought I may be able to open a Shell but that errors out "adbd F 02-27 15:18:31   520   520 shell_service.cpp:380] Could not set SELinux context for subprocess
libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 520 (adbd), pid 520 (adbd)". I'm assuming that at least in part the 'SE' security is preventing it from happening. 

I can get to Rescue mode too but not sure where to go from there.

Since your PixelFlasher has so many cool features already, how about one more?

Thank you.

**Comment by badabing2005** [comment]
Sorry, this is a device side feature, and PixelFlasher is just a client that connects to the device and communicates with it / drives it.
You would need something like TWRP recovery, but as we know, it doesn't exists for recent phones.

Thanks for your confidence in PF. :)
