### ISSUE TITLE
Cannot launch with debian

### ISSUE THREAD

**Issue by SalvatoreNoschese** [badabing2005/PixelFlasher#165]
Hi. Sorry but i change from arch to debian stable, and seems i cannot start.
Maybe some missed requirements? Hope u can help.
Best regards,
S.N.
![Screenshot_20240303_163610](https://github.com/badabing2005/PixelFlasher/assets/16841896/95eafb5d-c1f1-44f6-9434-838757ae593d)

**Comment by badabing2005** [comment]
Can you run with `--console` argument and provide the output?

**Comment by SalvatoreNoschese** [comment]
Hi, after some test, see some issue with all gtk apps (like synaptic and similar: no icon or just some).
Changed theme (issue seems to be related with dark breeze), now icons are present and pixel flasher 22.04 start as expected. Maybe is best to switch to debian testing :)
