### ISSUE TITLE
Create a message box, explaining something about the last setting the user made, in relation to the current configuration

### ISSUE THREAD

**Issue by ko3st** [badabing2005/PixelFlasher#167]
I asked HipKat 
 To double-check here and now with you:

I clicked this **radio button**:
Keep Data

I selected ONLY these **four(!) checkboxes**:

Flash to Inactive slot
Disable Verity
Disable Verification
Verbose

[@HipKat](https://xdaforums.com/m/3615140/) 
You can't keep data if you're checking disable verity and verification, but you MUST check those if you use a custom kernel or ROM with a kernel baked in.

My suggestion would be to check in PixelFlasher if a setting does not make sense ir is not allowed. 
Perhaps you could program it in such a way that certain settings are immediately Grayed out, but that would possibly require a lot of background checking... 

I think it would be much easier, just to inform the user via a little popup message, explaining something about the last setting made in the whole current configuration, perhaps explaining why it would be unwise to proceed if the last alteration was to be "accepted".

Perhaps in the message, you could even suggest a different setting, and if you would want to make it completely safe, you could ask if the user is willing to proceed with the PF suggested "custom" setting, instead current configuration in relation to the last alteration (which normally does _not_ make sense, and which triggered the message in the first place).

In the end, the user remains always responsible for his/her own choices, even if they were (automatically) suggested by PF.

I think it would be a nice touch if you could incorporate the knowledge of experts like HipKat and you, and about certain settings  :-).

**Comment by badabing2005** [comment]
This is already in place.
See [here](https://github.com/badabing2005/PixelFlasher/blob/91e2c165d5fabec354275bc7bcee2f124d7ab830/Main.py#L2174-L2176)

The best PF can do is warn the user about it, this could be intentionally selected option by the user to be able to flash custom kernel, why would I gray it out?
