### ISSUE TITLE
What could I be doing wrong / Is something wrong?

### ISSUE THREAD

**Issue by ko3st** [badabing2005/PixelFlasher#168]
**What could I be doing wrong / Is something wrong?**

OK [@HipKat](https://xdaforums.com/m/3615140/) , this is what I did:
14.0.0 (AP1A.240305.019.A1, Mar 2024) Link:
1. Downloaded https://dl.google.com/dl/android/aosp/husky-ota-ap1a.240305.019.a1-f1130be5.zip

2. Clicked Patch husky-ota-ap1a.240305.019.a1

3. Selected husky-ota-ap1a.240305.019.a1 Patched with Magisk (27.0:27000)

4. I used Flash Mode: Full OTA

5. Flash Options:
Flash to Inactive slot
Disable Verity
Disable Verification
Verbose

Clicked the big button and waited....

This is the result:
........
Total xfer: 2.00x
2024-03-04 21:35:02 Done flash script execution!
Sleeping 10 seconds ...

2024-03-04 21:35:12 Getting device: 3A251FDJG005HC state retry [4] times ...
debug: :Getting device: 3A251FDJG005HC state [1/4] using get-state
debug: "C:\platform-tools\adb.exe" -s 3A251FDJG005HC get-state
Currently the device is in recovery mode.
Updating connected devices ...

Selected Device on 2024-03-04 21:35:13:
Device ID: 3A251FDJG005HC
Device Model:
Device Active Slot:
Device Mode: sideload
Has init_boot partition: False
Device Bootloader Version:
Device is Rooted: False
Device Build:
Device API Level:
Device Architecture:
Device Kernel: None
Device Kernel Version:
Device KMI:
sys_oem_unlock_allowed:
ro.boot.flash.locked:
ro.boot.vbmeta.device_state:
ro.product.first_api_level:
ro.boot.veritymode:
ro.boot.verifiedbootstate:
ro.secure:
ro.zygote:
ro.vendor.product.cpu.abilist:
ro.vendor.product.cpu.abilist32:
Magisk Manager Version: :
Magisk Path: None
Checked for Package: com.topjohnwu.magisk

2024-03-04 21:35:13 Getting device: 3A251FDJG005HC state ...
debug: :Getting device: 3A251FDJG005HC state [1/1] using get-state
debug: "C:\platform-tools\adb.exe" -s 3A251FDJG005HC get-state
Rebooting device: 3A251FDJG005HC to bootloader ...
debug: "C:\platform-tools\adb.exe" -s 3A251FDJG005HC reboot bootloader
Fastboot waiting for device: 3A251FDJG005HC for bootloader ...
device: 3A251FDJG005HC is now in bootloader mode.
Updating connected devices ...

Selected Device on 2024-03-04 21:35:26:
Device ID: 3A251FDJG005HC
Device Model: husky
Device Active Slot: b
Device Mode: f.b
Device: Pixel 8 Pro
Device First API Level: 34
Device Version End Date: October 2026
Device Secuity Update End Date: October 2030
Has init_boot partition: True
Device Bootloader Version: ripcurrent-14.4-11322024
Device Unlocked: True
slot-retry-count:a:
slot-unbootable:a:
slot-successful:a:
slot-retry-count:b:
slot-unbootable:b:
slot-successful:b:

Getting current slot for device: 3A251FDJG005HC ...
debug: "C:\platform-tools\fastboot.exe" -s 3A251FDJG005HC getvar current-slot
Current slot:
Comparing the current slot with the previous active slot ...

2024-03-04 21:35:26 ERROR: It appears that OTA flashing did not properly switch slots.
Aborting ...
Aborting ...

Sleeping 10 seconds ...
Updating connected devices ...

Selected Device on 2024-03-04 21:35:36:
Device ID: 3A251FDJG005HC
Device Model: husky
Device Active Slot: b
Device Mode: f.b
Device: Pixel 8 Pro
Device First API Level: 34
Device Version End Date: October 2026
Device Secuity Update End Date: October 2030
Has init_boot partition: True
Device Bootloader Version: ripcurrent-14.4-11322024
Device Unlocked: True
slot-retry-count:a:
slot-unbootable:a:
slot-successful:a:
slot-retry-count:b:
slot-unbootable:b:
slot-successful:b:

Flashing elapsed time: 642 seconds
------------------------------------------------------------------------------

2024-03-04 21:35:36 INFO: Flashing was aborted.
This could be user initiated or a problem encountered during flashing.

2024-03-04 21:35:36 Getting device: 3A251FDJG005HC state ...
debug: :Getting device: 3A251FDJG005HC state [1/1] using get-state
debug: "C:\platform-tools\adb.exe" -s 3A251FDJG005HC get-state
debug: :Getting device: 3A251FDJG005HC state [1/1] using fastboot devices
Current device mode: fastboot
You might need to manually reboot your device.

Updating connected devices ...

Selected Device on 2024-03-04 21:35:37:
Device ID: 3A251FDJG005HC
Device Model: husky
Device Active Slot: b
Device Mode: f.b
Device: Pixel 8 Pro
Device First API Level: 34
Device Version End Date: October 2026
Device Secuity Update End Date: October 2030
Has init_boot partition: True
Device Bootloader Version: ripcurrent-14.4-11322024
Device Unlocked: True
slot-retry-count:a:
slot-unbootable:a:
slot-successful:a:
slot-retry-count:b:
slot-unbootable:b:
slot-successful:b:

**Comment by badabing2005** [comment]
Please provide a support file
What you're saying does not add up.
If you selected OTA image, you can not get the options you're describing.
Please follow the readme / guide in here at Github, your steps are missing and not adding up.
If you have any questions about specific steps, bring them up.

**Comment by ko3st** [comment]
[support_2024-03-04_23-20-25.zip](https://github.com/badabing2005/PixelFlasher/files/14487920/support_2024-03-04_23-20-25.zip)

Sorry, but I think did exactly what I wrote...

**Comment by ko3st** [comment]
Here you go.
 I just added it in the post.


Op ma 4 mrt 2024 om 23:31 schreef badabing2005 ***@***.***>:

**Comment by badabing2005** [comment]
I'll provide my answer here this time, but please do not log usage question / support tickets in Github unless you're creating a bug ticket or a feature request.
Please use the [XDA Forums thread](https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/) for such questions.

> Downloaded https://dl.google.com/dl/android/aosp/husky-ota-ap1a.240305.019.a1-f1130be5.zip
>
> Clicked Patch husky-ota-ap1a.240305.019.a1
>
> Selected husky-ota-ap1a.240305.019.a1 Patched with Magisk (27.0:27000)
>
> I used Flash Mode: Full OTA
>
> Flash Options:
> Flash to Inactive slot
> Disable Verity
> Disable Verification
> Verbose

This is not true.
You started with a device in the following state.

```
Selected Device on 2024-03-04 17:52:50:
    Device ID:                       REDACTED
    Device Model:                    husky
    Device Active Slot:              b
    Device Mode:                     adb
    Device:                          REDACTED 8 Pro
    Device First API Level:          34
    Device Version End Date:         October 2026
    Device Secuity Update End Date:  October 2030
    Has init_boot partition:         True
    Device Bootloader Version:       ripcurrent-14.1-11208047
    Device is Rooted:                False
    Device Build:                    UQ1A.240205.004
    Device API Level:                34
    Android Version:                 14
    Android Name:                    Android 14
    Android Codename:                Upside Down Cake
    Android Release Date:            Q3 2023
    Android Latest Update:           Present
    Device Architecture:             arm64-v8a
    Device Kernel:                   Linux localhost 5.15.110-android14-11-gcc48824eebe8-ab10865596 #1 SMP PREEMPT Tue Sep 26 19:57:58 UTC 2023 aarch64 Toybox
    Device Kernel Version:           5.15
    Device KMI:                      5.15.110-android14
    sys_oem_unlock_allowed:          1
    ro.boot.flash.locked:            0
    ro.boot.vbmeta.device_state:     unlocked
    ro.product.first_api_level:      34
    ro.boot.veritymode:              enforcing
    ro.boot.verifiedbootstate:       orange
    ro.secure:                       1
    ro.zygote:                       zygote64
    ro.vendor.product.cpu.abilist:   arm64-v8a
    ro.vendor.product.cpu.abilist32: 
    Magisk Manager Version:          27.0:27000
    Magisk Path:                     /data/app/~~z70OLCGUr7ve6Gd_yfValw==/com.topjohnwu.magisk-U1xVyWLxMX-AWeR__MUWmg==/base.apk
        Checked for Package:         com.topjohnwu.magisk
```

The relevant settings were:
```
    "disable_verification": false,
    "disable_verity": false,
    "flash_both_slots": false,
    "flash_to_inactive_slot": false,
    "firmware_is_ota": false,
    "firmware_path": "C:\\tmp\\husky-uq1a.240205.004-factory-594e3ca4.zip",
    "firmware_sha256": "594e3ca49d445b04587bb78289dc726606d3d8878fb5cdfb39434f5714d15224",
```

Notice that the selected firmware was not OTA
The next log that I see is the following

```
Selected Device on 2024-03-04 18:12:54:
    Device ID:                       REDACTED
    Device Model:                    husky
    Device Active Slot:              b
    Device Mode:                     f.b
    Device:                          REDACTED 8 Pro
    Device First API Level:          34
    Device Version End Date:         October 2026
    Device Secuity Update End Date:  October 2030
    Has init_boot partition:         True
    Device Bootloader Version:       ripcurrent-14.1-11208047
    Device Unlocked:                 True
    slot-retry-count:a:              
    slot-unbootable:a:               
    slot-successful:a:               
    slot-retry-count:b:              
    slot-unbootable:b:               
    slot-successful:b:               
```

Notice that youre device is in bootloader mode, so whatever you did between 2024-03-04 17:52:50 and 2024-03-04 18:12:54 was done outside of PixelFlasher

And then again outside of PixelFlasher, you rebooted your device to adb mode (can't tell if you did anything else) that's because you wanted to install Magisk (I don't know why, because you alread had same version of Magisk installed previously)

```
Installing C:\Users\REDACTED\AppData\Roaming\PixelFlasher\tmp\magisk_27.0_27000.apk on device ...
debug: "C:\platform-tools\adb.exe" -s REDACTED install   -r "C:\Users\REDACTED\AppData\Roaming\PixelFlasher\tmp\magisk_27.0_27000.apk"
Performing Streamed Install
Success
```

Then you processed February factory image
```
==============================================================================
 2024-03-04 18:18:41 PixelFlasher 6.8.2.1         Processing firmware file ...
==============================================================================
Low memory option:     False
Available Free Memory: 9.58 GB / 15.88 GB
Factory File:          C:\tmp\husky-uq1a.240205.004-factory-594e3ca4.zip
```

Which extracted the init_boot
```
Please select a boot image!
Selected Boot:
    File:                  init_boot.img
    Path:                  C:\Users\REDACTED\AppData\Roaming\PixelFlasher\boot_images4\9a4d04d27754a57db8f64970e6bc1355178be54a\init_boot.img
    SHA1:                  9a4d04d27754a57db8f64970e6bc1355178be54a
    Patched:               False
    Stock Boot:            True
    Init Boot:             True
    Date:                  2024-02-17 15:36:56
    Firmware Fingerprint:  husky-uq1a.240205.004
    Firmware:              C:\tmp\husky-uq1a.240205.004-factory-594e3ca4.zip
    Type:                  firmware
```

Which you used to create a patch
However to be able to create a patch, your device needed to be in adb mode, and not

You selected the patch and then created the first support file
```
Please select a boot image!
Selected Boot:
    File:                  magisk_patched_27000_9a4d04d2_6ef4641e.img
    Path:                  C:\Users\REDACTED\AppData\Roaming\PixelFlasher\boot_images4\9a4d04d27754a57db8f64970e6bc1355178be54a\magisk_patched_27000_9a4d04d2_6ef4641e.img
    SHA1:                  6ef4641ef4fb4645b32dfc1a0e2f3596af26e09d
    Patched:               True
    Patched Method:        app
    Patch Source SHA1:     9a4d04d27754a57db8f64970e6bc1355178be54a
    Patched With Magisk:   27.0:27000
    Patched on Device:     REDACTED
    Stock Boot:            False
    Init Boot:             True
    Date:                  2024-03-04 18:22:21
    Firmware Fingerprint:  husky-uq1a.240205.004
    Firmware:              C:\tmp\husky-uq1a.240205.004-factory-594e3ca4.zip
    Type:                  firmware


Flash mode changed to: keepData

2024-03-04 18:26:07 Creating support.zip file ...
```

And then you finally loaded March OTA file
```
2024-03-04 21:22:50 The following firmware is selected:
husky-ota-ap1a.240305.019.a1-f1130be5.zip
Selected Firmware husky-ota-ap1a.240305.019.a1-f1130be5.zip SHA-256: f1130be5f8ff4f2a2a8c9984d244b47898eaaea924ae9065a4f4ab1bed075442
Expected to match f1130be5 in the filename and did. This is good!

Please Process the firmware!

==============================================================================
 2024-03-04 21:23:21 User initiated Process firmware
==============================================================================

==============================================================================
 2024-03-04 21:23:21 PixelFlasher 6.8.2.1         Processing firmware file ...
==============================================================================
Low memory option:     False
Available Free Memory: 8.83 GB / 15.88 GB
Factory File:          C:\tmp03\husky-ota-ap1a.240305.019.a1-f1130be5.zip
```

Created a patch and flashed the OTA with the following option
```
Flash Mode:             OTA

Custom Flash Options:   True
Disable Verity:         True
Disable Verification:   True
Verbose Fastboot:       True
Temporary Root:         False
No Reboot:              False
Wipe:                   False
```

**Comment by ko3st** [comment]
@badabing2005  Thanks for explaining what I did. I think it might be worth sharing, especially to people with an unlocked bootloader, who do not have root yet. Perhaps they would be willing to fully root their device, but they might be hesitating, because they do not want to loose their installed software. Here I have showed a way to not wipe my phone and gain root access! 

So when I wrote...
_I used Flash Mode: Full OTA

Flash Options:
Flash to Inactive slot
Disable Verity
Disable Verification
Verbose_

... that reflected on the last part of your reaction.

_Created a patch and flashed the OTA with the following option

Flash Mode:             OTA

Custom Flash Options:   True
Disable Verity:         True
Disable Verification:   True
Verbose Fastboot:       True_

**Comment by badabing2005** [comment]
This is incorrect.
For starters in the help menu, there's at least 3 links to well writted guides, and people are strongly encouraged to read them and follow them.

Second, unlocking a bootloader is a requirement to rooting, and unlocking (or even locking) means automatic wipe, and there's no two ways about it.

Third, by the default, a device has both verity and verfication enabled, and anytime you transition from enabled verification to disabled verification, you absolutely need to perform a wipe (not the for the reverse direction) and if you don't you won't be able to boot to system, and the wipe is not automatic unlike for the unlocking of the bootloader.

**Comment by ko3st** [comment]
@badabing2005 Where did I say I never wiped my phone? Because obviously I needed to do that to get an unlocked device.  (Actually I did that only a few hours after opening the box of the brand new pixel 8 pro).

To obtain an unlocked bootloader there is no way to get past that, and I am sorry if I made you think something along that line. 

I am talking about the situation of having a (pixel 8 pro) phone _with_ an unlocked bootloader, which is not been fully rooted yet. 

Some (a lot of?) people are hesitating to fully root their device, because, **as I understand it,** that would normally require you to be prepared to 'wipe' your, already unlocked phone, for a second time...

So although you are right, I specifically wrote this part:
_....people with an unlocked bootloader, who do not have root yet._

... and I used that part in this full sentence:

> I think it might be worth sharing, especially to people with an unlocked bootloader, who do not have root yet. Perhaps they would be willing to fully root their device, but they might be hesitating, because they do not want to loose their installed software.

I do not wat to be a smartass or anything, but my question to you is this:

Do you agree that it is worth sharing, or is it nothing special to gain root access without 'wiping' it for a _second_ time and losing all your installed software in that process?

**Comment by badabing2005** [comment]
There is absolutely no requirement of wiping a device on a already unlocked device if all you want to achieve is to root the device.
I don't know why you want any of that added.
Like I previously said, that is a false premise.
I also clearly indicated under which conditions a wipe is necessitated, which by the way is well captured in the linked guides.

**Comment by ko3st** [comment]
I am so sorry to waste your time, but then l did not understand the remark from Hipkat, when he replied : "You can't keep data", in the full textual context below.

Please see: https://xdaforums.com/conversations/almost-ready-to-click-the-button-in-newest-pixelflasher.15401655/reply?quote=16073031


To double check here and now with you:
I clicked this radio button:
Keep Data

I selected ONLY these four(!) checkboxes:

Flash to Inactive slot
Disable Verity
Disable Verification
Verbose

[@HipKat](https://xdaforums.com/m/3615140/) do you "agree" it looks good to go?
If yes, I will click the button "FLash Pixel Phone" :)
Click to collapse

You can't keep data if you're checking disable veruty and verification but you MUST check those if you use a custom kernel or ROM with a kernel baked in

**Comment by badabing2005** [comment]
Hipkat's statements are correct.
If you disable verification, then you need to wipe, hence why he's saying
> You can't keep data if you're checking disable veruty and verification

He is also correct when he says, 
> but you MUST check those if you use a custom kernel or ROM with a kernel baked in

you would need to check that, if you're flashing custom kernel / ROM that requires it (which would imply a wipe)

**Comment by ko3st** [comment]
Please let me explain...
I will probably never raise to the same level of knowledge of you, but being a novice, I guess I am not the only one with basically _too little knowledge_  to fully understand the processes involved in rooting my phone. Hence I am following (or trying to follow) the appropriate guide, which had lead to brick my previous p8p.

After buying a completely brand new one again, I reached out to Hipkat and I explained to him I was afraid of bricking the brand new p8p also. 

It was Hipkat who was patient with me, and suggested to rather not follow the guide to the letter, but use PixelFlasher. It would be less complicated then following the steps....

Then I was almost ready to push the button...

I think I have extracted info from otherwise right info from Hipkat, but due to lack of knowledge, I took it out of context. 

I simply do not understand enough about it (yet). The confusion emerged when I wrote:
_I clicked this radio button:
Keep Data_

... and I mistook only these words of Hipkat:

_You can't keep data_

Do you understand / see where my confusion is coming from? 

(I hope you see I mean no harm but that you understand I am not ignorant also).
