### ISSUE TITLE
After stuck in fastboot for about 30 minutes, now cannot found magisk (but is present)

### ISSUE THREAD

**Issue by SalvatoreNoschese** [badabing2005/PixelFlasher#169]
Stuck apps cause stuck in bootloader (or viceversa?)
Start smartphone by powerbutton and kill app

Smartphone still work as expected (but not updated) and seems not recognized by pixelflasher

So, i can't flag "flash to inactive slot" and if i try to flash i receive this warning

Magisk seems to be ok.
![Screenshot_20240307-013650](https://github.com/badabing2005/PixelFlasher/assets/16841896/fcc5af27-87a7-4e4b-b963-d57a9f75dcb2)

Tried anyway to flash, i receive this:
`Android Platform Tools Version: 34.0.5-10900879

2024-03-07 01:39:30 Getting device: *** state  ...
Currently the device is in ERROR mode.

2024-03-07 01:39:31 Getting device:  *** state  ...
Rebooting device: *** to bootloader ...
Updating connected devices ...

2024-03-07 01:39:32 ERROR: Unable to detect the device.
Aborting ...

2024-03-07 01:39:32 INFO: Flashing was aborted.
This could be user initiated or a problem encountered during flashing.
You might need to manually reboot your device.

Updating connected devices ...`

Any help will be very appreciated.

**Comment by badabing2005** [comment]
support file please

**Comment by SalvatoreNoschese** [comment]
> support file please

Seems to be a permission issue. Indeed, by smartphone i don't more receive debug permission alert.

![Schermata_20240307_130600](https://github.com/badabing2005/PixelFlasher/assets/16841896/56f8df9a-3923-472f-82de-6c9c399ced28)
[support_2024-03-07_13-05-23.zip](https://github.com/badabing2005/PixelFlasher/files/14523777/support_2024-03-07_13-05-23.zip)

**Comment by SalvatoreNoschese** [comment]
Holy :hankey: 
Crashed at some step. Now just google logo here and i cannot shutdown.

`Writing 'super'                                    OKAY [  0.413s]
Finished. Total time: 197.040s
[liblp] Partition system_b will resize from 0 bytes to 946470912 bytes
[liblp] Partition system_dlkm_b will resize from 0 bytes to 348160 bytes
[liblp] Partition system_ext_b will resize from 0 bytes to 277393408 bytes
[liblp] Partition product_b will resize from 0 bytes to 3262619648 bytes
[liblp] Partition vendor_b will resize from 0 bytes to 763318272 bytes
[liblp] Partition vendor_dlkm_b will resize from 0 bytes to 45793280 bytes
[liblp] Partition system_a will resize from 0 bytes to 18255872 bytes
2024-03-07 14:47:38 Done flash script execution!
Sleeping 10 seconds ...

2024-03-07 14:47:48 Getting device: *************** state retry [4] times ...
Currently the device is in fastboot mode.
Updating connected devices ...


Selected Device on 2024-03-07 14:47:48:
    Device ID:                       ***************
    Device Model:                    cheetah
    Device Active Slot:              a
    Device Mode:                     f.b
    Has init_boot partition:         True
    Device Bootloader Version:       cloudripper-14.0-11170085
    Device Unlocked:                 True
    slot-retry-count:a:              
    slot-unbootable:a:               
    slot-successful:a:               
    slot-retry-count:b:              
    slot-unbootable:b:               
    slot-successful:b:               


2024-03-07 14:47:48 Getting device: *************** state  ...
Rebooting device: *************** to bootloader ...
Fastboot waiting for device: *************** for bootloader ...
device: *************** is now in bootloader mode.
Updating connected devices ...


Selected Device on 2024-03-07 14:48:07:
    Device ID:                       ***************
    Device Model:                    cheetah
    Device Active Slot:              b
    Device Mode:                     f.b
    Has init_boot partition:         True
    Device Bootloader Version:       cloudripper-14.4-11290827
    Device Unlocked:                 True
    slot-retry-count:a:              
    slot-unbootable:a:               
    slot-successful:a:               
    slot-retry-count:b:              
    slot-unbootable:b:               
    slot-successful:b:               

Checking if the bootloader is unlocked ...
Bootloader is unlocked, continuing ...
Flashing patched init_boot ...

2024-03-07 14:48:08 Getting device: *************** state  ...
Rebooting device: *************** to system ...
ADB waiting for device: *************** for device ...

2024-03-07 14:49:38 ERROR: Command "/opt/android-sdk/platform-tools/adb" -s *************** wait-for-device timed out after 90 seconds

2024-03-07 14:49:38 Getting device: *************** state  ...
Device is now in ERROR mode.
Sleeping 10 seconds ...
Updating connected devices ...
Flashing elapsed time: 380 seconds
------------------------------------------------------------------------------


==============================================================================
 2024-03-07 14:50:36 User initiated Scan
==============================================================================

2024-03-07 14:50:36 Scanning for Devices ...
No Devices found.

==============================================================================
 2024-03-07 14:51:22 User initiated Scan
==============================================================================

2024-03-07 14:51:22 Scanning for Devices ...
No Devices found.`

**Comment by badabing2005** [comment]
I need to see support files, this is not a support file
And you shouldn't need to launch as root.

The last message from your previous logs I see this
`no permissions; see [http://developer.android.com/tools/device.html]`

Unless that issue is addressed, things won't work.

Did you follow the steps in the link?

**Comment by SalvatoreNoschese** [comment]
Hi. I put here a support reply file.
https://github.com/badabing2005/PixelFlasher/issues/169#issuecomment-1983379190

Anyway, tried all useful way (also Google website and fastboot).
Usually flash as expected, but still hang on logo.
Tried also to reflash in both slot init_boot and firmware, but still stuck on logo.
After about 2hrs and 3 different firmware, I full reset via fastboot with -w flash-all.sh and now start again.
Idk the reason. First time I need to reset.

Anyway, now work.

**Comment by badabing2005** [comment]
> Hi. I put here a support reply file.
> https://github.com/badabing2005/PixelFlasher/issues/169#issuecomment-1983379190

That support file is old, after providing that support file you performed more actions and ran into a problem, how do expect me to guess what happened by looking at an older support file?

**Comment by SalvatoreNoschese** [comment]
Sorry, but with bricked device not simple to follow reply.
A long day today.

Anyway, I think is caused by arch setup (no udev rules, then require root to work).
Pixel flasher try, but fail cause of this (via terminal is more simple to see there is issue with permission).

Thank and sorry for time.
I really appreciate your job and pixel flasher ☺️👍

**Comment by badabing2005** [comment]
Are you truly bricked or just bootlooping?

You can still generate a support file.
Just connect your device, run PF, and generate a support file, no need to do anything else.

**Comment by SalvatoreNoschese** [comment]
Also flash factory from fastboot, seems ok but stuck on colored animated logo (eternally, also shutdown require long press power button). Tried to change slot, to reflash default init boot. Just this in any way.
I recovered d via fastboot with -w flag (not a giant problem thanks to Google one and swifthbackup).
