### ISSUE TITLE
Is it possible to add a backup menu ?

### ISSUE THREAD

**Issue by ItzPeaxel** [badabing2005/PixelFlasher#17]
Due to a lack of custom recovery software on Oriole & Raven, is it possible to add an ADB / fastboot menu for backup and restore option like TWRP ? 

I don't even know if this is possible, I'm just asking

**Comment by badabing2005** [comment]
If there are any ways to do a nandroid backup with adb / fastboot, I would add support for it.
To my knowledge there is none.
