### ISSUE TITLE
icons too large in toolbar

### ISSUE THREAD

**Issue by DjinnDjab** [badabing2005/PixelFlasher#170]
cant read the status messages windows because the icons up top are ridiculously large and i use a larger font on my display so i can see, unable to manually resize any part of the window

**Comment by DjinnDjab** [comment]
using ubuntu appimage

**Comment by badabing2005** [comment]
You can hide the icons, anything in the toolbar can be done from the menu
You can also move the toolbar.
See the `Toolbar` menu

**Comment by DjinnDjab** [comment]
thank you
