### ISSUE TITLE
Latest GitHub release missing macOS build

### ISSUE THREAD

**Issue by JoshAtticus** [badabing2005/PixelFlasher#171]
Title ^

**Comment by badabing2005** [comment]
You don't need to create tickets for this, I'm aware (in fact I had to make sure it was decoupled in the Github actions to get the others deployed), and it will be available whenever I manage to get around Apple sh*t.
This is a broken record with Apple, chaos theory in action.

**Comment by JoshAtticus** [comment]
> You don't need to create tickets for this, I'm aware (in fact I had to make sure it was decoupled in the Github actions to get the others deployed), and it will be available whenever I manage to get around Apple sh*t. This is a broken record with Apple, chaos theory in action.

Oh, sorry, my bad

**Comment by badabing2005** [comment]
I managed to build .app and not .dmg on MacOS 11 and MacOS 13
See if it works.
https://github.com/badabing2005/PixelFlasher/releases/download/v6.8.2.1/PixelFlasher.app_mac13.zip
https://github.com/badabing2005/PixelFlasher/releases/download/v6.8.2.1/PixelFlasher.app_mac11.zip

**Comment by teiffs** [comment]
@badabing2005 

Intel Mac (Ventura 13.6.4) gives same error on both...
![image](https://github.com/badabing2005/PixelFlasher/assets/65736720/804a7488-17d3-441c-9fc6-6993e403bc96)

**Comment by badabing2005** [comment]
What architecture your Mac is?

**Comment by teiffs** [comment]
Intel Core i5?

**Comment by badabing2005** [comment]
see the latest release v6.8.3.0

**Comment by teiffs** [comment]
> see the latest release v6.8.3.0

that would do it! THANKS MUCH!
