### ISSUE TITLE
No window shows up after the loading screen

### ISSUE THREAD

**Issue by godspirit00** [badabing2005/PixelFlasher#172]
I'm using Windows 10. There is no window showing up after the loading screen. I can see in the Task Manager that it is running in the background, but there is just no window in the foreground. I tried several recent builds, but the problem persists.
The problem did not exist back in January when I used the then latest build to update my pixel 6a at that time.
What could be the problem?
Thanks!

**Comment by ShosGithub** [comment]
Just try a "ladder"

**Comment by godspirit00** [comment]
> Just try a "ladder"

Problem solved. So it'll be great to have the window show up first before trying to reach Google. @badabing2005

**Comment by badabing2005** [comment]
@god

> > Just try a "ladder"
> 
> Problem solved. So it'll be great to have the window show up first before trying to reach Google. @badabing2005

I have no idea what you're asking for?
reach Google?
You said problem solved, how?

**Comment by godspirit00** [comment]
> @god
> 
> > > Just try a "ladder"
> > 
> > 
> > Problem solved. So it'll be great to have the window show up first before trying to reach Google. @badabing2005
> 
> I have no idea what you're asking for? reach Google? You said problem solved, how?

Sorry for the wording. 

It seems that PixelFlasher tries to get information from google.com or github.com after the loading screen disappears and before the main window shows up. As google.com and github.com are not directly accessible in some regions, PixelFlasher will hang in the background while no window shows up. 

My solution, or workaround, is to set a proxy in the Internet setting of the system, so that PixelFlasher can reach google.com or github.com via the proxy, and get the info it needs and so the main window can show up.

So, it'd be great to have the main window show up before trying to reach google.com or github.com.

**Comment by badabing2005** [comment]
Thanks for the clarification.

Already done, should be released soon.
See [here](https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/post-89392202)

**Comment by badabing2005** [comment]
Should be fixed in v6.8.3.0
