### ISSUE TITLE
I think the executable bit may have been lost in the "_mac11" version.

### ISSUE THREAD

**Issue by vitaprimo** [badabing2005/PixelFlasher#173]
I downloaded it and accidentally clicked it in Firefox in the list instead of clicking the little magnifying glass, it extracted it so fast it didn't even show a progress bar, I don't know what it invoked to extract it; from `./Contents` (and down) only, without the parent folder that makes the app.

With Keka, I unzipped it to `PixelFlasher.app_mac11`, removed `_mac11`, and I thought I was good to go but it refused to open. `./Contents/MacOS/PixelFlasher` wouldn't run either. GateKeeper is the first thing I get rid off on "new*" macOS systems, and it seems like this might be signed, IDK.

I went to the terminal and tried to launch the binary from there but it wouldn't ⇥complete and *there* was the reason. I confirmed it was not executable with `ls`. I don't know if it was because of Keka, but for what it's worth, the one extracted by Firefox was `644` too.

It might be a false alarm but I thought it wouldn't hurt to give you heads up just in case, and it's also an excuse to thank you for sharing your work, there's no way I'd use an Android device without rooting it and I'm not going back to iOS, this app and specially all the links included are very helpful to achieve that, thanks! <3 :)

*: It's Mojave, sometimes I reinstall High Sierra, so not so new.

**Comment by badabing2005** [comment]
Can you please try the `.app` from [here](https://github.com/badabing2005/PixelFlasher/actions/runs/8242488430)?
See if that works.
Before trying the `.dmg`

Thanks
