### ISSUE TITLE
Lost root while flashing OTA

### ISSUE THREAD

**Issue by xChAmeLIoNz** [badabing2005/PixelFlasher#177]
As title says, I successfully flashed the March OTA update for my Pixel 7, following the provided guide in the readme... but after that root was lost. I'm also unable to flash the patched init_boot.img alone if I try to install magisk separately.

OS: Ubuntu 22.04
Platform Tools: Latest v35
Device: Pixel 7 (panther)

I'm attaching the sanitized dumps. Thanks for the support.

[support_2024-03-20_23-42-51.zip](https://github.com/badabing2005/PixelFlasher/files/14673792/support_2024-03-20_23-42-51.zip)

**Comment by xChAmeLIoNz** [comment]
Found the solution. Turns out I'm an idiot.

When the device was prompting to enter fastboot, I was pressing `start` instead of selecting `restart bootloader` with the arrow keys.

At least we all learn from our mistakes. Hope this can help someone.

**Comment by badabing2005** [comment]
Reboot to bootloader should not wait for input unless you're using Pixel Watch2, which in this case you're not.
I see the erro
`2024-03-20 23:15:17 ERROR: Encountered an error while rebooting to bootloader`

Are you saying that each time your phone is rebooted to bootloader, you get a prompt?

**Comment by xChAmeLIoNz** [comment]
Every time I reboot the device, I get the `The bootloader is unlocked and software integrity cannot be guaranteed` message (see image 1). 
Every time I need to reboot to bootloader, I get prompted to either `start` the device and boot it normally, `restart bootloader` to boot to bootloader and few others. (see image 2)
Note that on my second successful attempt to flash the OTA, the phone also rebooted to recovery mode, but I did not touch it and proceeded to reboot itself to the OS.

P.S: The provided images are meant as a reference and are not from my device. I do not get `device state: error!`

@badabing2005 

Image 1:

![image](https://github.com/badabing2005/PixelFlasher/assets/95928045/6a08bc0e-3659-424d-bf1f-43bb00f8b0d1)

Image 2:

![image](https://github.com/badabing2005/PixelFlasher/assets/95928045/f090cf58-43b9-4037-b44c-4383c9a8c451)

**Comment by badabing2005** [comment]
It sounds to me that when you're seeing start you're pressing it, which reboots the phone to system.
You're not supposed to touch anything when PF is controlling and updating your phone, unless PF prompts you to take any specific action on your phone, you should leave the phone alone and it will work.

**Comment by xChAmeLIoNz** [comment]
> It sounds to me that when you're seeing start you're pressing it, which reboots the phone to system. You're not supposed to touch anything when PF is controlling and updating your phone, unless PF prompts you to take any specific action on your phone, you should leave the phone alone and it will work.

If I don't press anything, the boot process just doesn't happen.

**Comment by badabing2005** [comment]
If you're seeing the second screen, and not seeing Device state: Error!
Then the device is in bootloader mode.
If it is not detected by PF or the command `fastboot devices` then make sure you have the latest Google's USB drivers installed (link in Help menu) in both adb and bootloader modes.
Also make sure you're using reliable cable / port.
