### ISSUE TITLE
Boot loop P6P

### ISSUE THREAD

**Issue by spookymyo** [badabing2005/PixelFlasher#18]
I just tried to flash and patch the 12.1.0 (SQ3A.220705.003.A3, Jul 2022, Verizon update for my Pixel 6 Pro. I was skeptical because I've never been able to get any automatic programs to work, even the android flash utility doesn't work. I read everything carefully and gave Pixel Flasher a shot. I selected the correct boot image and patched it. It returned a message saying Magisk wasn't found on the phone, which it was, and for me to select it manually. I did so. Then I flashed it and it got almost all the way done and the phone got stuck on the fastbootd page. Then i got a couple of errors and the phone reset and started bootlooping. I had to sideload the stock OTA to get it working again. Then I did the usual manual patch and flash the magisk modified boot image to regain root. That works without issue.

I copied and pasted the console info:

PixelFlasher 3.4.0.0 started on 2022-08-04 15:59:36
{
    "advanced_options": true,
    "boot_id": null,
    "custom_codepage": "",
    "custom_rom": false,
    "custom_rom_path": null,
    "device": "24061FDEE000LT",
    "disable_verification": false,
    "disable_verity": false,
    "fastboot_verbose": false,
    "firmware_path": "C:\\Eric\\Phone Stuff\\Pixel 6 Pro\\Pixel Flasher\\raven-sq3a.220705.003.a1-factory-152f6a65.zip",
    "flash_both_slots": false,
    "force_codepage": false,
    "height": 985,
    "magisk": "com.topjohnwu.magisk",
    "mode": "keepData",
    "phone_path": "/storage/emulated/0/Download",
    "platform_tools_path": "C:\\Eric\\Phone Stuff\\platform-tools_r33.0.2-windows\\platform-tools",
    "pos_x": 57,
    "pos_y": 20,
    "selected_boot_md5": null,
    "update_check": true,
    "verbose": false,
    "version": "3.4.0.0",
    "width": 1664
}
System Default Encoding: utf-8
File System Encoding:    utf-8
Active code page: 437

2022-08-04 15:59:36 Selected Platform Tools Path:
C:\Eric\Phone Stuff\platform-tools_r33.0.2-windows\platform-tools.
SDK Version: 33.0.2-8557947

Please select a boot.img!

Loading Device list ...
This could take a while, please be patient.

Selected Device on 2022-08-04 15:59:38:
    Device ID:          24061FDEE000LT
    Device Model:       raven
    Device is Rooted:   False
    Device Build:       SQ3A.220705.003.A3
    Device Active Slot: b
    Device Mode:        adb

Load time: 3 seconds

Selected Boot: 178e1b56cd736be045602a9d96fa67dc from image: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a1-factory-152f6a65.zip
Deleting boot record,  ID:1  Boot_ID:178e1b56 ...
Cleared db entry for: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a1-factory-152f6a65.zip
Deleting Firmware cache for: C:\Users\spook\AppData\Roaming\PixelFlasher\factory_images\raven-sq3a.220705.003.a1 ...
Deleting Boot file: C:\Users\spook\AppData\Roaming\PixelFlasher\boot_images\178e1b56cd736be045602a9d96fa67dc\boot.img ...

Please Process the firmware!

2022-08-04 16:01:39 Reloading Device List ...

Selected Device on 2022-08-04 16:01:39:
    Device ID:          24061FDEE000LT
    Device Model:       raven
    Device is Rooted:   False
    Device Build:       SQ3A.220705.003.A3
    Device Active Slot: b
    Device Mode:        adb

Please Process the firmware!
2022-08-04 16:04:48 The following firmware is selected:
raven-sq3a.220705.003.a3-factory-5651ee94.zip

Please Process the firmware!

2022-08-04 16:04:52 Processing firmware file ...
7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
Scanning the drive for archives:
1 file, 2441060467 bytes (2328 MiB)
Extracting archive: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip
--
Path = C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip
Type = zip
Physical Size = 2441060467
Everything is Ok
Folders: 1
Files: 6
Size:       2459009024
Compressed: 2441060467
Package ID: 1
Boot ID: 1
Package_Boot ID: 1

Please select a boot.img!
Process firmware time: 6 seconds

Please select a boot.img!

Please select a boot.img!

Please select a boot.img!

2022-08-04 16:05:16 Processing firmware file ...
7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
Scanning the drive for archives:
1 file, 2441060467 bytes (2328 MiB)
Extracting archive: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip
--
Path = C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip
Type = zip
Physical Size = 2441060467
Everything is Ok
Folders: 1
Files: 6
Size:       2459009024
Compressed: 2441060467
Package ID: 1
Boot ID: 1
Package_Boot ID: 1

Please select a boot.img!
Process firmware time: 6 seconds

Selected Boot: ef050a14cf06b9d9ba121e2ac85b9eb6 from image: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip

Selected Boot: ef050a14cf06b9d9ba121e2ac85b9eb6 from image: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip

Selected Boot: ef050a14cf06b9d9ba121e2ac85b9eb6 from image: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip

==============================================================================
 2022-08-04 16:08:57 PixelFlasher 3.4.0.0              Patching boot.img 
==============================================================================
Deleting boot.img from phone in /storage/emulated/0/Download ...
Making sure boot.img is not on the phone in /storage/emulated/0/Download ...
Deleting magisk_patched.img from phone in /storage/emulated/0/Download ...
Making sure magisk_patched.img is not on the phone in /storage/emulated/0/Download ...
Transfering boot.img to the phone in /storage/emulated/0/Download ...
C:\Users\spook\AppData\Roaming\PixelFlasher\boot_images\ef050a14cf06b9d9ba121e2ac85b9eb6\boot.img: 1 file pushed, 0 skipped. 122.5 MB/s (67108864 bytes in 0.523s)

Making sure boot.img is found on the phone in /storage/emulated/0/Download ...
Magisk Tools not found on the phone
Looking for Magisk app ...
Unable to find magisk on the phone, perhaps it is hidden?
User pressed ok.

Looking for magisk_patched.img in /storage/emulated/0/Download ...
Found /storage/emulated/0/Download/magisk_patched-25201_dZ1g3.img
Pulling /storage/emulated/0/Download/magisk_patched-25201_dZ1g3.img from the phone ...
md5 of magisk_patched.img: 8f4fbe6d347e34d5df25ecdda3046ad7
Boot ID: 2
Package_Boot ID: 2

Please select a boot.img!
Patch time: 59 seconds

Selected Boot: 8f4fbe6d347e34d5df25ecdda3046ad7 from image: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip
Android SDK Version:    33.0.2-8557947
Device:                 24061FDEE000LT raven SQ3A.220705.003.A3
Factory Image:          C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip

Boot image:             8f4fbe6d / ef050a14 
                        From: C:\Eric\Phone Stuff\Pixel 6 Pro\Pixel Flasher\raven-sq3a.220705.003.a3-factory-5651ee94.zip
                        [Patched] with Magisk  on raven

Flash Mode:             keepData

Note: Pressing OK button will invoke a script that will utilize
fastboot commands, this could possibly take a long time and PixelFlasher
will appear frozen. PLEASE BE PATIENT. 
In case it takes excessively long, it could possibly be due to improper or
bad fasboot drivers.
In such cases, killing the fastboot process will resume to normalcy.

      Do you want to continue to flash with the above options?
              Press OK to continue or CANCEL to abort.

2022-08-04 16:10:23 User Pressed Ok.

==============================================================================
 2022-08-04 16:10:23 PixelFlasher 3.4.0.0              Flashing Phone    
==============================================================================
Rebooting device 24061FDEE000LT to bootloader ...
Waiting 10 seconds ...

Selected Device on 2022-08-04 16:10:40:
    Device ID:          24061FDEE000LT
    Device Model:       raven
    Device is Rooted:   None
    Device Build:       
    Device Active Slot: b
    Device Mode:        f.b
    Device Unlocked:    True

2022-08-04 16:10:40 Flashing device 24061FDEE000LT ...
C:\Users\spook\AppData\Roaming\PixelFlasher\factory_images\raven-sq3a.220705.003.a3>chcp 437
Active code page: 437
Sending 'bootloader_b' (11506 KB)                  OKAY [  0.424s]
Writing 'bootloader_b'                             (bootloader) Flashing pack version slider-1.2-8318357
(bootloader) flashing platform gs101
(bootloader) Validating partition ufs
(bootloader) Validating partition ufs
(bootloader) Validating partition partition:0
(bootloader) Validating partition partition:1
(bootloader) Validating partition partition:2
(bootloader) Validating partition partition:3
(bootloader) Validating partition bl1_b
(bootloader) Validating partition pbl_b
(bootloader) Validating partition bl2_b
(bootloader) Validating partition abl_b
(bootloader) Validating partition bl31_b
(bootloader) Validating partition tzsw_b
(bootloader) Validating partition gsa_b
(bootloader) Validating partition ldfw_b
(bootloader) Flashing partition ufs
(bootloader) Flashing partition ufs
(bootloader) Flashing partition partition:0
(bootloader) Flashing partition partition:1
(bootloader) Flashing partition partition:2
(bootloader) Flashing partition partition:3
(bootloader) Flashing partition bl1_b
(bootloader) Flashing partition pbl_b
(bootloader) Flashing partition bl2_b
(bootloader) Flashing partition abl_b
(bootloader) Flashing partition bl31_b
(bootloader) Flashing partition tzsw_b
(bootloader) Flashing partition gsa_b
(bootloader) Flashing partition ldfw_b
(bootloader) Loading sideload ufsfwupdate
OKAY [  2.732s]
Finished. Total time: 3.156s
Rebooting into bootloader                          OKAY [  0.000s]
Finished. Total time: 0.000s
< waiting for 24061FDEE000LT >
Sending 'radio_b' (81940 KB)                       OKAY [  2.737s]
Writing 'radio_b'                                  (bootloader) Flashing pack version g5123b-100840-220525-M-8640371
(bootloader) Flashing partition modem_b
OKAY [  0.108s]
Finished. Total time: 2.845s
Rebooting into bootloader                          OKAY [  0.000s]
Finished. Total time: 0.000s
< waiting for 24061FDEE000LT >
--------------------------------------------
Bootloader Version...: slider-1.2-8318357
Baseband Version.....: g5123b-100840-220525-B-8640371
Serial Number........: 24061FDEE000LT
--------------------------------------------
extracting android-info.txt (0 MB) to RAM...
Checking 'product'                                 OKAY [  0.000s]
Checking 'version-bootloader'                      OKAY [  0.000s]
Checking 'version-baseband'                        OKAY [  0.000s]
Setting current slot to 'b'                        OKAY [  0.090s]
extracting boot.img (64 MB) to disk... took 0.324s
archive does not contain 'boot.sig'
Sending 'boot_b' (65536 KB)                        OKAY [  2.175s]
Writing 'boot_b'                                   OKAY [  0.079s]
archive does not contain 'init_boot.img'
extracting dtbo.img (16 MB) to disk... took 0.031s
archive does not contain 'dtbo.sig'
Sending 'dtbo_b' (16384 KB)                        OKAY [  0.597s]
Writing 'dtbo_b'                                   OKAY [  0.016s]
archive does not contain 'dt.img'
archive does not contain 'pvmfw.img'
archive does not contain 'recovery.img'
extracting vbmeta.img (0 MB) to disk... took 0.000s
archive does not contain 'vbmeta.sig'
Sending 'vbmeta_b' (8 KB)                          OKAY [  0.000s]
Writing 'vbmeta_b'                                 OKAY [  0.000s]
extracting vbmeta_system.img (0 MB) to disk... took 0.000s
archive does not contain 'vbmeta_system.sig'
Sending 'vbmeta_system_b' (4 KB)                   OKAY [  0.000s]
Writing 'vbmeta_system_b'                          OKAY [  0.000s]
extracting vbmeta_vendor.img (0 MB) to disk... took 0.000s
archive does not contain 'vbmeta_vendor.sig'
Sending 'vbmeta_vendor_b' (4 KB)                   OKAY [  0.000s]
Writing 'vbmeta_vendor_b'                          OKAY [  0.011s]
extracting vendor_boot.img (64 MB) to disk... took 0.282s
archive does not contain 'vendor_boot.sig'
Sending 'vendor_boot_b' (65536 KB)                 OKAY [  2.308s]
Writing 'vendor_boot_b'                            OKAY [  0.079s]
archive does not contain 'vendor_kernel_boot.img'
extracting super_empty.img (0 MB) to disk... took 0.000s
Rebooting into fastboot                            OKAY [  0.000s]
< waiting for 24061FDEE000LT >
Sending 'super' (4 KB)                             OKAY [  0.005s]
Updating super partition                           OKAY [  0.012s]
Resizing 'product_b'                               OKAY [  0.006s]
Resizing 'system_b'                                OKAY [  0.010s]
Resizing 'system_ext_b'                            OKAY [  0.000s]
Resizing 'system_a'                                OKAY [  0.005s]
Resizing 'vendor_b'                                OKAY [  0.000s]
Resizing 'vendor_dlkm_b'                           OKAY [  0.011s]
Resizing 'vendor_a'                                OKAY [  0.000s]
archive does not contain 'boot_other.img'
archive does not contain 'odm.img'
archive does not contain 'odm_dlkm.img'
extracting product.img (2691 MB) to disk... took 17.962s
archive does not contain 'product.sig'
Resizing 'product_b'                               OKAY [  0.000s]
Sending sparse 'product_b' 1/11 (262140 KB)        OKAY [  9.265s]
Writing 'product_b'                                OKAY [  0.723s]
Sending sparse 'product_b' 2/11 (262140 KB)        OKAY [  9.469s]
Writing 'product_b'                                OKAY [  0.738s]
Sending sparse 'product_b' 3/11 (262140 KB)        OKAY [  9.405s]
Writing 'product_b'                                OKAY [  0.723s]
Sending sparse 'product_b' 4/11 (262140 KB)        OKAY [  9.517s]
Writing 'product_b'                                OKAY [  0.769s]
Sending sparse 'product_b' 5/11 (262140 KB)        OKAY [  7.144s]
Writing 'product_b'                                OKAY [  0.785s]
Sending sparse 'product_b' 6/11 (262140 KB)        OKAY [  5.902s]
Writing 'product_b'                                OKAY [  0.737s]
Sending sparse 'product_b' 7/11 (262140 KB)        OKAY [  5.902s]
Writing 'product_b'                                OKAY [  0.737s]
Sending sparse 'product_b' 8/11 (262140 KB)        OKAY [  6.891s]
Writing 'product_b'                                OKAY [  0.801s]
Sending sparse 'product_b' 9/11 (262140 KB)        FAILED (Error reading sparse file)
fastboot: error: Command failed
rebooting to bootloader ...
Rebooting into bootloader                          FAILED (Status read failed (Too many links))
fastboot: error: Command failed
Sleeping 5-10 seconds ...
flashing pf_boot ...
< waiting for 24061FDEE000LT >
Sending 'boot_b' (65536 KB)                        OKAY [  2.261s]
Writing 'boot_b'                                   OKAY [  0.079s]
Finished. Total time: 2.340s
rebooting to system ...
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.000s
2022-08-04 16:14:30 Done!
Flashing elapsed time: 247 seconds

**Comment by badabing2005** [comment]
Sorry for your troubles.
Take a look at the last part of the logs you pasted.
```
Writing 'product_b' OKAY [ 0.801s]
Sending sparse 'product_b' 9/11 (262140 KB) FAILED (Error reading sparse file)
fastboot: error: Command failed
rebooting to bootloader ...
Rebooting into bootloader FAILED (Status read failed (Too many links))
fastboot: error: Command failed
Sleeping 5-10 seconds ...
flashing pf_boot ...
< waiting for 24061FDEE000LT >
Sending 'boot_b' (65536 KB) OKAY [ 2.261s]
Writing 'boot_b' OKAY [ 0.079s]
Finished. Total time: 2.340s
rebooting to system ...
Rebooting OKAY [ 0.000s]
Finished. Total time: 0.000s
2022-08-04 16:14:30 Done!
Flashing elapsed time: 247 seconds
```

Sending product_b part 9 out of 11 failed, and then fastboot failed.
Not only product image writing was not completed, what follows it is writing of system and vendor / vendor_dlkm after which the patched boot.img would be written, none of that happened because of the failure.

I suspect bad connection, check the cables, try with a different cable, try a different USB port, I would also uninstall the fastboot drivers and reinstall them just to be on the safe side.
Which would also explain why you would have issues with Android flash utility.

As for Magisk not being detected.
Check point number two of the basic usage, You need to grant root permissions to shell for it to be detected and used automatically.

In the future if you want to submit logs, there is an easier way, , use the help menu and generate support.zip, it redacts all the private data like your name and device ID to keep your privacy safe.

The observed issue has nothing to do with PixelFlasher, I will close this ticket now, but if you think PixelFlasher is at fault, post supporting data and I will reopen it.
You should be able to add more data even to closed tickets.
