### ISSUE TITLE
some worry with patch with kernelsu lkm

### ISSUE THREAD

**Issue by goattc** [badabing2005/PixelFlasher#181]
Creating a patch ...
_  __                    _ ____  _   _
| |/ /___ _ __ _ __   ___| / ___|| | | |
| ' // _ \ '__| '_ \ / _ \ \___ \| | | |
| . \  __/ |  | | | |  __/ |___) | |_| |
|_|\_\___|_|  |_| |_|\___|_|____/ \___/
- Preparing assets
- KMI: android13-5.10
- Unpacking boot image
- Adding KernelSU LKM
- Repacking boot image
- Output file is written to
- /data/local/tmp/pf/assets/kernelsu_patched_20240329_050255.img
- Done!
No such file or directory (os error 2)
PATCH_SHA1:
PATCH_FILENAME: kernelsu_lkm_patched_11737_4ba1a714_.img
cp: bad 'kernelsu_boot_*': No such file or directory
ERROR: Patching failed!
Cleaning up ...
Checking patch log: /data/local/tmp/pf_patch.log ...
Getting file content of /data/local/tmp/pf_patch.log on the device ...

❌ 2024-03-29 13:02:56 ERROR: Could not get file content: /data/local/tmp/pf_patch.log
Aborting ...

Aborting ...

**Comment by badabing2005** [comment]
@goattc 
Please provide a support file

**Comment by goattc** [comment]
[support_2024-04-01_13-16-02.zip](https://github.com/badabing2005/PixelFlasher/files/14819585/support_2024-04-01_13-16-02.zip)

**Comment by goattc** [comment]
[support_2024-04-01_13-20-17.zip](https://github.com/badabing2005/PixelFlasher/files/14819604/support_2024-04-01_13-20-17.zip)

**Comment by badabing2005** [comment]
@goattc Where did you get that version of yours?
The published version is still the same one that I've tested with.

**Comment by goattc** [comment]
Tg group : https://t.me/KernelSU_group

**Comment by badabing2005** [comment]
Sorry I don't use TG.
The changes are easy, but I will only add them when an official release outputs in that format.

**Comment by badabing2005** [comment]
This is fixed in PixelFlasher 6.9.1.2

**Comment by successtheman** [comment]
This issue seems to be happening again on the latest build of PixelFlasher, I had to patch the image manually to get kernelsu to install

**Comment by badabing2005** [comment]
Support file ???

**Comment by XdekHckr** [comment]
> Support file ???

Boring. 
[support_2024-07-03_22-48-47.zip](https://github.com/user-attachments/files/16090686/support_2024-07-03_22-48-47.zip)

**Comment by badabing2005** [comment]
> > Support file ???
> 
> Boring. [support_2024-07-03_22-48-47.zip](https://github.com/user-attachments/files/16090686/support_2024-07-03_22-48-47.zip) It is not even detecting that magisk app is installed (does phone need to be rooted to detect app? If not then it should work, lol) [support_2024-07-03_23-02-19.zip](https://github.com/user-attachments/files/16090766/support_2024-07-03_23-02-19.zip)

What's boring? 

You have multiple issues my friend, have you even read the guide?
It is not detecting Magisk app because you have the wrong package name set.
It is not detecting root, because you haven't granted root permission to shell
You also seem to have internet connection issues.

**Comment by XdekHckr** [comment]
1. Well if I have wrong package then you made it wrong, because it's default and magisk was installed via pixel flasher using adb.
2. I don't have root so nothing to grant
3. I have updated platform tools and restarted pc and it started to work
So I think you was not right 100%

**Comment by badabing2005** [comment]
> 1. Well if I have wrong package then you made it wrong, because it's default and magisk was installed via pixel flasher using adb.
> 
>     2. I don't have root so nothing to grant
> 
>     3. I have updated platform tools and restarted pc and it started to work
>        So I think you was not right 100%

You really have to learn how to read the guide.
If you Magisk is installed and it is not detected, you have either hidden the Magisk and not updated the package name in the settings, (PF has no way of knowing the hidden package name)
Or you have switched Magisk flavors (example kitsune to offical Magisk or vice versa or any other flavor that is available) but kept the package name set to the old.

Like I said, you have multiple issues, that was not the only one.

Glad you sorted it out.
