### ISSUE TITLE
ADB Shell not working

### ISSUE THREAD

**Issue by knutlegrand** [badabing2005/PixelFlasher#185]
When clicking on "ADB Shell", the terminal app tries to open "_/var/folders/zt/0pbp62dn5w16cr6j2p6d2kvc0000gp/T/tmpa2s03ymw.sh_" which does not exist on my Mac.
Android Platform Tools has been mentioned in "_/Users/My_User_name/Library/Android/sdk/platform-tools_ "
Other tools are working well, such as patching init_boot, flashing OTA, Device info, App manager, ...

MacBook Pro (Retina, 13-inch, Early 2015)
MacOS 12.7.4 (Monterey)
PixelFlasher 6.9.0.2

**Comment by badabing2005** [comment]
That file gets created by PF to launch Terminal and then it gets deleted.
See https://github.com/badabing2005/PixelFlasher/blob/808fca5eb56fb39dedb24c6f57232ac03bb7be28/phone.py#L3306-L3312

I can't tell you more without seeing support file.

**Comment by knutlegrand** [comment]
Here is the support file
[support_2024-04-05_11-06-28.zip](https://github.com/badabing2005/PixelFlasher/files/14882730/support_2024-04-05_11-06-28.zip)

**Comment by badabing2005** [comment]
Sorry for not mentioning earlier, enabling debug output would help greatly.
![image](https://github.com/badabing2005/PixelFlasher/assets/22603312/d4fa0a28-c57c-44b8-8259-a27fb3876b8f)

> Please note that directory /var/folders/zt/0pbp62dn5w16cr6j2p6d2kvc0000gp/T exists

That's because by the time you try to get to it, PixelFlasher would have already deleted it.
See line 3312 from the previous post.

Here's how that's working.
The program first creates a file in the temp folder, with some random name.
let's call it `test.sh` for illustration
and if we would use the same path as yours it would be:
`/var/folders/zt/0pbp62dn5w16cr6j2p6d2kvc0000gp/T/test.sh`
the contents of that file is:
```
#!/bin/bash
/Users/REDACTED/Library/Android/sdk/platform-tools/adb shell
```
Need to replace `REDACTED` with your actual user.

Then it calls that script with the following process
```
osascript -e 'tell application "Terminal" to do script "/var/folders/zt/0pbp62dn5w16cr6j2p6d2kvc0000gp/T/test.sh"
```

You can try this manually and capture the output and provide that.

Another one of interest would be the output of this command.
```
/Users/REDACTED/Library/Android/sdk/platform-tools/adb shell "su -c 'magisk --denylist ls'"
```

I'm suspecting that there is something in your environment variables that's causing an issue.
Could it be that you have another SDK in the path?

**Comment by knutlegrand** [comment]
Here is the support file (debug enabled).

[support_2024-04-05_17-51-35.zip](https://github.com/badabing2005/PixelFlasher/files/14892839/support_2024-04-05_17-51-35.zip)

I've checked the osascript command (by entering it manually in the terminal, after having created a test.sh file) -> it works :

> REDACTED ~ % osascript -e 'tell application "Terminal" to do script "/var/folders/zt/0pbp62dn5w16cr6j2p6d2kvc0000gp/T/test.sh"'
> tab 1 of window id 6268

Have also checked Magisk : no "denylist" option exists 

Here is the result of printenv command:

> REDACTED T % printenv
> __CFBundleIdentifier=com.apple.Terminal
> TMPDIR=/var/folders/zt/0pbp62dn5w16cr6j2p6d2kvc0000gp/T/
> XPC_FLAGS=0x0
> TERM=xterm-256color
> DISPLAY=/private/tmp/com.apple.launchd.IKnPmtm1Ek/org.xquartz:0
> SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.vuW5LWJzqr/Listeners
> XPC_SERVICE_NAME=0
> TERM_PROGRAM=Apple_Terminal
> TERM_PROGRAM_VERSION=445.1
> TERM_SESSION_ID=87116460-335A-4C20-8CCF-6232D5B84945
> SHELL=/bin/zsh
> HOME=/Users/REDACTED
> LOGNAME=REDACTED
> USER=REDACTED
> PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS
> SHLVL=1
> PWD=/var/folders/zt/0pbp62dn5w16cr6j2p6d2kvc0000gp/T
> OLDPWD=/Users/REDACTED
> LANG=fr_BE.UTF-8
> _=/usr/bin/printenv

**Comment by badabing2005** [comment]
Please give this build a try.
https://github.com/badabing2005/PixelFlasher/actions/runs/8580639774

**Comment by knutlegrand** [comment]
Have downloaded proposed build, but just got "Contents" directory
Have checked v 6.9.1.2 --> still not working

**Comment by badabing2005** [comment]
I can't reproduce this, so I'm going to create a build with extra logging to see if we can get more details on what's going on, I'll also add extra debug message for your other ticket at the same time.
Stay tuned, I'll let you know when it's ready.

**Comment by badabing2005** [comment]
Just to be certain, you did get a prompt like this and selected OK, right?
![image](https://github.com/badabing2005/PixelFlasher/assets/22603312/904badb3-6ad7-49b5-bbcc-0ecf178cc08a)

**Comment by knutlegrand** [comment]
I don't remember, but probably yes. But your question gave me the idea to reset Accessibility pref (by deleting some system database files) to see what happens next. It works !
Were the pref files corrupted or did I click on "Don't allow" by mistake ? Nobody knows but it fixed the problem related to ADB Shell. Thx

**Comment by badabing2005** [comment]
Thanks, glad it worked.
To be honest, It's hard to tell if it was a corruption or accidental "Don't allow"
I wonder if there was a possible way to change the "Don't allow" to "Allow" after the fact instead of resetting Accessibility.
