### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by 423428309843290** [badabing2005/PixelFlasher#186]
I would like to pay you to do a service. I'll give a brief summary and see if it's possible:
Is there any tool that embeds an apk with root permission in the boot.img file? Or if it doesn't exist, are you able to do this and I pay you for your services?

contact: grooverlost@gmail.com

**Comment by badabing2005** [comment]
Your request is vague, root permission in boot.img file?
In any case I'm not interested.

Thanks for the offer.

**Comment by 423428309843290** [comment]
Sorry if I wasn't specific and didn't go into more detail.

I would like to include a specific apk in boot.img, and only this specific
apk has root permission. When I fastboot this boot.img, the phone will not
be rooted, but only the apk that will be pre-installed in the boot.img will
have root permission.

Attached I am sending the apk in which I would like to include in the
boot.img with root permission only for this apk.

I hope I was able to explain it better. I'm willing to pay a lot to find a
professional who can help me with this.

signed_com.telegram.a1064_v2.0.40_10_13_release-protect.apk
<https://grooverlost-my.sharepoint.com/:u:/g/personal/grooverlost_grooverlost_onmicrosoft_com/EQHNtZpcS85Gh-pL97KA6jEBLayR8f4yjhzDyBhVfo-WFw?e=ZbMMRf>

Regards

Nathan Franceshini

Em qui., 4 de abr. de 2024 às 19:59, badabing2005 ***@***.***>
escreveu:
