### ISSUE TITLE
I'm not too crazy about me either

### ISSUE THREAD

**Issue by shelby691** [badabing2005/PixelFlasher#19]
I rooted my new pixel 6 with Pixel flasher, worked flawlessly. 
ran it for a few days installed various magisk modules without 
any problems. then decided to flash custom rom, RiceDroid. 
made a mistake somehow and now have bootloop. tried installing latest 
factory img, but says can;t format because of wrong format, raw
whatever that means. stupid newb mistake appreciate any help or 
corrective procedures. 
      thanks

**Comment by badabing2005** [comment]
Can you create a support.zip file and submit?
Help | Create a Sanitized support.zip file
Let's take a look at the error and see how we can recover from it.

**Comment by shelby691** [comment]
[support.zip](https://github.com/badabing2005/PixelFlasher/files/9340338/support.zip)

**Comment by badabing2005** [comment]
Uncheck `flash both slots` option and try again.

**Comment by shelby691** [comment]
Will report back with results, thank you very much

**Comment by shelby691** [comment]
Bravo!!! I appreciate you and the help you gave.😀

**Comment by badabing2005** [comment]
I assume it worked.
I would proceed to closing this issue.

Thanks
