### ISSUE TITLE
Scrcpy issue on MacOS

### ISSUE THREAD

**Issue by shailantani** [badabing2005/PixelFlasher#190]
Hi I'm trying to use the scrcpy option on macOS, but it opens the terminal and just doesnt work.
I've set the scrcpy path as well, which is "/opt/homebrew/Cellar/scrcpy/2.4/bin/scrcpy"
I've set the same path in PixelFlasher as well. But when I click on the scrcpy option, the terminal opens with this error:

I'm using the PixelFlasher 6.9.1.3 version

<img width="647" alt="Screenshot 2024-04-10 at 6 40 21 PM" src="https://github.com/badabing2005/PixelFlasher/assets/98448265/1497c96d-75e7-48bc-88c9-b66b5a9f8e43"><br><br><br>

<img width="849" alt="Screenshot 2024-04-10 at 6 41 15 PM" src="https://github.com/badabing2005/PixelFlasher/assets/98448265/05f69eea-093d-44e5-85f2-ae1b095fc1f2"><br><br><br>

<img width="573" alt="Screenshot 2024-04-10 at 6 41 47 PM" src="https://github.com/badabing2005/PixelFlasher/assets/98448265/79a750c2-cee6-487a-9883-fd05fa9d2769">

**Comment by shailantani** [comment]
Yeah, so when I click on the adb shell, terminal opens up and i think its working too. (Added screenshot)
And I confirmed that I had given Terminal access to PixelFlasher too. Anything else I could do perhaps?<br><br>
<img width="583" alt="Screenshot 2024-04-10 at 9 34 22 PM" src="https://github.com/badabing2005/PixelFlasher/assets/98448265/dd4a2882-7057-48ef-a5f6-9ef359724be4">

**Comment by badabing2005** [comment]
Could you enable debug logging and try again so the events are captured in the log, and then provide support.zip?
Hoping I could spot something in there.
@knutlegrand does scrcpy work for you?
Trying to see if this is a common MacOS issue or an isolated issue.

Thanks

**Comment by knutlegrand** [comment]
Not working (same as first post of this thread). ADB option is still working well 
Here is the support file (debug activated).
Hope this helps.
[support_2024-04-11_10-00-37.zip](https://github.com/badabing2005/PixelFlasher/files/14943152/support_2024-04-11_10-00-37.zip)

**Comment by shailantani** [comment]
Here's mine:
[support_2024-04-11_13-41-47.zip](https://github.com/badabing2005/PixelFlasher/files/14943282/support_2024-04-11_13-41-47.zip)

**Comment by badabing2005** [comment]
> Not working (same as first post of this thread). ADB option is still working well Here is the support file (debug activated). Hope this helps. [support_2024-04-11_10-00-37.zip](https://github.com/badabing2005/PixelFlasher/files/14943152/support_2024-04-11_10-00-37.zip)

Thanks, I see that you set the path to:
```
Setting scrcpy path path to: /usr/local/Cellar/scrcpy/2.4_1/bin
```

PF attempted to run
```
Launching scrcpy for device: REDACTED ...
debug: "/usr/local/Cellar/scrcpy/2.4_1/bin" -s REDACTED
```
Which would not work as that is not the full path to scrcpy, it needs to include the scrcpy executable.

Please try setting to:
```
/usr/local/Cellar/scrcpy/2.4_1/bin/scrcpy
```
And test again
If it still fails, can you try this command from terminal?
```
/usr/local/Cellar/scrcpy/2.4_1/bin/scrcpy" -s REDACTED
```
Replace `REDACTED` with your device id.

@shailantani 
Yours is setup correctly.
PixelFlasher tried to launch
```
"/opt/homebrew/Cellar/scrcpy/2.4/bin/scrcpy" -s 10.10.30.54:5555
```

Can you please try that from terminal and see if it works?

Sorry, not having a Mac impedes my ability to provide quicker resolution and have to rely on your feedback.
Hackintosh has its limitations.


Thanks

**Comment by knutlegrand** [comment]
> Please try setting to:
> 
> /usr/local/Cellar/scrcpy/2.4_1/bin/scrcpy

--> Done, scrcpy option works now

**Comment by badabing2005** [comment]
Thanks @knutlegrand 

@shailantani I'll wait for your feedback, we know the feature works, something must be different on yours.

**Comment by shailantani** [comment]
Hi sorry for the delay, so running the command on terminal works
`"/opt/homebrew/Cellar/scrcpy/2.4/bin/scrcpy" -s 10.10.30.54:5555`
But again, through pixel flasher it doesnt for some reason. 
Anything I can do to help you further debug it?

**Comment by badabing2005** [comment]
PixelFlasher first dynamically creats a script in system temp directory with the following content.
let's call it temp.sh for this exacmple
```
/opt/homebrew/Cellar/scrcpy/2.4/bin/scrcpy" -s 10.10.30.54:5555
```
This is based on the defined path of scrcpy and the connected / selected device.

Then it launches the following command:
For this example, I'm assuming that you create the temp.sh in your home directory
```
osascript -e tell application "Terminal" to do script "~temp.sh"
```

Can you create the temp.sh and launch and type the osascript command in terminal and see if it works for you please?

Thanks

**Comment by shailantani** [comment]
Hi so I added a temp.sh file and ran the code. Heres the errors:
<img width="243" alt="Screenshot 2024-04-12 at 10 22 33 AM" src="https://github.com/badabing2005/PixelFlasher/assets/98448265/5bd85e9a-a00a-47b8-96c3-a69f5b64b864">
Above is the temp.sh file

And then heres what I had inputted in the terminal:
<img width="903" alt="Screenshot 2024-04-12 at 10 21 50 AM" src="https://github.com/badabing2005/PixelFlasher/assets/98448265/42457e54-c03c-424d-9c11-cdfd011b7969">


So the first command was connecting the adb device and it was connected.
Second command was the one that you had asked me to input, which popped up an error.
In the third command, I tried specifying the location of the temp.sh too, but that too popped up an error.

Am I doing something wrong?
Thanks!

**Comment by badabing2005** [comment]
try
```
chmod 755 ~/temp.sh
```
see if this works
```
~/.temp.sh
```
and then this
```
osascript -e tell application "Terminal" to do script "~temp.sh"
```

**Comment by shailantani** [comment]
Okay so, I did the `chmod 755 ~/temp.sh` and it woked.
Then I tried the `~/.temp.sh` and the scrcpy worked, the the phone screen was shown.
But upon trying `osascript -e tell application "Terminal" to do script "~temp.sh"` an error popped up. Heres the screenshot:
What can I do now? <br> <br>
<img width="582" alt="Screenshot 2024-04-13 at 10 35 36 AM" src="https://github.com/badabing2005/PixelFlasher/assets/98448265/2e523ab7-acfd-4b7f-bf61-da883f2e4d26">




Thanks!

**Comment by shailantani** [comment]
OHHHH Interesting, So I searched a bit more about the error and there has to be a change in the code:

It should be:

`osascript -e 'tell application "Terminal" to do script "/Users/shailantani/temp.sh "'`
instead of: 

`osascript -e tell application "Terminal" to do script "~temp.sh"`

So there were 2 changes I made: 
1) Adding quotes before 'tell' and after 'temp.sh'
2) Properly specifying the location of temp.sh ie `"/Users/shailantani/temp.sh "` instead of `~temp.sh`

Please do check it out once, Thanks. And let me know if further information is required!

**Comment by badabing2005** [comment]
> OHHHH Interesting, So I searched a bit more about the error and there has to be a change in the code:
> 
> It should be:
> 
> `osascript -e 'tell application "Terminal" to do script "/Users/shailantani/temp.sh "'` instead of:
> 
> `osascript -e tell application "Terminal" to do script "~temp.sh"`
> 
> So there were 2 changes I made:
> 
>     1. Adding quotes before 'tell' and after 'temp.sh'
> 
>     2. Properly specifying the location of temp.sh ie `"/Users/shailantani/temp.sh "` instead of `~temp.sh`
> 
> 
> Please do check it out once, Thanks. And let me know if further information is required! @badabing2005

Thanks for the investigation.
I'll make the necessary changes, although it is surprising that it doesn't work for scrcpy but works for adb shell and for @knutlegrand it works as is for both.

**Comment by badabing2005** [comment]
@shailantani 
Please give this version a try.
https://github.com/badabing2005/PixelFlasher/releases/tag/v6.9.2.0

**Comment by shailantani** [comment]
> @shailantani Please give this version a try. https://github.com/badabing2005/PixelFlasher/releases/tag/v6.9.2.0


Hi, so I just tried that version. The scrcpy works, but "adb" stopped working now 😭 
This is the error: <br><br><br> 
<img width="1077" alt="Screenshot 2024-04-15 at 2 07 42 PM" src="https://github.com/badabing2005/PixelFlasher/assets/98448265/97bf4dfb-7db1-4405-bc93-edf81de24579">

Heres the support file:
[support_2024-04-15_14-08-32.zip](https://github.com/badabing2005/PixelFlasher/files/14976294/support_2024-04-15_14-08-32.zip)

**Comment by badabing2005** [comment]
I'm fed up with Apple shenanigans.
See [here ](https://github.com/badabing2005/PixelFlasher/blob/fe34916e7521d50c1e950c6d40c1d46f01db49c2/phone.py#L3337) and [here](https://github.com/badabing2005/PixelFlasher/blob/fe34916e7521d50c1e950c6d40c1d46f01db49c2/phone.py#L3383)

Identical code, one to launch the adb shell the other to launch scrcpy.
And now adb shell doesn't want to work with single quotes around tell?

I'm not touching this until I hear from @knutlegrand or others if this is common issue for all.
I might revert to the previous way if the older version works for all others but not you.
I'm sorry but I'd like to keep things consistent and determininstic.

**Comment by badabing2005** [comment]
Please try this version.
I reverted the way ADB Shell is launched.
https://github.com/badabing2005/PixelFlasher/actions/runs/8692363043

**Comment by knutlegrand** [comment]
Both options are working on the same PF version ! Good job

**Comment by shailantani** [comment]
> Please try this version. I reverted the way ADB Shell is launched. https://github.com/badabing2005/PixelFlasher/actions/runs/8692363043

Hi I'm sorry but could you tell me how I can run the app from the actions?
When I download the PixelFlasher.app, it gets downloaded as zip. Do I extract it then and run it?

Sorry for the doubt :")

**Comment by badabing2005** [comment]
@shailantani 
I'm not a Mac user, but I think you just remove the .zip extension and drag it to your applications folder.

**Comment by knutlegrand** [comment]
You

> @shailantani I'm not a Mac user, but I think you just remove the .zip extension and drag it to your applications folder.

No, You have to unzip it, then you get "Contents" folder. Within this folder, navigate to folder MacOS.
There, you'll find PixelFlaxer file.

In terminal, enter following commands:

- cd path_to_unzipped_Contents_folder/MacOS
- chmod +x PixelFlasher (making it executable)
- mv PixelFlasher file to [path_to_PixelFlasher.app]/Contents/MacOS folder  file (PixelFlasher.app is normally located in Applications folder)

**Comment by shailantani** [comment]
> Please try this version. I reverted the way ADB Shell is launched. https://github.com/badabing2005/PixelFlasher/actions/runs/8692363043

@badabing2005
Finally this version seems to be working with both adb and scrcpy 😄 
Amazing job!!

@knutlegrand Thanks a lot for all the help btw!

**Comment by roryokane** [comment]
> > Please try this version. I reverted the way ADB Shell is launched.
> > https://github.com/badabing2005/PixelFlasher/actions/runs/8692363043
>
> Hi I'm sorry but could you tell me how I can run the app from the actions?
> When I download the PixelFlasher.app, it gets downloaded as zip. Do I extract it then and run it?

For future reference, here is my method for testing **PixelFlasher.app.zip** files downloaded from GitHub Actions on macOS. This method should make testing a little more accurate than @knutlegrand’s method. To help anyone unfamiliar with Terminal, I wrote the steps in more detail, too.

1. Open “PixelFlasher.app.zip”. This will unarchive it, creating a “Contents” folder as a sibling.
2. In Finder, navigate inside `Contents/MacOS/` so you can see the `PixelFlasher` file.
3. Open Terminal (in `/Applications/Utilities/`). Type `chmod +x ` (with the ending space), then drag and drop the `PixelFlasher` file onto the Terminal window. Press Return to run the command. (This gives `PixelFlasher` executable permissions.)
4. In Finder, navigate back up (for example, hit ⌘↑ twice) until you can see the “Contents” folder next to the zip file. Copy the text “PixelFlasher.app” to make the next step easier.
   - To copy this, I find it convenient to select the “PixelFlasher.app.zip” file in Finder, hit Return to select the basename “PixelFlasher.app”, then Copy (⌘C).
6. Select the “Contents” folder and use menu item File > New Folder with “Contents” (⌃⌘N) to wrap it in an enclosing folder. When Finder prompts you to rename “New Folder With Items”, paste “PixelFlasher.app” as the name.

This produces a new copy of the PixelFlasher app completely derived from the zip file. While testing, you can run this app where it is – you don’t need to overwrite your existing `/Applications/PixelFlasher.app`.
