### ISSUE TITLE
failed to process firmware

### ISSUE THREAD

**Issue by seriousfreedom** [badabing2005/PixelFlasher#192]
PixelFlasher failed to process factory image for android 15 beta but processes ota image just fine
[support_2024-04-14_20-26-11.zip](https://github.com/badabing2005/PixelFlasher/files/14972960/support_2024-04-14_20-26-11.zip)

**Comment by badabing2005** [comment]
Please see https://github.com/badabing2005/PixelFlasher/releases/tag/v6.9.2.1
