### ISSUE TITLE
Stuck on "Loading configuration File ..."

### ISSUE THREAD

**Issue by aoxhwjfoavdlhsvfpzha** [badabing2005/PixelFlasher#193]
Can't get the application to run on Debian 12, it gets stuck "Loading configuration File ..."

I've tried a few different releases including the current one.

I have used it before, so I'm not sure what's changed

Not sure if there's a verbose mode or some way to debug that step

Thanks for your help!

**Comment by badabing2005** [comment]
Have you tried launching the app with `--console` ?

**Comment by aoxhwjfoavdlhsvfpzha** [comment]
I have, the behavior does not change, and no new information is offered.

I ended up just going to Windows, but if you've got any more ideas I can give them a try

**Comment by badabing2005** [comment]
Just curious, is the Linux connected to internet?
One thing you could try.
Kill All process that are: PixelFlasher, adb, fastboot
Rename the file: `~/.local/share/PixelFlasher/PixelFlasher.json` to something else, (don't delete)
Launch PixelFlasher and see if it works.
If it does, please pass me the json file that you renamed.

**Comment by aoxhwjfoavdlhsvfpzha** [comment]
I am connected to the internet, but that folder doesn't contain a JSON file, can I generate it somehow?

**Comment by badabing2005** [comment]
Please download the file again, double check the checksum to make sure it matches what's published.
Make it executable, and then launch from terminal with `--console`
You should get that file generated and something output on console, even if the application fails to start.

**Comment by aoxhwjfoavdlhsvfpzha** [comment]
Redownloaded, sum checks okay, run with `--console`, but same error, I get:

`global_args.config: None
config_file_path: /home/username/.local/share/PixelFlasher/PixelFlasher.json
Loading configuration File ...`

and it hangs there indefinitely with no extra output

There is still no json file in that folder

**Comment by aoxhwjfoavdlhsvfpzha** [comment]
My apologies, it appears it was just taking a fair bit longer than I expected/remembered, it's just opened successfully

Sorry again, and thanks for your help!

**Comment by badabing2005** [comment]
No worries, happy to hear that it's none issue.
