### ISSUE TITLE
KernelSU LKM Patching fails

### ISSUE THREAD

**Issue by Pogogo007** [badabing2005/PixelFlasher#194]
2024-04-17 18:58:54 PixelFlasher 6.9.2.5              Patching KernelSU_LKM boot

Patching on hardware: panther
Deleting /storage/emulated/0/Download/init_boot_69002059.img from the device ...
Return Code: 0
Making sure file is not on the phone ...
Checking for /storage/emulated/0/Download/init_boot_69002059.img on the device ...
File: /storage/emulated/0/Download/init_boot_69002059.img is not found on the device.
Deleting /storage/emulated/0/Download/kernelsu_lkm_patched*.img from the device ...
Return Code: 0
Making sure file is not on the phone ...
Checking for /storage/emulated/0/Download/kernelsu_lkm_patched*.img on the device ...
File: /storage/emulated/0/Download/kernelsu_lkm_patched*.img is not found on the device.
Pushing local file: C:\Users\franc\AppData\Roaming\PixelFlasher\boot_images4\69002059b5ad9333df30b515d0d143f66db32429\init_boot.img to the device: /storage/emulated/0/Download/init_boot_69002059.img ...
Return Code: 0
Checking for /storage/emulated/0/Download/init_boot_69002059.img on the device ...
File: /storage/emulated/0/Download/init_boot_69002059.img is found on the device.
Checking to see if KernelSU app is installed ...
Getting package me.weishu.kernelsu path on the device ...
Package Path is: /data/app/~~8CBmUsnIm2EiS9NgBh4lHg==/me.weishu.kernelsu-pZxAT_1en2ZvTRbMBn-ndA==/base.apk
Getting package me.weishu.kernelsu path on the device ...
Package Path is: /data/app/~~8CBmUsnIm2EiS9NgBh4lHg==/me.weishu.kernelsu-pZxAT_1en2ZvTRbMBn-ndA==/base.apk

❌ 2024-04-17 18:58:55 ERROR: Encountered an error while patching KernselSU LKM
Traceback (most recent call last):
  File "Main.py", line 4313, in _on_kernelsu_lkm_patch_boot
  File "modules.py", line 2907, in patch_boot_img
  File "modules.py", line 2097, in patch_kernelsu_lkm_script
UnboundLocalError: cannot access local variable 'kmi_override' where it is not associated with a value

I get this error every time i attempt to patch my Pixel7 firmware with kernelsu lkm on windows and linux alike

**Comment by badabing2005** [comment]
OK thanks for reporting, I see the issue.
I'll have it fixed soon.
In the meantime, you can check what KMI PF is reporting when you scan and select your device.
And enter that value in Preferences | Override KMI
That should get you going.
A silly unintialized variable oversight.
![image](https://github.com/badabing2005/PixelFlasher/assets/22603312/26babfb1-747d-4fd5-b70d-e2caf1962c1b)
