### ISSUE TITLE
Hidden Magisk imploded

### ISSUE THREAD

**Issue by arass** [badabing2005/PixelFlasher#195]
Not sure if this is probably an issue for Magisk, but if you could fix it - awesome.

Told Magisk to hide itself. It did - made a nice separate icon. 
Then Magisk told me there's an update. Which fails wo error. Killed the separate icon's ability to bring up a UI. Only allows "update" (which immediately fails). 
That was fine as root itself was working ok. Then phone force-accepted some OTA patch, which broke root.
Got back to PC, used PF to flash newest patch and install Magisk again. 
Magisk works great, passes safetynet, but no more UI. PF is able to update modules (yay!).
Regular UI says I don't have Magisk installed. 
The Settings icon is still there, but only says I can update magisk app (and fails).

Any guidance or a patch that fixes UI would be awesome, but existing workaround (updating modules through PF) is acceptable.

**Comment by badabing2005** [comment]
This is a known Magisk issue.
It doesn't like multiple copies of Magisk.
This could happen during an upgrade where originally Magisk is hidden, and the Magisk update fails to properly unhide Magisk, and ends up installing Magisk App.
The solution to this is use an app like [TB Checker](https://play.google.com/store/apps/details?id=krypton.tbsafetychecker)
Run it and find all instances of Magisk, it will tell you the package names.
Uninstall all of them, and reboot
Install Magisk version matching what you rooted with, if Magisk does not prompt you automatically.

Nothing can be done in PixelFlasher to automatically fix this.
