### ISSUE TITLE
Windows 10 - Pixel 7 - AttributeError: 'NoneType' object has no attribute 'reboot_bootloader'

### ISSUE THREAD

**Issue by AndrewL97** [badabing2005/PixelFlasher#196]
Hello!

Attached support zip to the bottom of this.

Details:
	- panther-ota-ap1a.240405.002.b1-e5e55cca
	- Pixel 7 (not pro, etc.)
	- Windows 10 

Essentially all I am doing is:

- Connect to device
- Use OTA image that matches the device + current version
- Process Image
- Patching the (only) result in the `Select a boot/init_boot` table, w/ latest magisk (v 27~)
	-  Magisk is installed by PixelFlasher after a prompt
- Select the new result, with the cute bandaid "Patched" symbol
- Full OTA is selected by default (other options are disabled)
- left `No reboot` unticked
- Hit Flash
- Console outputs this (Included the support output to show I did not extra fiddling afterwards :) ):
 ```
[...]
serving: 'C:\Users\Jandrew\Downloads\panther-ota-ap1a.240405.002.b1-e5e55cca.zip'  (~92%)
serving: 'C:\Users\Jandrew\Downloads\panther-ota-ap1a.240405.002.b1-e5e55cca.zip'  (~93%)
serving: 'C:\Users\Jandrew\Downloads\panther-ota-ap1a.240405.002.b1-e5e55cca.zip'  (~94%)
Total xfer: 2.00x
2024-04-23 17:35:03 Done flash script execution!
Sleeping 10 seconds ...

2024-04-23 17:35:13 Getting device: 2B241FDH200DF5 state retry [4] times ...
Currently the device is in ERROR mode.
Updating connected devices ...

❌ 2024-04-23 17:35:18 ERROR: Encountered an error while flashing
Traceback (most recent call last):
  File "Main.py", line 4363, in _on_flash
  File "modules.py", line 4363, in flash_phone
  File "modules.py", line 4254, in reboot_device_to_bootloader
AttributeError: 'NoneType' object has no attribute 'reboot_bootloader'

ℹ️ 2024-04-23 17:35:28 Creating support.zip file ...
Saved support file to: C:\Users\Jandrew\Downloads\support_2024-04-23_17-35-26.zip
 ```

The device itself is then on a bootloader looking screen, where I can reboot, etc.
Let me know if you need more info, or more debugging on my side - this is my first go at this, so I am likely just missing something obvious

[support_2024-04-23_17-35-26.zip](https://github.com/badabing2005/PixelFlasher/files/15073078/support_2024-04-23_17-35-26.zip)

Cheers!

**Comment by AndrewL97** [comment]
Should mention - it looks like this was raised before (but closed because no support zip) - #188

Had a look at the code - I found some handling for pixel watches, where they don't support automatic changing to `Reboot to bootloader`, this seems to match the screen I end up on with the pixel 7 phone.

going to just add Panther to the pixel watch list so I throw the same dialog, will report back on how that goes

**Comment by AndrewL97** [comment]
Turns out I am dumb - it helps to unlock bootloader first :) 
https://xdaforums.com/t/april-17-2024-ap1a-240405-002-b1-global-unlock-bootloader-root-pixel-8-pro-husky-safetynet.4633839/post-89077787

**Comment by badabing2005** [comment]
There's nothing wrong with the statement, it's accurate.
If all you want to flash (sideload) is stock OTA, then you don't need an unlocked bootloader.
You need unlocked bootloader if you want to flash factory image (stock or patched) because to flash factory, you would use the fastboot command which requires an unlocked bootloader.

Just to be super clear, when you're sideloading OTA, and have selected a patched boot / init_boot instead of stock one, then that step can only be performed with fastboot command hence you need to have an unlocked bootloader.
Flashing patched boot / init_boot (which is what roots your device) requires unlocked bootloader
