### ISSUE TITLE
Dev Tools keybox 

### ISSUE THREAD

**Issue by VisionR1** [badabing2005/PixelFlasher#198]
Hi, how this option work? Because I click it and open the window dialog to choose a .xml, but when choose one nothing happened.
Without any connect device via adb.
![Test keybox xml](https://github.com/badabing2005/PixelFlasher/assets/25982450/c1400d81-edbd-4507-b883-49940a571ed7)

**Comment by badabing2005** [comment]
I'm assuming that you are refering to keybox.xml validity checker.

You don't need a device to be connected.
You would see the result of the test in the console, make sure you're checking the console.

Example:
```
EC Cert SN: 6a0c9ef31f814ebb8d8301eb443f7940
RSA Cert SN: 78d6b0810af9e6897b62ef2e26a853d2

Keybox is revoked!
debug: Result: False
```

**Comment by VisionR1** [comment]
> I'm assuming that you are refering to keybox.xml validity checker.
> 
> You don't need a device to be connected. You would see the result of the test in the console, make sure you're checking the console.
> 
> Example:
> 
> ```
> EC Cert SN: 6a0c9ef31f814ebb8d8301eb443f7940
> RSA Cert SN: 78d6b0810af9e6897b62ef2e26a853d2
> 
> Keybox is revoked!
> debug: Result: False
> ```

Yeah, sorry my mistake, I mean keybox.xml
Oh now see it, need it to be full screen the program to see it.

**Comment by xxjoe2** [comment]
i am sorry but i just downloaded v7.2.0.1 (PixelFlasher_Ubuntu_20_04) but i couldnt find any check xml result outputed to the console. these are all the outputs on the console and there is no output after a xml was selected

`(PixelFlasher_Ubuntu_20_04:252960): Gtk-CRITICAL **: 19:05:40.875: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher_Ubuntu_20_04:252960): GLib-GObject-WARNING **: 19:05:40.875: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher_Ubuntu_20_04:252960): Gtk-CRITICAL **: 19:05:40.875: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher_Ubuntu_20_04:252960): GLib-GObject-WARNING **: 19:05:40.875: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher_Ubuntu_20_04:252960): Gtk-CRITICAL **: 19:05:40.875: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
`


any idea pls?
