### ISSUE TITLE
Patch KSU get "ERROR: KernelSU patching in PixelFlasher is only supported on Pixel devices"

### ISSUE THREAD

**Issue by Xerxes-2** [badabing2005/PixelFlasher#199]
Phone: Pixel 7 Pro Global
Version: AP1A.240505.005
OS: macOS 14.4.1

After process the firmware, tried to patch the init_boot with ksu_lkm but get "ERROR: KernelSU patching in PixelFlasher is only supported on Pixel devices"

**Comment by badabing2005** [comment]
Please provide support file please.

**Comment by Xerxes-2** [comment]
> Please provide support file please.
[support_2024-05-08_21-04-07.zip](https://github.com/badabing2005/PixelFlasher/files/15247918/support_2024-05-08_21-04-07.zip)

**Comment by badabing2005** [comment]
You're running PixelFlasher 6.8.1.0
The issue is addressed in follow up release, please try running the [latest](https://github.com/badabing2005/PixelFlasher/releases/latest) and report back.
You should be fine.

**Comment by Xerxes-2** [comment]
Oh that's fixed. Sorry didn't mention that I downloaded the wrong version.
