### ISSUE TITLE
Add udev rules and plugdev group to prerequisites for Linux install

### ISSUE THREAD

**Issue by xChAmeLIoNz** [badabing2005/PixelFlasher#200]
Please add the official link to fix the `Insufficent permission for device` message when rebooting to fastboot. 
Without this, my pixel 7 wouldn't be able to boot to fastboot and it wasn't mentioned in the README.

https://developer.android.com/studio/run/device#setting-up

**Comment by badabing2005** [comment]
PixelFlasher does not install USB drivers, it is a pre-requisite, which is stated in the readme.
It is up to the user to follow the proper installation guide for their environment.
Besides even if I wanted to do that step through PixelFlasher, it requires root access to the host, not something I want to request or tackle.

PS: I added a link in the readme.

**Comment by xChAmeLIoNz** [comment]
Thank you.

Yes, I didn't mean to add the option to install/setup the udev rules within PixelFlasher. Forgot to specify to add in the README.
