### ISSUE TITLE
[Feature Request] Sign images with a custom AVB key

### ISSUE THREAD

**Issue by xeropresence** [badabing2005/PixelFlasher#201]
I'd like to be able to lock my device but still flash custom images with magisk. GrapheneOS signs their releases with a custom key that gets written to the device. There are some projects to resign images without having to build them your self. 
https://github.com/chenxiaolong/avbroot

**Comment by badabing2005** [comment]
There is a perfectly written tool that does this and you have referenced it, why would I re-invent the wheel? Use avbroot, sign the image before flashing.
