### ISSUE TITLE
New Android 15 Beta Factory Image - Nothing to extract from firmware

### ISSUE THREAD

**Issue by hector-autio** [badabing2005/PixelFlasher#203]
Downloaded the Pixel 8 Factory Image for the new beta, when loading into Pixel Flasher, and click process, it gives me a message "Nothing to extract from firmware". 

I'm attaching the support file.

[support_2024-05-21_11-53-15.zip](https://github.com/badabing2005/PixelFlasher/files/15393673/support_2024-05-21_11-53-15.zip)

**Comment by badabing2005** [comment]
This is not PixelFlasher issue, Google messed up the factory image.
If you open up the zip file, you'd see that there is a nested zip file `image-shiba_beta-ap31.240426.023.zip` which is the images that would get flashed.
Try to extract that file using any zip utility (example: 7zip)
You'd get the following Error:
```
Unexpected end of data
Data error : system_ext.img
```

Use the [OTA image](https://dl.google.com/developers/android/vic/images/ota/shiba_beta-ota-ap31.240426.023-b053b46c.zip) instead, which is actually the safer and recommended way.
