### ISSUE TITLE
No module named '_cffi_backend'

### ISSUE THREAD

**Issue by cjshearer** [badabing2005/PixelFlasher#204]
While packaging PixelFlasher for nix, I encountered a build error: `No module named '_cffi_backend'`. I fixed it by [updating the hidden imports in the .spec file](https://github.com/cjshearer/nixos-config/blob/ec6ff5ba2bdfb12773bc1f4fb9addba81751ba5d/pkgs/pixelflasher/default.nix#L32) to `hiddenimports=['_cffi_backend']`, following advice from [this PyInstaller issue comment](https://github.com/pyinstaller/pyinstaller/issues/1684#issuecomment-590288201). The application now works (I successfully performed an OTA update, Magisk patch, and updated my Pixel), but I don't understand the underlying fix.

If this a "good" fix, I'd be willing to make a PR, or feel free to take it, whichever.

**Comment by badabing2005** [comment]
Thanks for the find, and the necessary fix.
IT's an easy fix, so I can add it, and give credit to you on next release, or you can create a PR.
Either way I'm fine with, whatever you prefer.

Thanks

**Comment by cjshearer** [comment]
Sounds good! I'll throw up a PR here in a moment
