### ISSUE TITLE
Flashing custom kernel

### ISSUE THREAD

**Issue by road2react** [badabing2005/PixelFlasher#206]
Right now after flashing an update any custom kernel is reinstalled separately on the device using a kernel flasher app. Is it possible to add a custom kernel image (such as https://xdaforums.com/t/kernel-10-05-2024-android-14-0-0-stable-kirisakura_raviantah-2-2-4-for-pixel-7-pro-aka-pantah.4509795/) and flash the kernel along with the factory image?

**Comment by badabing2005** [comment]
For now I don't have any plans to add such functionality to PixelFlasher, I think @capntrips Kernel Flasher does a perfect job of it, why reinvent the wheel, besides I'd have to deal with all the different Kernels support.
I'm closing this now, but if I ever feel inclined to add support, I'll reopen it.
