### ISSUE TITLE
Windows Defender says version 6.9.8.0 contains a trojan 

### ISSUE THREAD

**Issue by lpedia-git** [badabing2005/PixelFlasher#212]
I tried to download v6.9.8.0/PixelFlasher.exe earlier today, but Windows Defender intervened, claiming it contains a trojan:

<img src="https://github.com/badabing2005/PixelFlasher/assets/78785226/9734fac4-6d2e-478c-818c-8f1a657a3ebb" width="50%" height="50%">

It's normal for Windows to object to downloading executables, saying they're potentially dangerous, but if that's just a warning one can choose to download anyway. This time it believes there's malicious code and blocks access to the file. 

A mis-identification, I hope?

**Comment by VisionR1** [comment]
Just disable for little the protect in real time and after download.

**Comment by lpedia-git** [comment]
Well, yes, of course I could do that. 

However, I wasn't asking how to get it past Windows Defender. I was pointing out the problem. Can you confirm that it's not infected and explain why it might be being identified as a trojan?

**Comment by drandrew1983** [comment]
I have the same problem, Windows defender and also NordVPN detects the file as malicious
Trojan:Win32/Sabsik.FL.A!ml
This program is dangerous and executes commands from an attacker.

**Comment by VisionR1** [comment]
Read in the front page in Readme
![PixelFlasher](https://github.com/badabing2005/PixelFlasher/assets/25982450/c2a9bf4f-3129-43b5-8447-1d58ad8d9c58)

and this: https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/post-89090938

**Comment by badabing2005** [comment]
Folks, 
This is recurring issue with every release, please read the referenced links.
I don't want to be told about this non-issue on every release.
Yeah I understand you might not have gotten this warning on a previous release, but that doesn't mean anything, it's a lottery, your AV might or might not complain about it.

**Comment by drandrew1983** [comment]
> Folks, This is recurring issue with every release, please read the referenced links. I don't want to be told about this non-issue on every release. Yeah I understand you might not have gotten this warning on a previous release, but that doesn't mean anything, it's a lottery, your AV might or might not complain about it.

Just wanted to say Sorry. we are not professional, we don't know about the technical stuff. For a person like me I feel worried to seee such warnings.
Keep up the good work, Thank you for the great tool.
