### ISSUE TITLE
[Bug] PixelFlasher crashes when clicking boot images | macOS 15 Beta

### ISSUE THREAD

**Issue by JoshAtticus** [badabing2005/PixelFlasher#213]
Version 6.9.8.0

macOS 15 Beta 2

PixelFlasher doesn't log anything to console so I can't attach logs

**Comment by badabing2005** [comment]
Does the [previous version](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.9.6.0) work?
Or is this a general problem with MacOS 15 Beta 2?

Can you run PixelFlasher with `--console` argument?
Does it output anything.

I don't have a MacOS, let alone one with 15 Beta 2, so it's going to be a challenge to fix this without input from testers.

**Comment by badabing2005** [comment]
Reading the title again, so it launches, but it crashes when you click on something?
Absolutely anything or some specific widgets?
How about menu items?

**Comment by JoshAtticus** [comment]
> Reading the title again, so it launches, but it crashes when you click on something? Absolutely anything or some specific widgets? How about menu items?

Clicking anything is correct, anywhere on the window that can normally be clicked

**Comment by JoshAtticus** [comment]
> Does the [previous version](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.9.6.0) work?

No

> Or is this a general problem with MacOS 15 Beta 2?

Not sure, didn't test on Beta 1. Works on latest Sonoma (14)

> Can you run PixelFlasher with `--console` argument? Does it output anything.

Sure, here's the error
```
PixelFlasher info_image: error: argument --image: can't open '/Users/josh/Library/Application Support/PixelFlasher/boot_images4/3b14ba68ebacc15e86bea283d644c2739b5c8f9b/magisk_patched_27000_3b14ba68_8154bb57.img': [Errno 2] No such file or directory: '/Users/josh/Library/Application Support/PixelFlasher/boot_images4/3b14ba68ebacc15e86bea283d644c2739b5c8f9b/magisk_patched_27000_3b14ba68_8154bb57.img'
```

**Comment by JoshAtticus** [comment]
Here's a screen recording


https://github.com/badabing2005/PixelFlasher/assets/72828296/595541f8-a502-46ac-95a8-b114479e7279

**Comment by JoshAtticus** [comment]
Found a solution!

Go to your home folder in finder, press Cmd + Shift + . to show hidden files and folders, open Library > Application Support > Pixel Flasher, move everything in there to bin, empty bin, then relaunch PixelFlasher. This will reset everything related to PixelFlasher.

**Comment by badabing2005** [comment]
Thanks for troubleshooting.

It looks like the fact that you're clicking on a non-existent boot image, it's crashing at the point it's trying to get avb boot info.
I'm not sure why, as there is [try / catch exception handling](https://github.com/badabing2005/PixelFlasher/blob/f0d0e67ee4bcb86184a456df4b9bf6997141db11/Main.py#L3949C1-L4098C34) even though there is no explict check for the file existence at that part of the code.

I'll add file presence check in any case.

Clearing the PF directory, reset everything and resolved the issue.
Thanks
