### ISSUE TITLE
PixelFlasher won't start on a rolling release Linux distro (python-protobuf related? / TypeError?)

### ISSUE THREAD

**Issue by upbox-org** [badabing2005/PixelFlasher#215]
Hi, I just tried to start PixelFlasher on my EndeavourOS Linux installation after a long time, and it won't start anymore.
I get the following terminal output while trying to start it:

```
❯ PixelFlasher
Traceback (most recent call last):
  File "/usr/bin/PixelFlasher", line 3, in <module>
    import Main
  File "/opt/pixelflasher/Main.py", line 34, in <module>
    from advanced_settings import AdvancedSettings
  File "/opt/pixelflasher/advanced_settings.py", line 6, in <module>
    from runtime import *
  File "/opt/pixelflasher/runtime.py", line 49, in <module>
    from payload_dumper import extract_payload
  File "/opt/pixelflasher/payload_dumper.py", line 14, in <module>
    import update_metadata_pb2 as um
  File "/opt/pixelflasher/update_metadata_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/lib/python3.12/site-packages/google/protobuf/descriptor.py", line 920, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```
So is some of your code out of date (TypeError), like the interpreter comment say?

BTW: I use the latest build of the following AUR package:
https://aur.archlinux.org/packages/pixelflasher

Best regards

**Comment by badabing2005** [comment]
Can you provide some context?
What version of EndeavourOS? (links?)
Is this the first time you're using PixelFlasher and on first run this is happening?
Or did it start happening recently and that it was working fine before that? If so, what brought it to this point?

**Comment by badabing2005** [comment]
Closing the issue, 
I setup the latest endeavouros in a VM and was able to run PixelFlasher without issues.
Without further relevant feedback, I'll keep this issue closed as none issue.

**Comment by cjshearer** [comment]
We get this [building in NixOS on the latest nixpkgs](https://github.com/NixOS/nixpkgs/pull/336191#issuecomment-2411837097). I was able to use the `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` workaround, but I figured you may want to know.
