### ISSUE TITLE
Platform tools not found when installed, arch linux

### ISSUE THREAD

**Issue by Spunkie** [badabing2005/PixelFlasher#217]
I'm on arch linux and I have `aur/pixelflasher-bin` installed as well as `extra/android-tools` but when I start up PixelFlasher it complains about platform tools not being found.
___
If I point it to `/bin` it errors out with this:
```
ℹ️ 2024-07-03 19:48:23 Selected Platform Tools Path:
/bin

❌ 2024-07-03 19:48:23 ERROR: /bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_trim_arg_from_keyseq


❌ 2024-07-03 19:48:23 ERROR: Android Platform Tools version is not available or is too old.
                           For your protection, disabling device selection.
                           Please select valid Android SDK.

SDK Version:      None
Adb SHA256:       f2a196bfd7ccb0ffffd317d31cdcb6113cfaa3b6528e7ec048e06861302c968a
Fastboot SHA256:  5be2fa9046744177cb114702a54618bd5088ea1290149203841d22bd656851c8
```
___
If I download the latest linux zip from https://developer.android.com/tools/releases/platform-tools and extract that to a folder, then point PixelFlasher to that dir it errors out in the same way:
```
ℹ️ 2024-07-03 19:51:30 Selected Platform Tools Path:
/home/spunkie/Downloads/platform-tools

❌ 2024-07-03 19:51:30 ERROR: /bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_trim_arg_from_keyseq


❌ 2024-07-03 19:51:30 ERROR: Android Platform Tools version is not available or is too old.
                           For your protection, disabling device selection.
                           Please select valid Android SDK.

SDK Version:      None
Adb SHA256:       19baa53be4ea6365b21341df3becab9046ba25692757fc934e2c95f0e8078883
Fastboot SHA256:  81dcaa554b5ad6b8354bb7ac16826782b11ba0faadb5601b242cd7c0780ae591

```
___
What am I missing or doing wrong?

**Comment by badabing2005** [comment]
#111 or https://github.com/badabing2005/PixelFlasher/issues?q=rl_trim_arg_from_keyseq

**Comment by sawdoctor** [comment]
The issue is still there if you use the pixelflasher bin from the AUR, it's impossible to select any version on platform tools.

If you use the none bin version and "build it" instead then that version work's fine. If you check the comments in the AUR i did report it to the maintainer but he's not removed bin version
