### ISSUE TITLE
Windows Defender detects Trojan:Win32/Wacatac.B!ml in 7.0.0.0 PixelFlasher.exe

### ISSUE THREAD

**Issue by The-MAZZTer** [badabing2005/PixelFlasher#219]
This occurs as part of the functionality to scan all downloaded files (as opposed to a manual disk scan). A manual scan of the file reports it is clean. VirusTotal says it's clean as well so this is likely a false positive. But, it is preventing download.

**Comment by badabing2005** [comment]
Common issue with lazy AV tools.
Happens on every release.
