### ISSUE TITLE
device info.

### ISSUE THREAD

**Issue by moduledd** [badabing2005/PixelFlasher#220]
application doesnt get device info. tried on 2 devices (oreo 8.1 and 13). application v
[PixelFlasher_2024-07-08_09h41m08s.log](https://github.com/user-attachments/files/16123186/PixelFlasher_2024-07-08_09h41m08s.log)
ersion 7.0.0.0

**Comment by badabing2005** [comment]
Please read the usage guide.
The application is able to get the device info.
And here it is (from your logs)
```
=======================================
Selected Device on 2024-07-08 09:41:09:
=======================================
    Device ID:                       REDACTED
    Device Model:                    qcom
    Device Active Slot:              
    Device Mode:                     adb
    Has init_boot partition:         False
    Device Bootloader Version:       unknown
    Device is Rooted:                False
    Device Build:                    OPM1.171019.026
    Device API Level:                27
    Android Version:                 8.1
    Android Name:                    Android Oreo
    Android Codename:                Oatmeal Cookie
    Android Release Date:            December 5, 2017
    Android Latest Update:           October 2021
    Device Architecture:             arm64-v8a
    Device Kernel:                   Linux localhost 3.18.71-perf-g310b3ba #1 SMP PREEMPT Fri Dec 14 21:47:11 EST 2018 aarch64
    Device Kernel Version:           
    Device KMI:                      
    oem_unlock_supported:            
    sys_oem_unlock_allowed:          1
    ro.boot.flash.locked:            1
    ro.boot.vbmeta.device_state:     
    ro.product.first_api_level:      27
    ro.boot.veritymode:              enforcing
    ro.boot.verifiedbootstate:       
    ro.secure:                       1
    ro.zygote:                       zygote64_32
    ro.vendor.product.cpu.abilist:   
    ro.vendor.product.cpu.abilist32: 
    Magisk Manager Version:          :
        Checked for Package:         com.topjohnwu.magisk
    KernelSU App Version:            :
    APatch App Version:              :
```

**Comment by moduledd** [comment]
window that showed device info didnt appear tho. appeared once and never seen again

**Comment by badabing2005** [comment]
> window that showed device info didnt appear tho. appeared once and never seen again

Again from the log file you provided.
```
Device Info:
------------
[DEVICE_PROVISIONED]: [1]
[af.fast_track_multiplier]: [1]
[audio.deep_buffer.media]: [true]
[audio.offload.min.duration.secs]: [30]
[audio.offload.video]: [true]
[av.debug.disable.pers.cache]: [1]
[ckt.internal.version]: [WHALE01A-S00A_CKT_L99EN_V136_181214210834]
...
```

**Comment by moduledd** [comment]
and? i know its in the log im saying bout that stupid window

**Comment by badabing2005** [comment]
And?
You want to me guess? I don't have a crystal ball, what you provided doesn't show anything, besides you're supposed to provide support.zip.
![image](https://github.com/badabing2005/PixelFlasher/assets/22603312/d725c812-3cc2-4158-9702-b2505ebe4b3d)

**Comment by moduledd** [comment]
[support_2024-07-09_19-32-42.zip](https://github.com/user-attachments/files/16145574/support_2024-07-09_19-32-42.zip)
ok, here is the support archive

**Comment by badabing2005** [comment]
What is the output of:
`C:\vedroid_adb_fastboot\adb.exe devices`

Needless to say, you need to run this when PF is not detecting your device (assuming that your device is properly connected to your PC, with a good cable to a working USB port and Google's USB drivers are installed)

And please next time you test in PF, enable debug.
