### ISSUE TITLE
Husky Beta 4.1 file format not supported

### ISSUE THREAD

**Issue by Birraque** [badabing2005/PixelFlasher#226]
The latest husky_beta-ap31.240617.010-factory-b9695ae9.zip beta rom file format isn't supported in PixelFlasher (PixelFlasher_Win_2019) v7.2.0.1
How can we handle it?

![PixelFlasher_v7 2 0 1](https://github.com/user-attachments/assets/b30a75a4-66ac-4b73-aece-d40d1d60cbe3)

**Comment by badabing2005** [comment]
Can you provide a support file please.

**Comment by Birraque** [comment]
My bad badabing... I noticed that I haven't enough disk space when processing the rom.
Please close this report and thanks for your prompt response.
