### ISSUE TITLE
Windows Defender throwing a Win32:Puasson warning for PixelFlasher.exe

### ISSUE THREAD

**Issue by Razzemmatazz** [badabing2005/PixelFlasher#227]
![win32puasson-pixelflasher](https://github.com/user-attachments/assets/cd39cc50-a53b-4b7b-bc17-1edc8671f63a)

Not sure why, but I'm getting a Potentially Unwanted Software warning for PixelFlasher.exe against the launcher exe for v7.1.1.1.

**Comment by badabing2005** [comment]
https://github.com/badabing2005/PixelFlasher#troubleshooting
> If your anti-virus program is telling you that PixelFlasher is a malware, or you are concerned in any way, please check [this post](https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/post-89090938) about false positives.

And many such duplicate tickets in here. (#57 ...)
