### ISSUE TITLE
Tool Bar not showing all buttons when advanced options are enabled.

### ISSUE THREAD

**Issue by The-Unforgiven-One** [badabing2005/PixelFlasher#228]
Not a huge issue however with the latest update version 7.3.1.0 when I enable advanced options the tool bar pushes the settings and support radio buttons completely off the screen and part of the unlock button as well.

![image](https://github.com/user-attachments/assets/fc9630c7-ffe4-42c2-8c3e-3627ce4cad54)

**Comment by The-Unforgiven-One** [comment]
Thank you for replying. I am using a 17 inch laptop so I suppose that is kind of small compared to the 27 inch monitors I use when I have access to my PC.  I understand moving the tool bar to any of the 4 sides of the screen. Is it possible to resize the tool bar by grabbing the end or the separators and dragging them I have tried and have not had any success and am wondering if there something I am missing or its not possible.

**Comment by badabing2005** [comment]
Sorry, I will not be investing time on making the toolbar resizable.
I'm not even sure it is possible with the framework I use.
Hand coding UI with WxPython is not something I enjoy, I rather spend the time on more productive features.
You can hide the tools you don't use to make the toolbar smaller.

**Comment by The-Unforgiven-One** [comment]
I was just uncertain if it was already possible based on the wording of the option to move the toolbar. Thank you for clarifying it for me.
