### ISSUE TITLE
Microsoft Defender Antivirus Flagging Release v7.3.1.2

### ISSUE THREAD

**Issue by suddenlydoomy** [badabing2005/PixelFlasher#230]
Hi there.  When I attempt to download release v7.3.1.2, Microsoft Defender Antivirus blocks the download.  This is the message it provides:

![image](https://github.com/user-attachments/assets/ab84959a-aceb-4e7c-b249-a306f4535272)

**Comment by badabing2005** [comment]
It's a recurring theme, mentioned in the readme and discussed ad nauseam in many threads @ XDA Forums and there are many Github issues of the same.
I'm getting sick of reading the same thing with every release.

There is nothing I can do about it.

**Comment by suddenlydoomy** [comment]
I'm really sorry.  I wasn't trying to annoy you.  I really do appreciate PixelFlasher and your work.  This is the first release where I've encountered this issue.

**Comment by badabing2005** [comment]
Don't take it personally,
Everyone experiences it on some release which ends up being their first.

With these lazy AV companies, there is no guarantee when you would get the false positive.
