### ISSUE TITLE
Possibility to build an RPM package?

### ISSUE THREAD

**Issue by lxwulf** [badabing2005/PixelFlasher#231]
I would like to run this on my fedora system, which is obviously RPM-based. 
When we are already at this point, I would also be happy to help to create and provide the rpm package if I can.

😊✌

**Comment by badabing2005** [comment]
It's a single executable, does it really require an rpm package?
Feel free to create it, but all it takes is download the binary and run it, no installer or anything.

**Comment by lxwulf** [comment]
@badabing2005 sorry, totally missed that! 🤦‍♂️

Thank you for pushing me back to earth! 🤝

We can close this as....`close` or
