### ISSUE TITLE
Bug: UI Toolbar size/location is wrong after Device Scan / selecting device

### ISSUE THREAD

**Issue by dethknite** [badabing2005/PixelFlasher#232]
I have the toolbar setting (on the Right Side of window).
Press Scan for device, then select the device, and the toolbar window fills the majority of screen.
If I change the window size (cause and invalidate/refresh) it goes back to normal.
![PixelFlasher_v7 3 2 0_4ZyBHpYAek](https://github.com/user-attachments/assets/0a807b35-1e36-43d7-8fe6-f3ae6df9db15)

**Comment by badabing2005** [comment]
I can't reproduce the issue.
Can you please enable debug (I see you have it already), reprodce the issue and then create support.zip file.

I'll probably won't be able to look at it in the next while, so no rush to submit.
