### ISSUE TITLE
[FEATURE REQUEST] Add automatic APatch (KernelSU) Patching

### ISSUE THREAD

**Issue by antiLegion** [badabing2005/PixelFlasher#233]
APatch seems to be the latest root manager that works really well.
I've been using it successfully.

It would be fantastic if there was a way to auto patch the kernel with APatch, similar to the Magisk auto patching feature.
APatch is here: https://github.com/bmax121/APatch

And for anyone that reads this, here is a list of super useful modules to include if you choose APatch.
Play Integrity Fix
https://github.com/chiteroman/PlayIntegrityFix

ZygiskNext
https://github.com/Dr-TSNG/ZygiskNext

Zygisk Assistant
https://github.com/snake-4/Zygisk-Assistant

Cherish Peekaboo (hides root in APatch)
https://xdaforums.com/attachments/cherish_peekaboo_1-4-2-zip.6128965/

Bootloader Spoofer
https://github.com/chiteroman/BootloaderSpoofer

YouTube Revanced Extended
https://github.com/j-hc/revanced-magisk-module

Systemless hosts (for adguard)
https://github.com/symbuzzer/systemless-hosts-KernelSU-module

------------

References:
https://xdaforums.com/t/dev-apatch-an-alternative-root-solution-to-kernelsu-and-magisk.4655727/

**Comment by sawdoctor** [comment]
Not sure what you are actually asking for but Pixelflasher will patch the boot.img with any Magisk version, Apatch or KSU. I flashed the August A14 ota and PF automatically patched the boot.img with Apatch, all I had to do was select Apatch as by root/patch method. PF downloaded apatch APK to the phone and patched and then I rebooted into a rooted phone

**Comment by antiLegion** [comment]
Uhhhh.... OK, ignore me. I'm a doof.
Feature Request fulfilled!
