### ISSUE TITLE
Error when using "Export List" within Package Manager

### ISSUE THREAD

**Issue by profucius** [badabing2005/PixelFlasher#235]
I am trying to export the list of 3rd party apps from my pixel device using PixelFlasher. I open the Package Manager, and have already gotten all application names. I also hide system apps.

When I click Export List button at the button, it prompts to save a file, and then it seems to save it successfully. However the file is 0 kb and contains no data.

The PixelFlasher Console shows this error:

`2024-08-10 17:10:55 User Pressed Export List`
`Traceback (most recent call last):`
`  File "package_manager.py", line 760, in OnExportList`
`  File "encodings\cp1252.py", line 19, in encode`
`UnicodeEncodeError: 'charmap' codec can't encode characters in position 6960-6962: character maps to <undefined>`

Is there anything I can do to bypass this? Or perhaps if it is a specific app with some invalid character name, can I bypass/exclude it? I don't even mind uninstalling the app if I can just find out which one it is that is causing the issue. Please advise, thanks.

**Comment by badabing2005** [comment]
Enable debug and it should possibly tell you which app is causing the encoing issue.
I'll add code to handle encoding in the next release.

**Comment by badabing2005** [comment]
Should be fixed in 7.4.0.0
