### ISSUE TITLE
Request for "TrickyStore MOD" from osm0sis support

### ISSUE THREAD

**Issue by swebow** [badabing2005/PixelFlasher#236]
Hi!

I wonder if it's possible for you to add support for pushing keybox.xml files to the modded trickystore?
https://github.com/osm0sis/TrickyStore

Not sure how easy it is to port the already added function for the previous trickystore.

**Comment by badabing2005** [comment]
This functionality is already present in PIF Manager,
Probably there is a bug causing it to hide the button.
I'll have it fixed in the next release.

**Comment by V0latyle** [comment]
Noticed the same thing here, keybox button is missing with Osm0sis TS fork.

**Comment by badabing2005** [comment]
I have a fix for it, should be in the next release.

**Comment by badabing2005** [comment]
Should be fixed in 7.4.0.0
