### ISSUE TITLE
Unable to patch boot.img with APatch

### ISSUE THREAD

**Issue by xdwsdev** [badabing2005/PixelFlasher#241]
Hey,
I wanted to patch my boot.img coming from crDroid with APatch, it was running smoothly and asked for my SuperKey etc. until the end.
Here's the support file:

[support_2024-09-01_16-54-48.zip](https://github.com/user-attachments/files/16829365/support_2024-09-01_16-54-48.zip)

Thanks!
xdws

**Comment by badabing2005** [comment]
That question should be directed to Apatch or CrDroid.
If Apatch can't patch CrDroid image, PF can't do anything about it.
I see you tried the Alternate Apatch and got a patch.

In regards to Sideloading OTA failing, see [this post](https://xdaforums.com/t/pixelflasher-for-google-pixel-9-pro-9-pro-xl-support-thread.4688252/page-6#post-89689389).

**Comment by xdwsdev** [comment]
I'll try to get info from them then.

About the Alternate APatch - it did success and got a patch but failed when flash booting, saying that it's too small or something.

**Comment by badabing2005** [comment]
Hmmm
I didn't see that in the logs.
What I saw is that you created it but never flashed it.
Maybe I missed it.

**Comment by xdwsdev** [comment]
It should be in this file, exported it while I saw the error in the console.

[support_2024-09-01_21-05-27.zip](https://github.com/user-attachments/files/16830533/support_2024-09-01_21-05-27.zip)
