### ISSUE TITLE
Check for existing files when Pixel firmware is selected

### ISSUE THREAD

**Issue by V0latyle** [badabing2005/PixelFlasher#243]
Instead of needing to re-process the file every time you select firmware for a particular device, have Pixel Flasher check to see if the firmware has already been processed to save time.

PF does appear to check for a previous patched boot image.

**Comment by badabing2005** [comment]
It already does that, for day one.
You process a firmware only once, which extracts the necessary boot / init_boot / vbmeta ...
And you also patch only once (as long was you don't want to patch differently) there is no need to create a patch again.
In fact if you load the same firmware from a different path, it even recognizes that and finds the matching processed files.
All this assuming that you don't delete the processed files.
