### ISSUE TITLE
ADB FAILED: 0 - Currently the device is in ERROR mode

### ISSUE THREAD

**Issue by keeweel** [badabing2005/PixelFlasher#245]
Hi,

Installed google drivers and tried flashing Full OTA several times. Always getting same error at 94% flashing, in phone ADB Failed :0, and then jumps into recovery. PF can't communicate after the error.

Thanks
[support_2024-09-12_00-17-33.zip](https://github.com/user-attachments/files/16970995/support_2024-09-12_00-17-33.zip)

**Comment by badabing2005** [comment]
![image](https://github.com/user-attachments/assets/59e2d529-ca2e-4b7b-b612-7c6819b38fd0)

**Comment by keeweel** [comment]
Thanks, Understood. I was confused with this. Did not realize about the last phrase in parenthesis: stock boot only. So if you patch, it is not stock, need to unlock bootloader.

![image](https://github.com/user-attachments/assets/41340489-0004-4971-b15f-7c10ab2a6b1f)

PS: Great and well developed software :)

**Comment by badabing2005** [comment]
Correct
