### ISSUE TITLE
4.1.0 Linux: abend during "Creating PACKAGE_BOOT record"

### ISSUE THREAD

**Issue by DarryDoo** [badabing2005/PixelFlasher#25]
Linux Mint XFCE 20.3. Full log attached.

```
debug: Creating PACKAGE_BOOT record, package_id: 1 boot_id: 2
Package_Boot ID: 2
Traceback (most recent call last):
  File "Main.py", line 1528, in _on_patch_boot
  File "modules.py", line 1618, in patch_boot_img
  File "modules.py", line 163, in populate_boot_list
TypeError: ListCtrl.SetItem(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'int'
  overload 2: argument 3 has unexpected type 'NoneType'

```
[PixelFlasher console log.txt](https://github.com/badabing2005/PixelFlasher/files/9701651/PixelFlasher.console.log.txt)

**Comment by badabing2005** [comment]
Thanks for reporting it,
I see what is going on, I'll have a fix shortly,
It's trying to add Magisk Version (which is the rooted version) and not finding it, because now PixelFlasher by default uses the Magisk Manager.
