### ISSUE TITLE
New Feature (Auto PIF) on PIF Manager is not visible

### ISSUE THREAD

**Issue by aprimasheva** [badabing2005/PixelFlasher#251]
This is an old issue that happened to me, since long time ago. Screenshot attached. Area marked with box in screenshot, pretty sure that Auto PIF feature is there. Long time ago, area marked with box was Play Integrity Check if i'm not wrong. Hope you fix it later, thank you :)

Device: Laptop Lenovo Ideapad Slim 3 (Ryzen 3 4300U)
OS: Windows 11 Home & Student (upgraded from Windows 10 Home & Student)

![Screenshot 2024-11-10 164332](https://github.com/user-attachments/assets/94f4c888-2e9f-4da2-9ec2-0bd0574a40f2)
Edit: I sent wrong screenshot

**Comment by badabing2005** [comment]
What is your screen resolution?

**Comment by aprimasheva** [comment]
> What is your screen resolution?

Of course Full HD (1920x1080)

**Comment by badabing2005** [comment]
Give [this one](https://github.com/badabing2005/PixelFlasher/actions/runs/11766676656/artifacts/2168491838) a try.

**Comment by aprimasheva** [comment]
> Give [this one](https://github.com/badabing2005/PixelFlasher/actions/runs/11766676656/artifacts/2168491838) a try.

Sorry for very late reply. I just try the latest release and my issue is fix. Thank you :)
