### ISSUE TITLE
Failure at flashing Nov. 2024 OTA for Pixel 7a

### ISSUE THREAD

**Issue by samueltardieu** [badabing2005/PixelFlasher#252]
[support_2024-11-10_13-31-06.zip](https://github.com/user-attachments/files/17691397/support_2024-11-10_13-31-06.zip)

 Using the latest git version to flash my unlocked magisk-rooted Pixel7a with the latest November OTA firmware gives (after ~50%):

```
Selected Device on 2024-11-10 11:04:52:
=======================================
Device ID: 32181JEH[redacted]
Device Model: lynx
Device Active Slot: b
Device Mode: f.b
Device Name: Pixel 7a
Device First API Level: 33
Device Version End Date: May 2026
Device Security Update End Date: May 2028
Has init_boot partition: True
Device Bootloader Version: lynx-15.0-11920998
Device Unlocked: True
slot-retry-count:a: 2
slot-unbootable:a: yes
slot-successful:a: yes
slot-retry-count:b: 2
slot-unbootable:b: no
slot-successful:b: yes

Getting current slot for device: 32181[…] ...
Current slot:
Comparing the current slot with the previous active slot ...

❌ 2024-11-10 11:04:52 ERROR: It appears that OTA flashing did not properly switch slots.
Aborting ...
Aborting ...
```

On the device, I see a `kInstallOpenDeviceError` that I could not capture because I don't have another one handy to take a picture.

**Comment by samueltardieu** [comment]
The device *is* unlocked and rooted, using Magisk. I've carried out many versions of the OS using PixelFlasher since I've bought it. See attached images:

![photo_5875020665835341696_y](https://github.com/user-attachments/assets/f56a9967-b5cf-45c4-af92-b4aafdb0595e)
![photo_5875048669022111515_y](https://github.com/user-attachments/assets/0d4133df-31df-48e6-93d0-5376c5d09667)

The only "unusual" thing I've done since the October update (Android 15) is enable the private space, then disable it because I didn't need it anymore, but that's it. I'll try the update again and upload a new report, in case something went wrong with it.

**Comment by samueltardieu** [comment]
And indeed, PixelFlasher prints: "==============================================================================
 2024-11-10 16:16:35 PixelFlasher 7.6.0.0              Flashing Phone    
==============================================================================
Android Platform Tools Version: 35.0.1-android-tools

2024-11-10 16:16:35 Getting device: 32181JEHN17546 state  ...
Currently the device is in adb mode.
Skipping cancelling a previous OTA update because device rooted is not detected ..."

It *is* rooted. I'll see if enabling root access from adb (instead of just applications) changes something.

**Comment by badabing2005** [comment]
Yep, root access to shell is a requirement if you want PixelFlasher to perform any root level actions.
Happy to learn that you figured it out.
Closing the issue.
