### ISSUE TITLE
Pixel Watch support

### ISSUE THREAD

**Issue by JohnLGalt** [badabing2005/PixelFlasher#253]
Hi,

Love the Pixel Flasher app. Makes my life so much easier versus having to do it all by hand in _adb_.

I'm curious, I see support for all three generations of Pixel Watches. How does this work with the PW, which has no direct wired connection (unless you have that Developer cable)?

I _think_ I can connect the PW to adb over network, but have been unsuccessful in previous attempts, before I got the PW2 and stopped playing with it. Is this what the app does?

**Comment by badabing2005** [comment]
Thanks.

I don't own PW, so I don't have first hand knowledge.
But you can check [this thread](https://xdaforums.com/t/nov-12-2024-aw2a-241105-012-global-013-france-lte-orange-pixel-watch-2-wi-fi-aurora-and-lte-eos-firmware-updates-root-dir-by-llstarks.4635402/) on XDA, I believe the USB charger / cradle is used to establish the adb connection.

As far as I know, it should be the same with PW3, but because I haven't heard back from anyone, I haven't explictly created a support page for it.

If you have PW3 and succeed, I'd appreciate if you let me know.
Thanks

**Comment by JohnLGalt** [comment]
Actually, that is the issue,

The Pixel Watch (original  model / gen 1) doesn't have pogo pins on the charger, so there is no way to connect it via a wired connection to anything - unless you have a special developer's cable from Google which attaches to a pogo pin where thee watch band connects.

The 2nd gen changed that, adding pogo pins on the back face of the watch, like FitBit devices, which also allows for a wired connection by simply plugging in the charger into a PC USB slot. Same holds true for the Pixel Watch 3.

AFAIK, PW (gen 1) has no other way to connect it via wired interface other than that special developer cable, and it is not generally available.

See:  https://support.google.com/googlepixelwatch/thread/190659456/connect-pixel-watch-to-android-studio-or-watch-face-studio?hl=en

https://developer.android.com/training/wearables/get-started/debugging

> To debug your Wear OS app on a physical watch, connect your development machine to the watch using Wi-Fi or Bluetooth. Alternatively, if your watch has a USB port, [connect using USB](https://developer.android.com/training/wearables/apps/creating#connect-watch-wired).

https://mobilesyrup.com/2023/10/17/pixel-watch-2-support-usb-data-transfer/

HTH

**Comment by JohnLGalt** [comment]
Of course, if your app can do _adb_ over Wi-Fi, (and / or BT)that would be stupendous. I can stop worrying about plugging things in lol.

Also, I neglected to mention that I have both the PW (gen 1) and the PW2, and I just used PF to flash the latest update to my PW2,, and it worked superlatively. So, if I can also use it to flash to the PW (gen 1), I'll be ecstatic! And, I'm well versed in adb CLI so if you need me to test anything to try to make PF work with gen 1 PW, let me know :)

**Comment by badabing2005** [comment]
The app can do adb over wifi, but sideloading / flashing which drops to recovery or bootloader is not accessible over wifi (I wish there was a way, I would add it to the app).

**Comment by JohnLGalt** [comment]
Yeah, that is what I thought. However, according to this link, it should still work - which I need to test. 

https://docs.zebra.com/us/en/tablets/l10-series/l10-enterprise-tablet-product-reference-guide-for-android-11/c-application-deployment/c-l10-android-system-update/t-l10-performing-a-system-update-using-wireless-adb.html

I'm gonna be sending in my Pixel 6 Pro as a trade-in for my Pixel 9 Pro XL, so I've got a test bed I can use to test doing it over Wi-Fi to see if it works before I do something that can break my PW1. I'll see if this does, indeed, work, and then see if I can force enable wireless adb on the watch specifically to try this on the watch.

I suspect they have something missing in their instructions, but a simple `adb devices` will tell me if it still sees the device over Wi-Fi after booting into recovery. Again, I don't think it will either - but I could be wrong.

BTW, just out of curiosity, is there a way to enter console commands manually at any given time when using PF (obviously not wile performing actions like flashing, but just in general)?

**Comment by badabing2005** [comment]
I tested this on Pixel 5
Steps 1 - 16 can be performed in PixelFlasher's Wifi Manager (the wifi icon next to adb devices)
Step 17, according to the reference has to be perfomed on the device, but Pixel 5 recovery is upside down Android with no possibility of Volume up Volume down interaction.
However I could reboot straight to sideload in PixelFlasher and that would put the device in sideload mode.
As I feared, at that point adb is no longer able to interact with the device.
adb devices shows the device offline :(

**Comment by JohnLGalt** [comment]
Yeah, for the upside down Android icon, hold Power button while you press Vol Up and it should bring you to the same Recovery menu you get from directly booting to sideload via your PF app.

I also tested this (on the Pixel 7 Pro), and no amount of coaxing seems to work, I saw the same results as you did. Once in sideload mode there is 0 interaction with the phone, and even at the regular main Recovery Mode, there is none, either, meaning we cannot re-authenticate with the adb server on the device.

One thing I did *not* try are instructions I saw on other pages to forcibly tell adb to use port 5555 after connecting via wired, before connecting to adb over Wi-Fi - but I suspect that unless there is a way to programmatically also force the PIN, it still will not help. Still gonna give it a shot, to see - maybe the use of port 5555 will make it skip the need for a PIN? I seriously doubt that, though, that would be a massive security risk IMO. So, I'm expecting this to also not work.

**Comment by JohnLGalt** [comment]
I was able to force port 5555, which then allowed me to connect without any authentication, but upon booting to the bootloader, I could no longer see the device, neither by using port 5555 or by omitting a port entirely, which is what we expected (and which makes sense from a security standpoint).

Bummer.

**Comment by badabing2005** [comment]
Yeah what I suspected too.
I could be wrong, but I don't believe either sideload or fastboot commands support wireless communication, they're low level protocol designed for wired communication.

**Comment by JohnLGalt** [comment]
Hmmm. sideload is a native adb command, though, right? and if everything else (in terms of native adb commands) can work over wireless, then so should it.

Except for the fact that neither the recovery environment nor the bootloader have any access to networking. Theoretically, it could be done, because UEFI supports networking. But I suspect that it would be a massive security hole if it were to be developed.

Anyway, I'm not trying to be argumentative, just trying to figure out why it is the way it is - and I suspect that security is the large part of why there is no networking ability in either environment, which leaves us with a device like the Pixel Watch having no recourse in terms of being able to flash any system images / OTAs unless you have the Developer cable.

Marking this closed as we now have a definitive answer that the PWatch (gen 1) is a no go.
