### ISSUE TITLE
Pixel 8a stuck boot looping

### ISSUE THREAD

**Issue by pennerman** [badabing2005/PixelFlasher#256]
I have tried to root my Pixel 8a and my phone has been boot looping ever since. I cannot enter the recovery mode so I tried using PixelFlasher but it too seems to be looping for some reason. I am on Mac and I have tried doing the process through a virtual machine as well with the same results. Your help is greatly appreciated.

[support_2024-11-20_00-24-16.zip](https://github.com/user-attachments/files/17822846/support_2024-11-20_00-24-16.zip)

**Comment by badabing2005** [comment]
I can see that your device is in bootloader mode.
Do you have the bootloader unlocked?

Can you tell me about the previous state of the device when it was stble, what OS version it had and if it was rooted or not.

What steps you took that brought you into this state?

The answers to the above is crucial to provide you the next steps to recover from this.

**Comment by badabing2005** [comment]
- Download the [factory firmware for your device](https://dl.google.com/dl/android/aosp/akita-ap3a.241105.007-factory-680e6948.zip).
- Process and select the listed init_boot
- Select the following options.
![image](https://github.com/user-attachments/assets/735d15d5-f0d0-448a-978c-96e320802ed7)
- Flash Device.

After that if you want to root.
- Select the stock init_boot from the list
- Hit the Patch button, and choose your patching method
- Select the generated patch
- Hit the `Flash Boot` button (Not the `Flash Device` button)

For future monthly update, I recommend OTA over factort.

**Comment by pennerman** [comment]
I am unsure if I can follow your advice so I will list what I did:
- My phone is in fastboot mode and connected to my Mac.
- I have opened PixelFlasher and selected the android platform tools
- Selected the connected adb device
- Now here for the device image, do I go with the linked folder above and then navigate to the zip inside of it? Because it gives me ![Bildschirmfoto 2024-11-20 um 02 04 26](https://github.com/user-attachments/assets/5a4bd964-4d01-4c41-8c01-c048ebe4d627) as a pop up.

I then do not see the option for init_boot in the list and I can also not find it in the structure of the previously downloaded folder.

I can also not press the flash device button as it is greyed out.

This 
![Bildschirmfoto 2024-11-20 um 02 06 48](https://github.com/user-attachments/assets/db470adb-d3db-4f86-8d8d-3c696641c8bd)

is what it looks like

I am sorry if my questions or problems seem ridiculous, I am a total noob at this and I am so glad for your help and patience!

**Comment by badabing2005** [comment]
This message is exactly what it means.
![387888564-5a4bd964-4d01-4c41-8c01-c048ebe4d627](https://github.com/user-attachments/assets/e53026d8-eea2-4d45-ab3f-b04943f43178)


You should not manually extract files from the factory image, just point to the downloaded file and select it intact.
