### ISSUE TITLE
Flashing failed mid-flash, please help.

### ISSUE THREAD

**Issue by ghost** [badabing2005/PixelFlasher#259]
I was flashing my phone and I believe I have a faulty cable, I've included the logs of where it failed. Please forgive my urgency and desperation but I do not want to brick my brand new phone and I am unfamiliar with the underlying commands to finish or recover manually. The phone is a Pixel 9 Pro XL and this was the initial flash of the latest firmware with unpatched boot images in preparation to flash the modified boot images. Your help is greatly appreciated, I have left the phone connected to the PC and I have not touched it since this happened. I have closed PixelFlasher and done nothing more on the PC as well. I have combed through Google and can't seem to find any discussion on graceful recovery. Thank you in advance. Log follows...

Sending sparse 'super' 11/24 (254972 KB)           FAILED (Error reading sparse file)
fastboot: error: Command failed
[liblp] Partition system_a will resize from 0 bytes to 878813184 bytes
[liblp] Partition system_dlkm_a will resize from 0 bytes to 11681792 bytes
[liblp] Partition system_ext_a will resize from 0 bytes to 321212416 bytes
[liblp] Partition product_a will resize from 0 bytes to 3839606784 bytes
[liblp] Partition vendor_a will resize from 0 bytes to 991580160 bytes
[liblp] Partition vendor_dlkm_a will resize from 0 bytes to 22216704 bytes
[liblp] Partition system_b will resize from 0 bytes to 3448832 bytes

❌ 2024-11-27 11:15:24 ERROR: Encountered an error while running flash script.
Aborting ...

ℹ️ 2024-11-27 11:15:24 INFO: Flashing was aborted.
This could be user initiated or a problem encountered during flashing.

**Comment by badabing2005** [comment]
Hi @SubSpaceManeuvers 
Please launch PixelFlasher and click on create support file, and post that here, no worries it's encrypted.
This would allow me to see exactly where your phone currently stands, and I would give my suggestions after analysing the data.

**Comment by SubSpaceManeuvers** [comment]
Not a problem and thank you for your incredibly speedy response.

[support_2024-11-27_11-49-08.zip](https://github.com/user-attachments/files/17938257/support_2024-11-27_11-49-08.zip)

**Comment by SubSpaceManeuvers** [comment]
I am stepping away from the terminal for 10-15 minutes just in case you should respond and I don't respond back, please don't give up on me. Thank you again for coming to help. I am hoping this is as simple as a reboot or repushing files manually and I am trying to convince myself that I am having irrational fears about the phone somehow spontaneously power cycling itself.

**Comment by badabing2005** [comment]
I see that during factory flashing writing the data failed.
You say it's due to faulty cable,
Have you replaced the cable with a good one?
You should do that now, no worries nohing will happen to your phone.
It's a good thing that your phone is still in bootloader state, which means it can be flashed again with a good cable.
Any reason why you are choosing the wipe option? (just curious, it's perfectly ok to do so, just that it is uncommon)

In the future (not this time) download and sideload full ota instead of factory image, it's much safe that way.

This time, after replacing the cable, just hit the Flash button again and let PixelFlasher flash again, and if your cable is good, it should complete.

Good luck and report back.

**Comment by SubSpaceManeuvers** [comment]
I have replaced the cable and it has rectified the situation, it always seems as if the flimsier cables are the higher quality cables despite the outward appearances. I choose 'Wipe Data' as 'Keep Data' would be contradictory to a factory flash, I don't suppose there is a specific reason outside of my brain following logical (to itself at least) paths to a desired result. I tend to do OTAs as a means of updating to new quarterlies and using a factory flash for major version upgrades of Android  and of course new installs. I'm not sure if the old rule of thumb that OTAs (pertaining to feature phones) are somewhat more prone to issues than factory flashes but it has stuck with me throughout the years. We are down one successful flash and I am at the initial setup wizard, I have full confidence from this point forward and I cannot possibly thank you enough for giving me guidance.

**Comment by SubSpaceManeuvers** [comment]
Completely finished without further issue, you sir are a gentleman and a scholar.

**Comment by badabing2005** [comment]
Yeah, stick to OTA all the time, unless it fails.
The advantage is that it always flashes to the alternate inactive slot, and only on success it switches over, keeping your current one always functional.
