### ISSUE TITLE
Rebooting but I used the right Image

### ISSUE THREAD

**Issue by UnkreativerNutzername** [badabing2005/PixelFlasher#26]
So I downloaded the Oct. factory image and patched the boot file. After flashing the patched boot.img my phone reboots.
[support.zip](https://github.com/badabing2005/PixelFlasher/files/9706528/support.zip)

**Comment by badabing2005** [comment]
Sorry to hear that.

Everything was going good until your ran out of storage space.
```
extracting product.img (2663 MB) to disk...ziparchive W 10-04 13:35:02 11940 11940] Zip: unable to allocate 2792894464 bytes at offset 0: No space left on device
fastboot: error:
failed to extract 'product.img': I/O error
```

**Comment by UnkreativerNutzername** [comment]
Yea I already fixed it. But thanks for your help. You are awesome!
