### ISSUE TITLE
Feature Request: Add aPatch support

### ISSUE THREAD

**Issue by stitchemd** [badabing2005/PixelFlasher#260]
Good evening, I'm not sure how hard or even possible this could be but wanted to suggest anyway. Would love to see the option of using  aPatch rooting in the program as well since it shares a lot of similarities with Magisk. That way the user could choose which method and manage updates and such the way the program currently does with Magisk. Thank you in advance for the consideration.

**Comment by badabing2005** [comment]
aPatch patching has been available since version [6.9](https://github.com/badabing2005/PixelFlasher/releases/tag/v6.9.0.0)

![image](https://github.com/user-attachments/assets/00990c10-f148-4792-b8ee-c551e09e1c0e)

**Comment by stitchemd** [comment]
I ment to add on the possibility of managing the app kinda like your able to with Magisk where its in the tool bar after the install.

**Comment by badabing2005** [comment]
Unfortuantely I can't do much if [programatic access is broken](https://github.com/bmax121/APatch/issues/633).
