### ISSUE TITLE
Pf 7801 tagged by Windows Defender as containing Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by JohnLGalt** [badabing2005/PixelFlasher#261]
Defender scanned my downloads folder when I was extracting other downloads, and it came up with this:

![Screenshot 2024-12-04 120944](https://github.com/user-attachments/assets/b2f71f2f-d4e3-4f82-b487-42ee09f914ed)

I sent it to VT for a confirmation, and get this:

https://www.virustotal.com/gui/file/49c5b944755ffb8b074be723733973151411f28c384d76c8a3ba910bb5b4f5bd/detection/f-49c5b944755ffb8b074be723733973151411f28c384d76c8a3ba910bb5b4f5bd-1733192680

22/72 positives.

Is there a library you're using that may be causing this flag?

**Comment by JohnLGalt** [comment]
First time Defender has flagged it. I went back and checked 7800 and 7710, and VT does show varying FPs for both those versions as well.

Since neither of those two trigger Defender, I'll stick with 7800 and see if future builds trigger Defender as well.

**Comment by badabing2005** [comment]
Feel free to stick to the version you're comfortable with.
In my experience, there is no rhyme or reason as to which version of PF gets triggered by which AV.
It goes a long way showing you how reliable these AVs are.
