### ISSUE TITLE
Device is not in adb mode. Cannot delete init_boot_x.img

### ISSUE THREAD

**Issue by JustNoon** [badabing2005/PixelFlasher#263]
### Environment
Rooted Pixel 7 Pro AP3A.241005.015 with Magisk Canary and PIFix

### What went wrong
Trying to patch and apply the December OTA update errors out with
```
Device: [redacted] is in device mode.
Patching on hardware: cheetah

Deleting /storage/emulated/0/Download/init_boot_2bc8985d.img from the phone ...

❌ 2024-12-13 06:05:42 ERROR: Could not delete /storage/emulated/0/Download/init_boot_2bc8985d.img. Device is not in ADB mode.
Aborting ...
```

### What I expected to happen
Being able to patch the boot image

### Additional details
The device is definitely in adb mode. I can adb shell into it and manipulate everything manually. The connected device selector also has a checkmark indicating root/adb.
I have tried installing Magisk from PF, toggling root permission to Shell in Magisk, Clearing and reregistering adb RSA keys on the phone. All to no avail.

[Attached is the support zip.](https://github.com/user-attachments/files/18126136/support_2024-12-13_06-05-50.zip)

**Comment by badabing2005** [comment]
Something is different about the responses PF receives, notice how every response is preceeded by **0xFF** 

![image](https://github.com/user-attachments/assets/fef6f12a-0632-47cf-adbf-c6d58712bd33)

Speculation on possible causes.
- ADB Corruption (try killing ADB server, and testing again)
- Some custom ROMs might include binary headers or metadata in their adb output, are you using a custom ROM?
- If you're using a terminal emulator or script that interprets the output in a non-standard way, it could prepend unintended binary data, this could possibly be through your windows shell or Android's

I have never seen anything like this in all the logs I have analyzed while supporting PF.
This is definitely unique to your device, and I'm curious to know what is causing it.

**Comment by JustNoon** [comment]
- ADB is latest. I've done reinstalls and restarts as recently as an hour ago.
- Stock pixel images. I think I'm on a patched November one. It was working as of last month.
- I did recently install a terminal emulator on the device, I'll uninstall that just in case it's causing some issue. I will look into finding a different computer to run PixelFlasher from some time today.

**Comment by badabing2005** [comment]
I doubt that any PF changes introduced this issue, but you can try version 7.5.0.0 just to eliminate the possibility.

**Comment by JustNoon** [comment]
Works fine on a different win10 computer

ADB drivers fully updated, terminal emulator on the device was irrelevant. Still doesn't work on the original. I'll continue investigating on my end too.

**Comment by badabing2005** [comment]
Maybe something was added to Windows shell (command).
A startup script that runs with every command?

**Comment by JustNoon** [comment]
Amazing call. Yep. That was exactly it. When I updated my aliases I added
```
@cls
```
to the end which was causing the problem. Probably also explains a weird quirk I was having with node two days ago as well...

Anyways, really appreciate the help. Thank you.

**Comment by badabing2005** [comment]
Great you found it.
Happy to hear it's all good now.
