### ISSUE TITLE
Virus in Pixelflasher.exe

### ISSUE THREAD

**Issue by haydnrotork** [badabing2005/PixelFlasher#264]
Hi, the 2 latest versions I get warning of this virus Trojan:Win32/Wacatac.B!ml in Pixelflasher.exe. Is it so or what?

**Comment by badabing2005** [comment]
False positive,
Please check the Readme and similar duplicate issues here.

**Comment by haydnrotork** [comment]
link to the explaining in xda forum dont work  https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/post-89090938

**Comment by badabing2005** [comment]
> link to the explaining in xda forum dont work https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/post-89090938

Check your internet settings, it works.
