### ISSUE TITLE
How to minimise the chances of a brick?

### ISSUE THREAD

**Issue by expected-ingot** [badabing2005/PixelFlasher#265]
Hi! Sorry if this is a noob question but I want to get a Pixel 9 soon and root it with Magisk. I want to use this app to do so and I want to ask what are the chances of a brick with this app. Do you just need a sturdy cable? Or do you have to do some more work. TYSM I'm advance

**Comment by badabing2005** [comment]
There's always a chance of a brick, though very minute, but not zero.
The most important thing is to educate yourself about the process, how it works, why you do certain things.
Don't use any tool blindly, including this one, know what you're doing and why? on each step of the way, you want to understand what is the exepcted outcome from that step, confirm that it was successful, before moving to the next step.

The application has guide links to very well written guides, read them up.
