### ISSUE TITLE
Crash when clicking "Download Pixel Firmware" without connected phone

### ISSUE THREAD

**Issue by mkomko** [badabing2005/PixelFlasher#28]
When starting PixelFlasher and immediately clicking "Download Pixel Firmware" without connecting the phone prior to that, the following happens:

![image](https://user-images.githubusercontent.com/8350714/194637099-0cac98c6-53c7-45a0-a64d-29155af4ac49.png)

~~PixelFlasher is not usable anymore after that.~~

It's a minor issue, but I take you for a perfectionist 😉.

**Comment by badabing2005** [comment]
Thanks for reporting it,
Yep, a silly coding error, it shouldn't have happened.
You don't have device selected, and with the latest version it's trying to open a device specific URI
Already fixed, will be part of next drop.

> PixelFlasher is not usable anymore after that.
I think you meant usable right?
It's still usable, the spinning cursor makes you think it is not.

Thanks

**Comment by mkomko** [comment]
Oh yeah, you're right, it is usable, my bad. The spinning cursor indeed led me to believing it was not😉.

**Comment by badabing2005** [comment]
This is fixed
