### ISSUE TITLE
Hint for hidden Magisk

### ISSUE THREAD

**Issue by ryder203** [badabing2005/PixelFlasher#3]
My Magisk is hidden, so the renaming is Magic, and the package is existing as _waph.ahlw_ ... 

`adb shell monkey -p com.topjohnwu.magisk -c android.intent.category.LAUNCHER 1`

won't launch it, so give users a hint regarding that maybe.

**Comment by badabing2005** [comment]
Very good point, 
I do mention  that if it is not started, to start it manually.
But it does not hurt to add a hint that the reason it might not be started is because it is hidden.

```
------------------------------------------
Magisk should now be running on your phone
If it is not, Start magisk on your phone, 
patch boot.img found in Download folder:  
$transferPath                             
and then come back here to continue       
CTRL+C to abort                           
------------------------------------------
```

**Comment by badabing2005** [comment]
Done
