### ISSUE TITLE
just wondering?

### ISSUE THREAD

**Issue by shelby691** [badabing2005/PixelFlasher#31]
Is there a specific procedure for flashing most of the new roms? that come in 2 zips and doesn't have the old standard  format so the flasher doesn't have what it needs? If you have already addressed this I apologize for not keeping up.  Appreciate your wonderful work, and thank you for all the details you've provided

**Comment by badabing2005** [comment]
Can you please provide a specific example?

**Comment by shelby691** [comment]
Ok.... Here are 2,  HentaiOS,aospa-topaz-beta-1.1, (by paranoid android)These 2 I have tried and your flasher cannot find boot.img because of how the file comes. However what does work perfectly!Derpfest,Project Zephyrus,Ricedroid,SparkOS.I have flashed all of them to wonderful success. Don't understand why you would say look it up on GitHub or unsubscribe?Cause I wasn't bitchin, or complaining, in fact your flasher is the best I've tried, which is all of them. However if you want to be terse, I'll accommodate you and go to hell I guess.  Anyway I'll type it again, I use and appreciate your wonderful work please continue with everything you do except being short with me LOL Thanks Shelby Fugate On Oct 17, 2022 11:53 AM, badabing2005 ***@***.***> wrote:
Can you please provide a specific example?

**Comment by shelby691** [comment]
got it figured how to apply roms, thanks again brother. I appreciate you
