### ISSUE TITLE
Font and Font size should be configruable by the user

### ISSUE THREAD

**Issue by bnsmb** [badabing2005/PixelFlasher#33]
The fonts used are too small for high resolution displays

**Comment by badabing2005** [comment]
The console and the list items are intentionally set to a smaller font, however all others use the system font at default size.
Where exactly are you seeing the issue? screenshots can help.
I do use the program on 4K displays and they look fine, and my eyes are not what they used to be ;)

**Comment by badabing2005** [comment]
@bnsmb and @mackdacre 
This is done, let me know if you encounter any issues.
Not all fonts are replaced, just the monospaced ones (which were the tiny ones)
