### ISSUE TITLE
Generic Linux build

### ISSUE THREAD

**Issue by ThatOneCalculator** [badabing2005/PixelFlasher#34]
Why are there "Ubuntu" and "Kali" builds? Why not an AppImage or a Flatpak for all distros? Why isn't it even in a packaging format?

**Comment by badabing2005** [comment]
> Why are there "Ubuntu" and "Kali" builds? Why not an AppImage or a Flatpak for all distros?

If you can manage to create a package and get WxPython based application (which is what PixelFlasher is using) working on all Linux distros, then I would happily accept a Pull Request that does it in Github Actions.

> Why isn't it even in a packaging format?

I don't even know what that means.
The single file you download, as the Readme states is an executable package, similar to the AppImage or Flatpak, and it is built with PyInstaller, you just run it.

**Comment by ThatOneCalculator** [comment]
Well it's not really, it's a binary. AppImages and Flatpaks are self-contained and have dependencies built in.

**Comment by badabing2005** [comment]
It's the same with Pyinstaller, it's just packaging so that when you execute it unpacks the dependencies are runs.

In any case if you think you can pull this off with WxPython, be my guest, submit a PR.

**Comment by swebow** [comment]
I think I've manage to build an "agnostic" version.
Sadly I don't know how to package it to an appimage or flatpak.

I've built it with EndeavorOS just using the build.sh script provided in source. Super easy to use. I just needed to install pyinstall 4.10 so the .spec file could be used.

**Comment by badabing2005** [comment]
> I think I've manage to build an "agnostic" version.

What do you mean by `agnostic` version?
It would run on any Linux? how do we know that?

**Comment by badabing2005** [comment]
This is most likely not going to happen.
I don't see PR.
