### ISSUE TITLE
"Flash to both slots" missing

### ISSUE THREAD

**Issue by radioactiv** [badabing2005/PixelFlasher#35]
When updating from below Android 13, a warning is shown that ways Selecting the option "Flash to both slots Will take care of that.".  There's no "Flash to both slots" checkbox on the main screen. 
![pixel_flasher](https://user-images.githubusercontent.com/625653/203128644-96257346-07cd-4cb2-91d6-49de2869c536.PNG)

**Comment by badabing2005** [comment]
Flash to both slots is part of advanced option.
Enabled Advanced Options in advanced configuration and you'd have that option.
See [Expert Mode](https://github.com/badabing2005/PixelFlasher#expert-mode).
