### ISSUE TITLE
Crash when trying to open browse dialog on ubuntu 22.04 

### ISSUE THREAD

**Issue by PrawnMan** [badabing2005/PixelFlasher#36]
```
~/MyApps$ lsb_release -a && uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
Linux USER 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

~/MyApps$ ./PixelFlasher-Ubuntu 
Loading configuration File ...

(PixelFlasher-Ubuntu:1132649): Gtk-WARNING **: 15:11:33.832: Could not load a pixbuf from /com/ubuntu/themes/Yaru-dark/3.0/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(PixelFlasher-Ubuntu:1132649): Gtk-WARNING **: 15:11:37.593: Negative content width -33 (allocation 1, extents 17x17) while allocating gadget (node button, owner GtkButton)

(PixelFlasher-Ubuntu:1132649): Gtk-WARNING **: 15:11:37.593: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)


```

Clicking on any of the browse dialogs causes the program to crash, be it the Platform tools one or the factory image one. Im on version 4.4.0.0 and ubuntu 22.04. Running it under sudo results in the same outcome.

**Comment by bojangles86** [comment]
i have the same issue. although im using garuda linux. i just have to copy and paste the directories i want to use and it seems to accept that. only problem im facing is when i go to flash it crashes then as well.
kali version doesnt open at all

**Comment by badabing2005** [comment]
> i have the same issue. although im using garuda linux. i just have to copy and paste the directories i want to use and it seems to accept that. only problem im facing is when i go to flash it crashes then as well. kali version doesnt open at all

If you can provide a sanitized support.zip (Help Menu) I can take a look why it is crashing during flashing.
Just launch the app and generate support.zip, no need to make it crash again.

@PrawnMan and @bojangles86 
I see that there is now a [wheel file](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/) for Ubuntu 22.04 
Can you try to build the app? and see if that fixes your issue.



Thanks

**Comment by bojangles86** [comment]
> > i have the same issue. although im using garuda linux. i just have to copy and paste the directories i want to use and it seems to accept that. only problem im facing is when i go to flash it crashes then as well. kali version doesnt open at all
> 
> If you can provide a sanitized support.zip (Help Menu) I can take a look why it is crashing during flashing. Just launch the app and generate support.zip, no need to make it crash again.
> 
> @PrawnMan and @bojangles86 I see that there is now a [wheel file](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/) for Ubuntu 22.04 Can you try to build the app? and see if that fixes your issue.
> 
> Thanks

Will take a look when I get home.  Thanks

**Comment by badabing2005** [comment]
Please see if this works for you.
Built on Ubuntu 22.04 WSL

Steps taken to build.
```
sudo apt install python3-pip
pip install virtualenv
sudo apt install python3.10-venv
python3 -m venv venv
. venv/bin/activate
pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04 wxPython
```
edit `requirements.txt` and change the first line to:
`wxPython~=4.2.0`

```
pip3 install -r requirements.txt
ldd ~/dev/PixelFlasher/venv/lib/python3.10/site-packages/wx/core.py
```
find all the missing modules
```
libgtk-3.so.0 => not found
libXxf86vm.so.1 => not found
libSM.so.6 => not found
libnotify.so.4 => not found
libSDL2-2.0.so.0 => not found
libpcre2-32.so.0 => not found
```
Install them
```
sudo apt install libgtk-3-0
sudo apt install libxxf86vm-dev
sudo apt install libsm-dev
sudo apt install libnotify-dev
sudo apt install libsdl2-2.0-0
```
Build it.
```
./build.sh
```

Binary is in `dist` directory.

**Comment by PrawnMan** [comment]
> Please see if this works for you. Built on Ubuntu 22.04 WSL
......
> Binary is in `dist` directory.

I followed your instructions to build it. 

`ldd ~/dev/PixelFlasher/venv/lib/python3.10/site-packages/wx/core.py
`

Didnt work for me so I installed all the libs manually using apt. Building it resulted in the program loading successfully and not crashing when clicking on the "browse" button. I'll run a test flash tomorrow.

**Comment by badabing2005** [comment]
> I followed your instructions to build it.
> 
> `ldd ~/dev/PixelFlasher/venv/lib/python3.10/site-packages/wx/core.py `
> 
> Didnt work for me so I installed all the libs manually using apt. Building it resulted in the program loading successfully and not crashing when clicking on the "browse" button. I'll run a test flash tomorrow.

Thanks for the update, I'm curious to know if you tried [this build](https://github.com/badabing2005/PixelFlasher/releases/download/v4.4.0.0-alpha/PixelFlasher-Ubuntu-22.04).
If that would have worked without you having to install anything else, I would publish a build with every release.

**Comment by bojangles86** [comment]
> > i have the same issue. although im using garuda linux. i just have to copy and paste the directories i want to use and it seems to accept that. only problem im facing is when i go to flash it crashes then as well. kali version doesnt open at all
> 
> If you can provide a sanitized support.zip (Help Menu) I can take a look why it is crashing during flashing. Just launch the app and generate support.zip, no need to make it crash again.
> 
> @PrawnMan and @bojangles86 I see that there is now a [wheel file](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/) for Ubuntu 22.04 Can you try to build the app? and see if that fixes your issue.
> 
> Thanks



> > i have the same issue. although im using garuda linux. i just have to copy and paste the directories i want to use and it seems to accept that. only problem im facing is when i go to flash it crashes then as well. kali version doesnt open at all
> 
> If you can provide a sanitized support.zip (Help Menu) I can take a look why it is crashing during flashing. Just launch the app and generate support.zip, no need to make it crash again.
> 
> @PrawnMan and @bojangles86 I see that there is now a [wheel file](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/) for Ubuntu 22.04 Can you try to build the app? and see if that fixes your issue.
> 
> Thanks

when i click "create sanatized report" in the help menu it causes pixel launcher to crash as well.  :)

**Comment by badabing2005** [comment]
> that build you posted seems to work for me though. so far.. im going to try flashing and see what happens
> 
> edit: that did it. everything flashed without a hitch. root checker confirms my device is rooted.

Thanks for the update.
I assume you did not had to install any libraries, just ran the build and it worked?

@PrawnMan and @bojangles86 
Can we consider this issue resolved?

**Comment by bojangles86** [comment]
Yes and yes. Issue resolved

**Comment by badabing2005** [comment]
Closing the issue.

**Comment by PrawnMan** [comment]
Yep, it worked, thanks, glad you closed it!
