### ISSUE TITLE
PixelFlasher Hanging right after vendor_boot_b image OKAY message

### ISSUE THREAD

**Issue by totempole** [badabing2005/PixelFlasher#38]
Hello,

Attached is the support.zip file as well.

Mac M1 Air Monterey 12.5.1
Phone: Pixel 6a (New out of the box with the bootloader unlocked)
Image: Android 12 SD2A.220601.003.B1, Jul 2022

It doesn't seem to progress past the fastbootd screen after it reboots past "Writing 'vendor_boot_b'                            OKAY [  0.086s]"

I've let it sit in past attempts for 15 minutes or longer and the phone just sits on the fastbootd screen. I've tried the following options:

**Basic Mode:**
Flash to inactive with both keep data and WIPE data options
Unchecked Flash to inactive slot with those same options
Installed Magisk apk via tool and this is succesfull. I see the app in the app drawer and on subsequent adb scans the phone shows up as having Magisk installed.

**Advanced Mode:**
Flash to both slots with both keep data and WIPE data

None of these yield a different outcome. Phone boots back into android 12.
[pixelflashersupport.zip](https://github.com/badabing2005/PixelFlasher/files/10128380/pixelflashersupport.zip)

**Comment by badabing2005** [comment]
This typically suggests driver issue but you're on a Mac which does not require separate drivers.
What happens when the phone reaches the fastbootd state and is just sitting there, if you open a terminal and type `fastboot devices`?
I suspect when your device is in fastbootd mode, it is no longer detected.
Typically using another cable or switching to a USB 2 port solves the issue considering that in your case it can't be a driver issue.

**Comment by totempole** [comment]
Thanks I suspected driver issue as well but as you mentioned, MacOS doesn't need it. I changed the cable too with no effect. I will try it again to the point that it gets to fastbootd and see if the device is seen by my laptop. Will report back.

Nov 30, 2022 8:02:12 PM badabing2005 ***@***.***>:

**Comment by totempole** [comment]
Tried doing it again... Seems to reboot into fastbootd as soon as vendor_boot_b returns OKAY. I checked to see if the device was visible via a separate terminal and sure enough it's there and listed. Given this, I don't think it's a cable issue either (going on 3 different cables now incl. the one that came with the phone and I've used exactly once.. for this)

-------------
sh-3.2# fastboot devices
28231BEFR07704	fastboot
-----------------

**Comment by totempole** [comment]
OK so tried something different... right after i get to fastbootd where it hangs, i rebooted the phone manually back into the bootloader and then killed the fastboot process... this seems to have allowed the script to progress.. Did this for both slots and i now have magisk root on my phone. Seems to be a wait in the script or a race condition.. not a programmer. Zip attached if it helps you.

**Comment by badabing2005** [comment]
Please update here when you do so that it can benefit others who face the same issue.
