### ISSUE TITLE
Flash to inactive slot doesn't work.

### ISSUE THREAD

**Issue by mike-s123** [badabing2005/PixelFlasher#39]
Latest version - 4.5.0.0

Connect phone, do a scan, this is in the result: "Device Active Slot:              a"

Extract and patch boot, Flash Mode "keep data", check Flash to inactive slot. Flash Phone, completes OK, but flashes to existing slot a, not inactive slot. I'll note that nothing is logged when toggling the "Flash to inactive slot" checkbox.

Edit: you should probably include info on the active slot and the slot to be flashed in the confirmation pop-up.

Excerpts from the log:

```
Selected Device on 2022-12-05 18:19:49:
    Device ID:                       25071JEGR06808
    Device Model:                    bluejay
    Device Active Slot:              a
...
2022-12-05 18:22:20 Flashing device 25071JEGR06808 ...
...
Sending 'bootloader_a' (11574 KB)                  OKAY [  0.343s]
Writing 'bootloader_a'                             (bootloader) Flashing pack version bluejay-1.2-9152140
...
Sending 'boot_a' (65536 KB)                        OKAY [  1.940s]
Writing 'boot_a'                                   OKAY [  0.299s]
Finished. Total time: 2.243s
rebooting to system ...
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.001s
2022-12-05 18:26:32 Done!
...
2022-12-05 18:28:59 Scanning for Devices ...
1 Device(s) are found.
2022-12-05 18:29:00 No Device is selected!

Selected Device on 2022-12-05 18:29:07:
    Device ID:                       25071JEGR06808
    Device Model:                    bluejay
    Device Active Slot:              a

```

**Comment by badabing2005** [comment]
When you toggle, it is not logged to console, however before you click ok to flashing you are presented with a dialog that shows all the options that would apply, that is logged to the console as well.

If you provide a sanitized (personal data removed) support.zip file (you can generate one from the help menu) I'll see where things did not work.

**Comment by mike-s123** [comment]
support.zip attached. I didn't see anything about slots in the dialog, and nothing about slots in that section of the log:

`*** Dialog ***
Android SDK Version:    33.0.3-8952118
Device:                 25071JEGR06808 bluejay TP1A.221005.003
Factory Image:          C:\Android\sdk\platform-tools\bluejay-tq1a.221205.011-factory-41aa5eb7.zip

Boot image:             f94ecc0b / f633cc6d 
                        From: C:\Android\sdk\platform-tools\bluejay-tq1a.221205.011-factory-41aa5eb7.zip
                        [Patched] with Magisk 25.2:25200 on bluejay

Flash Mode:             keepData



Note: Pressing OK button will invoke a script that will utilize
fastboot commands, this could possibly take a long time and PixelFlasher
will appear frozen. PLEASE BE PATIENT. 
In case it takes excessively long, it could possibly be due to improper or
bad fasboot drivers.
In such cases, killing the fastboot process will resume to normalcy.

      Do you want to continue to flash with the above options?
              Press OK to continue or CANCEL to abort.
`

I also see this in the log, which is a bit scary.

`Transfering boot.img_f633cc6d.img to the phone in /data/adb/magisk/stock-boot.img ...

2022-12-05 18:20:37 ERROR: Encountered an error.
Return Code: 1.
Stdout: adb: error: stat failed when trying to push to /data/adb/magisk/stock-boot.img: Permission denied
.
Stderr: .
Aborting Backup...

Triggering Magisk again to create a backup ...
Making sure stock-boot.img is found on the phone ...

2022-12-05 18:20:37 ERROR: /data/adb/magisk/stock-boot.img is not found!
Return Code: 1.
Stdout: .
Stderr: ls: /data/adb/magisk/stock-boot.img: Permission denied
.
Aborting run_migration ...
Checking to see if Magisk made a backup of the source boot.img
It looks like backup was not made.

Extracting short SHA1 from magisk_patched_f633cc6d.img ...
Short SHA1 embedded in C:\Users\xxx\AppData\Roaming\PixelFlasher\tmp\magisk_patched_f633cc6d.img is: f633cc6d
Comparing short source boot.img SHA1 with short SHA1 embedded in f633cc6d (they should match) ...
Good: Both SHA1s: f633cc6d match.

`
[support.zip](https://github.com/badabing2005/PixelFlasher/files/10159348/support.zip)

**Comment by badabing2005** [comment]
Thanks for the support.zip file, found the issue and it's fixed and it should be part of the next release soon.
To explain, "Flash to Inactive Slot" used to be part of Advanced Mode feature, and it would only show / apply if advanced mode was turned on, I moved it to Basic mode, but had missed the check to apply.
Had you just enabled the advanced mode, it would have worked.

As for the backup issue, that is fixed as well, it was already reported [here](https://forum.xda-developers.com/t/pixelflasher-for-google-pixel-7-pro-support-thread.4505287/post-87820919).

> FYI, this is not an issue, Magisk makes the backup only after applying the Patch, PF actually triggers a backup when creating a Patch to make sure it's there if need be.
That part was not running as su which is why it failed, Magisk would have still created the backup on flashing / reboot

**Comment by badabing2005** [comment]
Fixed.
Closing the issue, @mike-s123 if there are still any issues related to this, please comment here.
