### ISSUE TITLE
If two or more patched boot.img files are in path script can't handle it

### ISSUE THREAD

**Issue by ryder203** [badabing2005/PixelFlasher#4]
I had started the script, it copied stock boot.img to /Download , I patched the image with Magisk and it gave me magisk_patched-24102_XYZ123.img but from previous tests there still was an old file magisk_patched-24102_OPQ345.img ... the script can't handle that. Maybe it needs a cleanup function for /Download with a warning that old boot.img and magisk_patched-*version*_*string*.img get deleted before copying the fresh stock boot.img.

**Comment by badabing2005** [comment]
I think the cleanest way to tackle is for the script to do the patching.
But until then maybe I'll just issue a warning that older copies will be deleted by the script to assure that what it finds is the correct patched version.

**Comment by badabing2005** [comment]
For now the script first warns that it will delete older files and then deletes them before the patching process.
