### ISSUE TITLE
No can do on Windows 11 Pro

### ISSUE THREAD

**Issue by MarQc13** [badabing2005/PixelFlasher#40]
Howdy all, 

I tried to flash my P6Pro with the latest  PixelFlasher Release v4.5.0.0 the program doesn't load on Windows 11 Pro Edition (Version 22H2
OS Version 22621.900 / Windows Feature Experience Pack 1000.22638.1000.0) 

If I try with Release v4.4.0.0 everything goes flawlessly and was able to install december update. 

Thanks for your hard work!

**Comment by badabing2005** [comment]
Thanks for reporting this.
Interesting, I wouldn't have expected an issue on Windows.
Version 4.5 uses the latest version of wx.Python which is compiled against libraries.
Could you run the application from command line and see if it outputs any errors?
Those could give us clues as to what is missing on your system.

**Comment by MarQc13** [comment]
No error. 
The splash interface appears for many seconds then disappear. I have four instances of PixelFlasher in Task Manager, but the program still doesn't load.
 
<img width="979" alt="PF4500" src="https://user-images.githubusercontent.com/42945549/205785635-53e0a07c-259f-4323-8694-613659f2511f.png">

**Comment by badabing2005** [comment]
Please kill them all (or reboot) and launch from the console without `start`
```
.\PixelFlasher.exe
```
see if comes up or gives any errors?

Thanks

**Comment by MarQc13** [comment]
Same result. Opening splash interface that disappear after few seconds. Want me to try something else with a different tool?

**Comment by badabing2005** [comment]
@MarQc13 and @iCassius 
I changed wx.Python dependency to an older version, see if [this release](https://github.com/badabing2005/PixelFlasher/releases/tag/v4.6.0.1) fixes your issue.

**Comment by ShosGithub** [comment]
> @MarQc13 and @iCassius I changed wx.Python dependency to an older version, see if [this release](https://github.com/badabing2005/PixelFlasher/releases/tag/v4.6.0.1) fixes your issue.

Same issue on 4.6.0.1
Windows 11 22H2

**Comment by badabing2005** [comment]
Really weird, I'm on the same version of Windows.
Ok [here's another build](https://github.com/badabing2005/PixelFlasher/releases/tag/v4.6.0.2) with all the modules dropped to the older version.

Let me know if this resolves it.

**Comment by ShosGithub** [comment]
4.6.0.2 not work too, while 4.4 works well.
New Version stops before it tries to connect Internet.

**Comment by badabing2005** [comment]
Thanks for testing.
These are built on Github with Github actions, I'm attaching a a build from my machine, see if it makes a difference, just in case something has changed on Github.
[PixelFlasher.zip](https://github.com/badabing2005/PixelFlasher/files/10163016/PixelFlasher.zip)

**Comment by ShosGithub** [comment]
not work as well...

**Comment by badabing2005** [comment]
Can you temporarily turn off Anti Virus software in case it is blocking extraction of some files?
Of course turn it back on after testing.
Without being able to reproduce and no console log, I'm just grasping at straws.
Also can you create a support.zip with 4.4.0.0 ? if 4.6.0.0 output anything to the logs, the support.zip will include it.

Thanks

**Comment by MarQc13** [comment]
> Can you temporarily turn off Anti Virus software in case it is blocking extraction of some files? Of course turn it back on after testing. Without being able to reproduce and no console log, I'm just grasping at straws. Also can you create a support.zip with 4.4.0.0 ? if 4.6.0.0 output anything to the logs, the support.zip will include it.
> 
> Thanks

I can do that, give me an hour. I'll do some more testing. If you want me to test something, I'll be glad to help.

**Comment by ShosGithub** [comment]
i got this
hope it will be helpful

-------------

Traceback (most recent call last):
  File "wx\core.py", line 2346, in Notify
  File "wx\core.py", line 3552, in Notify
  File "Main.py", line 2006, in _show_main
  File "Main.py", line 100, in __init__
  File "Main.py", line 113, in initialize
  File "Main.py", line 61, in write
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 19-24: ordinal not in range(256)

**Comment by MarQc13** [comment]
Support generated from v4.4.0.0 

[support v4400.zip](https://github.com/badabing2005/PixelFlasher/files/10166692/support.v4400.zip)

**Comment by MarQc13** [comment]
[Version 4.6.0.0] 
In Windows Debbuger two errors are detected. Hope it helps.

<img width="1496" alt="Error dat 1" src="https://user-images.githubusercontent.com/42945549/205930065-793379c1-2911-4ec8-b800-1e3a61488cb3.png">
<img width="1489" alt="Error dat 2" src="https://user-images.githubusercontent.com/42945549/205930066-b446ffdd-78f8-467f-8835-74f1b267d028.png">
<img width="1178" alt="Win debbuger" src="https://user-images.githubusercontent.com/42945549/205930067-106b9d41-7dfc-4d84-9404-b91a29508173.png">

**Comment by badabing2005** [comment]
Thanks @ShosGithub and @MarQc13 
That help a lot.
I just created another version, that handles encoding errors.
Let's see if that works.

Another thing you should try,
Run PF 4.4.0.0 and set the encoding to cp1252 in configuration, exit PF and start PF 4.6.0.0
![image](https://user-images.githubusercontent.com/22603312/205931694-229f543d-4817-466b-9e24-8a78e59757d2.png) see if that works.

Thanks

**Comment by MarQc13** [comment]
Force codepage on PF 4400 doesn't seem to change anything for PF 4600. 

BUT version 4603 loads flawlessly! Great job Buddy!

**Comment by badabing2005** [comment]
@MarQc13 
Thanks for the update and all the feedback.
Happy to learn that we finally got this working.
Later today when I get some free time, I'll merge the code to main and release an official version.

Thanks everyone who contributed to this thread.

**Comment by ShosGithub** [comment]
Thanks! 4.6.0.3 runs properly. Great Job!

**Comment by badabing2005** [comment]
Closing the issue.
4.6.1.0 is released
