### ISSUE TITLE
Avast antivirus identify v4.6.1.0 as malware

### ISSUE THREAD

**Issue by lupohan44** [badabing2005/PixelFlasher#41]
Hi, avast identify latest version(v4.6.1.0) as malware(Win64:Evo-gen[Trj]). I have submitted false alarm, can you please help with this?

**Comment by badabing2005** [comment]
Not sure what I can do to help with false positive.

**Comment by lupohan44** [comment]
> Not sure what I can do to help with false positive.

Maybe you can submit samples too? Since you are the owner, maybe they will respond faster.

**Comment by badabing2005** [comment]
Submitted, can't do much beyond that.
![image](https://user-images.githubusercontent.com/22603312/206747239-8470ae93-3019-42fd-a2b5-39c9098bf434.png)

**Comment by badabing2005** [comment]
Issue is resolved, VirusTotal all passing.

**Comment by lupohan44** [comment]
> Issue is resolved, VirusTotal all passing.

Thank you for your help.
