### ISSUE TITLE
ran out of storage space issue.

### ISSUE THREAD

**Issue by nerdguy1338** [badabing2005/PixelFlasher#42]
I'm having this exact problem with a pixel 6a, it was rooted on the november update, I was trying to get the december update to flash, and now it's seemingly stuck in fastboot mode. Obviously I could just delete some things to free up some space, but how do i get into the filesystem through adb to do that? 

Everything was going good until your ran out of storage space.
```
extracting product.img (2663 MB) to disk...ziparchive W 10-04 13:35:02 11940 11940] Zip: unable to allocate 2792894464 bytes at offset 0: No space left on device
fastboot: error:
failed to extract 'product.img': I/O error
```

_Originally posted by @badabing2005 in https://github.com/badabing2005/PixelFlasher/issues/26#issuecomment-1266971327_

**Comment by badabing2005** [comment]
Try flashing one partition at a time, what the full factory does, take a look at flash_all file
You would also need to take a look at the update image zip file contents
Try flashing your current firmware not the update, so that you can manage to boot to system and clear some space.

**Comment by nerdguy1338** [comment]
How do I flash the current firmware and still keep root? I've heard from a
few people that if I flash stock with an unlocked bootloader my phone will
be bricked.

**Comment by nerdguy1338** [comment]
Update:
Well, i wiped my phone for nothing, because it apparently was just my literal laptop not having enough space to extract the damn file.

lol.

thanks for the help. this tool rocks.

**Comment by badabing2005** [comment]
Sorry for your troubles.
> I've heard from a few people that if I flash stock with an unlocked bootloader my phone will be bricked.
FYI , that is not true, flashing stock firmware will not brick your phone.

**Comment by nerdguy1338** [comment]
I really appreciate this app. Thanks for making it!

It worked perfectly 20 minutes ago!

May I suggest adding a working directory configuration option?

**Comment by badabing2005** [comment]
> I really appreciate this app. Thanks for making it! It worked perfectly 20 minutes ago! May I suggest adding a working directory configuration option?
