### ISSUE TITLE
[Request] Implement Updater functionality

### ISSUE THREAD

**Issue by scottismyname** [badabing2005/PixelFlasher#46]
I have no programming experience with Python or else I'd submit a PR myself. 

This library seems simple enough to use though?
https://pypi.org/project/AutoUpdate/

**Comment by badabing2005** [comment]
The product already has updater functionality.

**Comment by scottismyname** [comment]
Sorry I meant more of an automated process.

Like, program opens, checks for an update, prompts you to upgrade... If you click yes, update is downloaded to a temporary file, program closes, temporary file gets renamed to executable name.

I understand that manual updating is not difficult, but if the above can be done without much trouble, why not?

**Comment by badabing2005** [comment]
I see what you're asking, but it's not as simple as that, there are multiple builds that are posted, and the user could be running any one of those builds, a person could be running Kali Linux build on Debian, so keying on the OS is not sufficient, each build needs to be tagged differently, which only means that the build is no longer generic and needs to be customized for each platform, of course it can be done, but how much added value it brings? compared to the user downloading the version that they want and running it, it's a single file that doesn't even require an installation.

It's always a matter or ROI (return on investment).
At some point I need to rework on the build process to support even more platforms, I might include it then if it is feasible.

**Comment by scottismyname** [comment]
Ok that makes sense, thanks for the explanation!
