### ISSUE TITLE
UnboundLocalError: local variable '_magisk_sha1' referenced before assignment

### ISSUE THREAD

**Issue by PilgrimToHyperion** [badabing2005/PixelFlasher#48]
After upgrading to the latest rom, I plugged my Pixel Pro 7 back in, scanned for it, selected it and then clicked the purple Magisk Backup Manager button.

I get this error and just a spinning circle (Window load icon).

![image](https://user-images.githubusercontent.com/28935079/217656479-ea9e2c80-dbb1-4833-bd05-58ad1cb60444.png)

I thought it might be because I hid Magisk, but after unhiding it, the behaviour is the same. 

Thank you for an awesome app!

**Comment by badabing2005** [comment]
You have to grant su (root) access to adb shell in Magisk.
The fact that it shows your `Device is Rooted: False` suggests that you have not allowed that.
See Basic usage point 2.

**Comment by badabing2005** [comment]
I'll disable the button to avoid this from happening.
