### ISSUE TITLE
Android 14 Developer Preview Pixel 7 Pro

### ISSUE THREAD

**Issue by AmyClaraRose** [badabing2005/PixelFlasher#50]
![image](https://user-images.githubusercontent.com/8126609/218296520-5077f7d6-b3c2-4b7e-a31e-2998887c1d1a.png)
wanted to try out Android 14 dev preview but when processing the firmware file boot.img listing is boot not init_boot.img

**Comment by AmyClaraRose** [comment]
it works as intended on other Pixel 7 firmware including QPR beta

**Comment by AmyClaraRose** [comment]
solved my issue by removing _beta from all file names for some reason pixelflasher thinks for pixel 7/pro that _beta makes it a different device

**Comment by badabing2005** [comment]
Thanks for reporting this,
I'll have PF handle beta in the name (or any other suffix) in the next release.
