### ISSUE TITLE
not sure it's worth the trouble

### ISSUE THREAD

**Issue by shelby691** [badabing2005/PixelFlasher#52]
but it would be cool if there were a script for partition adjustments for older Pixels. Pixel 2xl to be exact. would like to upgrade to 13

**Comment by XslifeX** [comment]
> but it would be cool if there were a script for partition adjustments for older Pixels. Pixel 2xl to be exact. would like to upgrade to 13

There are, from same source. I was having trouble finding this one.

**Comment by badabing2005** [comment]
@shelby691 and @XslifeX 
There are no plans to add such feature to PixelFlasher.
There is too much risk bricking your device if not done properly, and it varies from device to device.
These are advanced features that require intimate knowledge and understanding, it just doesn't make sense automating this and encouraging people to use it without understanding.
