### ISSUE TITLE
set custom temp directory

### ISSUE THREAD

**Issue by bitpixl** [badabing2005/PixelFlasher#53]
Hi,

Would it be possible to add an advanced option to set a custom "temp/working"-directory?
My hardened Windows system will not run executables from the normal user temp folder, which leads to an error while trying to process the rom and unpack the boot.img. (7z.exe is blocked)

If I would be able to set a custom "temp/working"-directory from PixelFlasher, this would be solved and my system can remain secure.

thank you in advance.

**Comment by badabing2005** [comment]
PixelFlasher is a python program, bundled into a [single executable](https://pyinstaller.org/en/stable/operating-mode.html#how-the-one-file-program-works) by [PyInstaller](https://pypi.org/project/pyinstaller/).

I cannot add an option into PixelFlasher to define where it should be unpacked, the option can only be read if the program is unpacked and executed (which would be too late at that point), however pyinstaller supports `--runtime-tmpdir` flag to define which directory to use as temporary directory.
You might want to try launching PixelFlasher with that option, although in my tests and other reports, that option does not work.
You can also try to start the application from a terminal / script where the Temp folder value is overridden.
Lastly you can clone the project, and hard code in `build-on-win.spec` to your liking and build your own.
Or run with python from the folder of your choosing.

Good luck.

**Comment by bitpixl** [comment]
I will look into the possible solutions 👍

**Comment by badabing2005** [comment]
Closing the issue.
