### ISSUE TITLE
probably something i'm doing wrong

### ISSUE THREAD

**Issue by shelby691** [badabing2005/PixelFlasher#54]
gets a "unable to detect device fault after flashing bl

**Comment by badabing2005** [comment]
Please provide sanitized support.zip (from the help menu)
I suspect you're using Android platform Tools version 34?
It's known to have problems, if you are, use 33.0.3 and you should be fine.
But support.zip helps identifying exactly what is going wrong where.

**Comment by shelby691** [comment]
[support_2023-03-11_23-46-30.zip](https://github.com/badabing2005/PixelFlasher/files/10950061/support_2023-03-11_23-46-30.zip)
[support.zip](https://github.com/badabing2005/PixelFlasher/files/10950062/support.zip)

**Comment by badabing2005** [comment]
@shelby691 
Change Android platform tools to 33.0.3
Don't use Magisk 25210, if you want to use canary, then use 25206
You should be fine.

**Comment by shelby691** [comment]
thank you very much

**Comment by badabing2005** [comment]
Closing the issue.
If you encounter any issues, please log another ticket if you can't comment here.
