### ISSUE TITLE
Pixel 7 Pro - Device Not Detected in Fastboot Mode (& Patch Fails?)

### ISSUE THREAD

**Issue by Sceleratis** [badabing2005/PixelFlasher#55]
This seems similar to https://github.com/badabing2005/PixelFlasher/issues/43 however in this case I'm running PixelFlasher on Windows 11 and did not find a resolution at that issue (I think the solution they had was to run as root on Ubuntu.)  For what it's worth I tried running PixelFlasher as an administrator just to try it and there was no difference. I've also tried completely removing all files in AppData/Roaming related to it and restarting my computer but still no luck.

While booted as normal on my phone with USB debugging enabled it has no issue detecting my device via ADB and performing the initial reboot to bootloader:
![image](https://user-images.githubusercontent.com/18238620/224835817-7b7eaf43-80cf-403a-bcd1-9541442d7890.png)

But once it reboots, it fails to re-find the device via fastboot:
![image](https://user-images.githubusercontent.com/18238620/224836046-6a4269bd-ed0b-43a0-abe3-fdc2952ad60f.png)

Rescanning for devices also yields nothing, despite fastboot on the command line having no issue finding my device...
![image](https://user-images.githubusercontent.com/18238620/224836297-a44ae16b-16a2-49bf-820f-5b02b321c025.png)

I'm using the same fastboot executable PixelFlasher should be using from the same platform-tools folder. 
It also seemed to fail to patch init_boot with Magisk so I ended up patching via Magisk's manager and transferring (replacing the original init_boot.img with the patched one then trying to patch that for some reason "works" though?) I have the necessary Android USB & bootloader drivers installed.

[support_2023-03-13_17-37-34.zip](https://github.com/badabing2005/PixelFlasher/files/10962161/support_2023-03-13_17-37-34.zip)

**Comment by therealmarv** [comment]
I have that problem also on Intel Mac. Platform Tools 34.0.1 did not fix the problem.

Download the old Android Platform Tools 33.0.3 and extract them somewhere. Point Pixelflasher to use them.

Windows:
https://dl.google.com/android/repository/platform-tools_r33.0.3-windows.zip

Mac:
https://dl.google.com/android/repository/platform-tools_r33.0.3-darwin.zip

**Comment by badabing2005** [comment]
As @therealmarv said, the latest functional Android platform tools is 33.0.3, change it to that and you should be fine. versions 34.0.x can't get into userspace fastboot mode (fastbootd)
Having said that, it looks like in 34.0.1 they have changed the output slightly, which is why PF was not able to detect the device even though the command `fastboot devices` was able to find it.
I'll fix that in the next release.

**Comment by Sceleratis** [comment]
Downgrading to platform tools r33.0.3 fixed the issue for me, thanks 👍
