### ISSUE TITLE
"This buid of SDK platform tools has known issues, please select another version"

### ISSUE THREAD

**Issue by UnkleFunk** [badabing2005/PixelFlasher#56]
When I try to select the newest or frankly, any version of platform tools, I get this same message: "This version has known issues, select another version" - and because I cannot select a version without issues, I am not able to select my Pixel 3aXL from the drop down menu below the platform tools box. I can't scan for any phones, even though I Am connected to my Mac , and can transfer files back and forth with the Android Transfer app. 
Including Screenshots to show you what I am seeing, as well as info about my macbook, in case that may matter. If I am missing any info needed to address the issue I am having, sorry just let me know. Thanks in advance. 
-Glenn

![Screen Shot 2023-03-15 at 3 16 09 PM](https://user-images.githubusercontent.com/79250389/225418870-50d33247-902d-4d04-b24f-4b1a633729f9.png)
![Screen Shot 2023-03-15 at 3 16 29 PM](https://user-images.githubusercontent.com/79250389/225418954-a8bb4c4f-12d8-409c-969b-670931573dee.png)
![Screen Shot 2023-03-15 at 3 17 10 PM](https://user-images.githubusercontent.com/79250389/225419107-0c2c051c-8984-4509-a3e8-6acf76ec72b9.png)
![Screen Shot 2023-03-15 at 3 18 33 PM](https://user-images.githubusercontent.com/79250389/225419444-d4bd6dce-cf4c-4b0f-bb8e-f4ca50a04927.png)

**Comment by badabing2005** [comment]
both versions 34.0.0 and 34.0.1 have issues, the latest good version is 33.0.3-8952118

https://dl.google.com/android/repository/platform-tools_r33.0.3-windows.zip - Windows
https://dl.google.com/android/repository/platform-tools_r33.0.3-darwin.zip - Mac
https://dl.google.com/android/repository/platform-tools_r33.0.3-linux.zip - Linux

You should be good with that.

**Comment by badabing2005** [comment]
closing the issue
