### ISSUE TITLE
Detected as virus

### ISSUE THREAD

**Issue by andreapx** [badabing2005/PixelFlasher#57]
I've download the latest Windows executable and it's detected as a virus by 6 antivirus.
What's going on inside this file???
![image](https://user-images.githubusercontent.com/13846728/228067735-debcad43-67a9-4e39-bf62-0c407f5161ce.png)

**Comment by badabing2005** [comment]
False positive.
Please see #41
And [this discussion](https://forum.xda-developers.com/t/pixelflasher-concern.4567703/).
