### ISSUE TITLE
Adding Magisk 32bit Support - Enhancement

### ISSUE THREAD

**Issue by RareMaker50** [badabing2005/PixelFlasher#58]
Just wondering if you could add support to this fork of Magisk in the Magisk Manager Downloader, Patcher, and Module Manager, since I personally use it and know many people that do and I think it would be a helpful enhancement.

Link: https://forum.xda-developers.com/t/tutorial-magisk-enabling-32-bit-support-for-apps.4521029/

**Comment by badabing2005** [comment]
Please see [this](https://forum.xda-developers.com/t/pixelflasher-for-google-pixel-7-pro-support-thread.4505287/post-88174491) post.

**Comment by RareMaker50** [comment]
Hey there, Nameless wonder had added the json support if this can be an added feature soon

**Comment by badabing2005** [comment]
It will be in the next release.

**Comment by RareMaker50** [comment]
alright thank you! just wondering if you have any eta on that?

**Comment by badabing2005** [comment]
Should be ready before or just after May firmware release.
I say just after in case I need to make adjustments for May release if Google decides to make massive changes.

**Comment by badabing2005** [comment]
[Released](https://github.com/badabing2005/PixelFlasher/releases/tag/v4.9.0.0)

**Comment by NBruderman** [comment]
> alright thank you! just wondering if you have any eta on that? 

It's out
