### ISSUE TITLE
Support Loose boot.img

### ISSUE THREAD

**Issue by Funtime60** [badabing2005/PixelFlasher#59]
I manually extract my boot.img from the zip so I don't have to keep an entire 2-4GB file. I can do this all manually, but I never remember how and so having a tool to use like this would be great instead of having to go back to a bloated guide and having to decipher it again.

**Comment by badabing2005** [comment]
sorry but I don't understand your question / request, or is it?

**Comment by badabing2005** [comment]
No response, closing the issue
