### ISSUE TITLE
image file only older february

### ISSUE THREAD

**Issue by linuxdep** [badabing2005/PixelFlasher#63]
Hi under https://developers.google.com/android/ota?hl=de#oriole i found only images older february 2023???
search with google i found newer under https://developer.android.com/about/versions/13/download#factory-images 

why???

I use version 4.8.2.0

**Comment by badabing2005** [comment]
You have to ask that to Google, this has nothing to do with PixelFlasher.
Change language to English and it probably would show.
Again, I have no control on what Google does :)
