### ISSUE TITLE
Issue with Release v4.9.0.0

### ISSUE THREAD

**Issue by mike-s123** [badabing2005/PixelFlasher#66]
edit: same happens with Release v4.10.0.0

When patching the May '23 Pixel 6a image, PixelFlasher v4.9.0.0 hangs while patching. Magisk 25.2. Upgraded to Magisk 26.1, same thing.

`
Extracting short SHA1 from magisk_patched_25200_40100d6b_8e174e53.img ...
Traceback (most recent call last):
  File "Main.py", line 2022, in _on_patch_boot
  File "modules.py", line 1890, in patch_boot_img
  File "modules.py", line 1054, in extract_sha1
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 3: invalid start byte
`
[support_2023-05-01_14-19-08.zip](https://github.com/badabing2005/PixelFlasher/files/11367203/support_2023-05-01_14-19-08.zip)

**Comment by badabing2005** [comment]
Can you pass me this file please.
`C:\Users\REDACTED\AppData\Roaming\PixelFlasher\tmp\magisk_patched_25200_40100d6b_8e174e53.img`
Replace REDACTED with your username

**Comment by n0k0m3** [comment]
I got the same problem
[magisk_patched_26100_40100d6b_2b749cd5.img.zip](https://github.com/badabing2005/PixelFlasher/files/11367675/magisk_patched_26100_40100d6b_2b749cd5.img.zip)

**Comment by badabing2005** [comment]
Thanks, looking into it.

**Comment by badabing2005** [comment]
@n0k0m3 is it possible to get support file from you as well?
Thanks

**Comment by mike-s123** [comment]
Not the same filename, because I've tried since, but the problem still exists with this one... zipped because github won't accept .img files.

[magisk_patched_26100_40100d6b_20a487c1.zip](https://github.com/badabing2005/PixelFlasher/files/11367793/magisk_patched_26100_40100d6b_20a487c1.zip)

**Comment by n0k0m3** [comment]
> @n0k0m3 is it possible to get support file from you as well? Thanks

Here it is
[support_2023-05-02_09-43-14.zip](https://github.com/badabing2005/PixelFlasher/files/11373805/support_2023-05-02_09-43-14.zip)

**Comment by badabing2005** [comment]
Can you guys do me a favor?

@mike-s123 
Using Magisk 25.2:25200 app,
select the following file `/sdcard/Download/boot.img_40100d6b.img` and create a patch
Give me that file.

@n0k0m3  
Using Magisk 26.1:26100 app,
select the following file `/sdcard/Download/boot.img_40100d6b.img` and create a patch
Give me that file.

Thanks

**Comment by n0k0m3** [comment]
Here
[magisk_patched-26100_J8uuc.img.zip](https://github.com/badabing2005/PixelFlasher/files/11375661/magisk_patched-26100_J8uuc.img.zip)

**Comment by mike-s123** [comment]
[magisk_patched-25200_2jgmE.zip](https://github.com/badabing2005/PixelFlasher/files/11376295/magisk_patched-25200_2jgmE.zip)

I checked, it's identical to the one done via PixelFlasher.

**Comment by badabing2005** [comment]
Thanks @n0k0m3 and @mike-s123 
Next version will handle this scenario gracefully.

**Comment by mike-s123** [comment]
Thanks. I saw your post over on XDA, and it seems that this is at root a Magisk issue.

**Comment by badabing2005** [comment]
v5.0.0.0 released
