### ISSUE TITLE
4.10.0.0 windows defender detects virus.

### ISSUE THREAD

**Issue by whitewallman** [badabing2005/PixelFlasher#67]
Cannot use 4.10.0.0 because windows 11 detects Program:Win32/Cayunamer.A!ml virus and removes immediately.

**Comment by umpf1** [comment]
Same thing for me

**Comment by badabing2005** [comment]
It's probably a false positive, I never heard of this malware and MS does not provide much details.
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Program:Win32/Cayunamer.A!ml&ThreatID=274594

You can decide for yourself if the [changes that were introduced in 4.10](https://github.com/badabing2005/PixelFlasher/commit/62d7494dcae5cda13e11ff6682e9f46d02ebbb86) is acceptable to you.
You can also [build it yourself](https://github.com/badabing2005/PixelFlasher#build-it-yourself).

With almost every release there is some sort of false positive flagging.
see #57, #41

**Comment by whitewallman** [comment]
Thank you for your response. I thought that may be the issue.
