### ISSUE TITLE
No devices found when going to fastboot

### ISSUE THREAD

**Issue by BThornAlpha** [badabing2005/PixelFlasher#69]
I know that this problem is something that keeps nailing people and it isn't a PixelFlasher problem (currently it is a me problem). I know that there is the laundry list of things to try with it. Different cables, different machines, updating drivers and so on. Would it be possible to have PixelFlasher run a check on what is currently installed and warn a user if they are going to have the fastboot issue before it tries it and ends up having to abort? I am going kinda nuts now. I have done all the driver bits. I downloaded from google and windows 11 is telling me I already have the best ones for my device (pixel 6 pro). I downgraded my platform tools after the popup from PixelFlasher. Rebooted tried on laptop and desktop. Same thing every time:
"2023-05-08 11:09:43 Scanning for Devices ...
1 Device(s) are found.
2023-05-08 11:09:43 No Device is selected!"
There are hundreds of forums that always list the same handful of fixes (none of them working for me currently) I am just wondering if PixelFlasher can be made to catch the problem and tell you what to do ahead of time? I know that it can't tell someone if they are going to need a different cable or anything like that. 

Thank you for your time. Love PixelFlasher when I can get things working.

**Comment by badabing2005** [comment]
>"2023-05-08 11:09:43 Scanning for Devices ...
1 Device(s) are found.
2023-05-08 11:09:43 No Device is selected!"

Without know the full context.
All this is telling you is that you have done a scan, and PixelFlasher has detected one device connected to PC, however you have not selected that device for operations.
That is, did you drop down the device and select the device?
You know you could have multiple devices connected, and PF works fine, all you have to do is select the device you want to operate on.

I know you talked about fastboot, and you wanted PF to tell you if you're going to have any issues with fastboot.
Have you tried the dry mode?
That is exactly for that, it goes through the fastboot cycle (and in the next version  it will also go through fastbootd) does couple of reboots and checks, to make sure your device is working in fastboot.
If it doesn't, then your device will get stuck in bootloader mode, as at that point there is nothing PF can do to communicate with your device, and you have to reboot manually.

I can't think of any other way to improve on that.
