### ISSUE TITLE
Build fail errors

### ISSUE THREAD

**Issue by sawdoctor** [badabing2005/PixelFlasher#70]
Trying to build on manjaro (arch) and I'm getting the following errors
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5wtuqeov/wxpython_ff406a1dbce44e48bf9f87dc5fef716e/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-5wtuqeov/wxpython_ff406a1dbce44e48bf9f87dc5fef716e/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

I am out of my comfort zone with building from source so apologise if I've done something stupid. I was hoping I'd find it in the AUR but alas no luck

**Comment by badabing2005** [comment]
The biggest challenge is getting wxPython building which appears to be failing in your case.
Follow the steps outlined in the [build](https://github.com/badabing2005/PixelFlasher#build-it-yourself) section, but before you actually do the build see if you can find a wxpython wheel for your environment, if you do, just [install the wheel](https://www.wxpython.org/pages/downloads/) before doing the build.

**Comment by sawdoctor** [comment]
Like i said I'm out of my depth a liitle but i think i have the wheel installed

[sawdoctor@sawdoctor-gs726qe PixelFlasher-main]$ pip3 install virtualenv
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: virtualenv in /usr/lib/python3.10/site-packages (20.17.1)
Requirement already satisfied: distlib<1,>=0.3.6 in /usr/lib/python3.10/site-packages (from virtualenv) (0.3.6)
Requirement already satisfied: filelock<4,>=3.4.1 in /usr/lib/python3.10/site-packages (from virtualenv) (3.12.0)
Requirement already satisfied: platformdirs<3,>=2.4 in /home/sawdoctor/.local/lib/python3.10/site-packages (from virtualenv) (2.6.2)
[sawdoctor@sawdoctor-gs726qe PixelFlasher-main]$ pip install -U wxPython
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wxPython in /usr/lib/python3.10/site-packages (4.2.0)
Requirement already satisfied: pillow in /usr/lib/python3.10/site-packages (from wxPython) (9.4.0)
Requirement already satisfied: six in /usr/lib/python3.10/site-packages (from wxPython) (1.16.0)
Collecting numpy
  Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 20.0 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.24.3
[sawdoctor@sawdoctor-gs726qe PixelFlasher-main]$ python3 -m venv venv
[sawdoctor@sawdoctor-gs726qe PixelFlasher-main]$ . venv/bin/activate
(venv) [sawdoctor@sawdoctor-gs726qe PixelFlasher-main]$ pip3 install -r requirements.txt
Collecting wxPython>=4.2.0
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 MB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

**Comment by badabing2005** [comment]
You need to install the wheel in venv
So do the wheel installation after activating the venv

**Comment by sawdoctor** [comment]
Sorry to keep bothering you, not sure if I'm still doing something wrong or if I need a different wxPython or I'm just stupid
[sawdoctor@sawdoctor-gs726qe PixelFlasher-4.10.0.0]$ python3 -m venv venv
[sawdoctor@sawdoctor-gs726qe PixelFlasher-4.10.0.0]$ . venv/bin/activate
(venv) [sawdoctor@sawdoctor-gs726qe PixelFlasher-4.10.0.0]$ pip install -U wxPython
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wpo0fd0o/wxpython_9c9ef8bc6c5a440f914717708ca77f85/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-wpo0fd0o/wxpython_9c9ef8bc6c5a440f914717708ca77f85/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by badabing2005** [comment]
don't do `pip install -U wxPython`
You need to get a wheel from [here](https://extras.wxpython.org/wxPython4/extras/linux/) as described [here](https://www.wxpython.org/pages/downloads/) and do pip install of the wheel.

Similar to the example: (obviously replace with the appropriate wheel)
```
pip install -U \
    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \
    wxPython
```

Which wheel to get is dependent on your OS, GTK version and Python version.
You can experiment.

**Comment by sawdoctor** [comment]
Thanks for all your help. There isn't a version listed for arch and no matter what I try it defaults to using the cached version. I'll do a little more digging and googling to see what I can come up with

**Comment by sawdoctor** [comment]
Using the Fedora36 package worked in the end. Thanks for all your help, really appreciated

**Comment by badabing2005** [comment]
Happy to learn that you managed to get it to work.
I know it is a PITA to set it up.
