### ISSUE TITLE
13.0.0 (TQ2A.230505.002, May 2023) Patching Error

### ISSUE THREAD

**Issue by zamarax** [badabing2005/PixelFlasher#72]
When upgrading to 13.0.0 (TQ2A.230505.002, May 2023) release on Pixel 6 Pro it fails to install the patched file correctly and throws error

`archive does not contain 'boot_other.img'
archive does not contain 'odm.img'
archive does not contain 'odm_dlkm.img'
extracting product.img (2620 MB) to disk...ziparchive W 05-12 10:11:19 22904 15236] Zip: unable to truncate file to 2747408384: Invalid argument
fastboot: error:
failed to extract 'product.img': I/O error
rebooting to bootloader ...
Rebooting into bootloader                          OKAY [  0.001s]
Finished. Total time: 0.001s
Sleeping 5-10 seconds ...
flashing pf_boot ...
Sending 'boot_a' (65536 KB)                        OKAY [  1.918s]
Writing 'boot_a'                                   OKAY [  0.079s]
Finished. Total time: 2.001s
rebooting to system ...
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.001s
2023-05-12 10:11:29 Done!
Flashing elapsed time: 72 seconds
------------------------------------------------------------------------------

`

This then results in a boot loop and soft bricks the device.

I have tried both PixelFlasher 4.10.0 and 4.9.0

**Comment by badabing2005** [comment]
See details [here](https://forum.xda-developers.com/t/pixelflasher-for-google-pixel-6a-support-thread.4482703/post-88526043)
