### ISSUE TITLE
Add Pixel 7a support

### ISSUE THREAD

**Issue by carcheky** [badabing2005/PixelFlasher#74]
pixel 7a uses init_boot.img too

**Comment by carcheky** [comment]
image name 'lynx'

**Comment by carcheky** [comment]
[issue74.patch](https://github.com/badabing2005/PixelFlasher/files/11507388/issue74.patch)

**Comment by badabing2005** [comment]
Thanks for your contribution, I have a more generic solution implemented already that should work with future products as well (considering that more and more Google devices that use init_boot are to be released soon.

When dealing with factory images, it will auto detect the included init_boot and use that to extract / patch
When flashing to device, it will auto detect device support for init_boot (partition) and flash to that.
I'm just wrapping up the final pieces, it is a big release hence why it's taken some time, it will be release 5.0.

Thanks again, don't let this discourage you from submitting future contributions, I encourage sharing and collaboration.

**Comment by badabing2005** [comment]
Sorry, I'll keep it open until 5.0 is released, in case anyone wants to use the patch in the interim.

**Comment by badabing2005** [comment]
v5.0.0.0 released
