### ISSUE TITLE
Version 5.0.0.1 Crashing on Manjaro/Arch

### ISSUE THREAD

**Issue by sawdoctor** [badabing2005/PixelFlasher#76]
Version 4.10 works perfectly on Manjaro but unfortunately neither of the new Ubuntu versions work. [Ubuntu_20_04] will launch but fc when ever you try to select platform tools. [Ubuntu_22_04] won't launch and gives the following error

Traceback (most recent call last):
  File "PixelFlasher.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Main.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: /usr/lib/libwx_baseu_net-3.2.so.0: undefined symbol: _ZNK13wxSecretValue11GetAsStringERK8wxMBConv
[32928] Failed to execute script 'PixelFlasher' due to unhandled exception!

I know neither versions are meant for arch based distros but be great if we managed to get a universal Linux version working

Edit here's the error log for the fc on Ubuntu_20_04
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)

**Comment by badabing2005** [comment]
Is [5.0.1.0 release](https://github.com/badabing2005/PixelFlasher/releases/tag/v5.0.1.0) also giving the same error.

The thing is builds prior to 5.0 were all build manually on my systems.
As of 5.0 the builds are done by Github actions.
I'm trying to move away from manual builds.

**Comment by sawdoctor** [comment]
[5.0.1.0 release](https://github.com/badabing2005/PixelFlasher/releases/tag/v5.0.1.0) is the one giving the error, 4.10 works fine. A bit of googling gave me this information

"The traceback you provided suggests that there is an error in the execution of the "PixelFlasher.py" script. The error occurs when importing the "wx" module, specifically in the "core.py" file.

The specific error message indicates an "ImportError" caused by an undefined symbol "_ZNK13wxSecretValue11GetAsStringERK8wxMBConv" in the "/usr/lib/libwx_baseu_net-3.2.so.0" library." 

I'm pretty useless with Python, I've tried to change the wxpython version on my PC see if that helps but the versions in the AUR all have build errors atm which isn't helping

**Comment by badabing2005** [comment]
Just to be clear, 5.0.1.0 is different than 5.0.0.1 which you initially reported the problem.
You tried 5.0.1.0 and got the same error?.

**Comment by sawdoctor** [comment]
Sorry yes latest version still gives the same error

sawdoctor@sawdoctor-gs726qe Downloads]$ ./PixelFlasher_Ubuntu_22_04
Traceback (most recent call last):
  File "PixelFlasher.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Main.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: /usr/lib/libwx_baseu_net-3.2.so.0: undefined symbol: _ZNK13wxSecretValue11GetAsStringERK8wxMBConv
[56226] Failed to execute script 'PixelFlasher' due to unhandled exception!

PixelFlasher_Ubuntu_20_04 version still launches same as in 5.0.0.1 but fc due to the gtk errors which is to be expected

**Comment by badabing2005** [comment]
Here's one thing you could try.
Run `ldd` on PixelFlasher
you get something similar to this
```
        linux-vdso.so.1 (0x00007fffe0df9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff8f4696000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff8f467a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff8f4657000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff8f4465000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff8f46b8000)
```
See if you have all the dependencies on your system

Have you tried the manual build steps?
Just follow the steps, and if you get into an error, post it back, and we'll look into how to resolve it.

**Comment by sawdoctor** [comment]
I'll try and build it myself again but it was a pia last time. I tried running 

`pip install -U wxPython`
 
and got 
`Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wxPython in /usr/lib/python3.11/site-packages (4.2.0)
Requirement already satisfied: pillow in /usr/lib/python3.11/site-packages (from wxPython) (9.5.0)
Requirement already satisfied: six in /usr/lib/python3.11/site-packages (from wxPython) (1.16.0)
Requirement already satisfied: numpy in /usr/lib/python3.11/site-packages (from wxPython) (1.24.3)
[sawdoctor@sawdoctor-gs726qe ~]$ 
`
ldd gives this

` ldd PixelFlasher_Ubuntu_22_04
	linux-vdso.so.1 (0x00007ffd091ec000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fe079c13000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fe079bf9000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fe079bf4000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fe079a0a000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe079c56000)
`

Just really strange that [Ubuntu_20_04] will launch until gtk errors and version 4.10 works perfectly

**Comment by badabing2005** [comment]
I'm just guessing here,
Would this work for you
```
sudo pacman -Sy --noconfirm wxpython
```

Another option is to try with Python 3.10 instead of 3.11
With Python 3.10
You can try pip install this wheel
https://extras.wxpython.org/wxPython4/extras/manylinux-test/wxPython-4.2.0-cp310-cp310-manylinux_2_28_aarch64.whl

**Comment by sawdoctor** [comment]
Thanks for all your help, unfortunately no luck. I'll keep digging and see if I can get the latest version to work, If I have any luck I'll let you know

**Comment by badabing2005** [comment]
The thing is even if you install the above or change Python, if you run the PF binary (as opposed to building it yourself) none of those will be used.
The only thing that is not packaged is the system libraries, everything else is packaged as part of the PF binary in a venv.

Try building it yourself, and post back where you get failures as you go through the build.

**Comment by mattgdev69** [comment]
That same thing happens in Linux Mint 21.1.  Responding to your suggestion to run ldd, here is the output:

![2023-05-23_15-14](https://github.com/badabing2005/PixelFlasher/assets/32312016/521502ba-730a-40be-a328-5cca55a57c5c)

**Comment by badabing2005** [comment]
I've made a small change to the requirements.txt, I don't expect it to have positive or negative impact on this issue, but wouldn't hurt to try version 5.1.0.0

**Comment by badabing2005** [comment]
@sawdoctor 
Can you give build a test?
https://github.com/badabing2005/PixelFlasher/actions/runs/5093783673

**Comment by sawdoctor** [comment]
Unfortunately still the same error on test build

./PixelFlasher
Traceback (most recent call last):
  File "PixelFlasher.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Main.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: /usr/lib/libwx_baseu_net-3.2.so.0: undefined symbol: _ZNK13wxSecretValue11GetAsStringERK8wxMBConv
[252316] Failed to execute script 'PixelFlasher' due to unhandled exception!

Has anyone confirmed it working on Ubuntu ? Very surprised it doesn't work on mint as well as manjaro

**Comment by mattgdev69** [comment]
Same error in Mint.

![image](https://github.com/badabing2005/PixelFlasher/assets/32312016/c586925e-d61e-405a-b114-3398d24343f4)

**Comment by badabing2005** [comment]
Thanks for the quick test.
On Ubuntu that library is found in
`/usr/lib/x86_64-linux-gnu/libwx_baseu_net-3.0.so.0`
as you can see, that is not arch
Perhaps all we're missing a symbolic link
Can you see if you have the same library in some other path on your Manjaro?
perhaps `/usr/lib/arch-linux-gnu/...` ?

**Comment by sawdoctor** [comment]
Looks like its just in /usr/lib64/ on manjaro

![image](https://github.com/badabing2005/PixelFlasher/assets/8081226/7d5917e1-814f-421a-b5a5-7f4b1f5c7aa8)

**Comment by badabing2005** [comment]
I'd be curious if you do this if it works
```
cd /usr/lib/
sudo ln -s lib64 x86_64-linux-gnu
```

**Comment by sawdoctor** [comment]
My bad it looks like it was in usr/lib as well. Tried creating the symlink and also tried manually creating the folder and copying but still same error


![image](https://github.com/badabing2005/PixelFlasher/assets/8081226/b5474870-b30a-49b6-aeea-f45b7972f353)

**Comment by badabing2005** [comment]
If the error is exactly the same `no such file or directory`, most likely it didn't find it, which probably would be because of wrong link.

Can you do this in a terminal? let's see what are links and what are not.
```
ls -l /usr/lib /usr/lib/*/ > list
```

This will output to a file named `list`
just attach the file.

**Comment by sawdoctor** [comment]
Think this is what you wanted, thanks so much for all your help with this it really is appreciated
[list.zip](https://github.com/badabing2005/PixelFlasher/files/11581376/list.zip)

**Comment by badabing2005** [comment]
Thanks.
Looking at the details, I realized that your error is not about library not being found but rather about undefined symbol, so linking trick won't make a difference.

We know that version 4.10 worked for you, and version 5+ is not working for you.
Two of the changes between version 4.10 and versions 5.x could potentially cause this.
- Where I build the binaries, prior to 5.x, I had to manually build them locally, and now they get build with Github actions on Github.
- Code changes (added features) which possibly would add more dependencies on additional libraries.

If you don't mind, let's try to see which of the two is causing the issue.
I'm made a [test build of 5.1.0.2](https://github.com/badabing2005/PixelFlasher/releases/tag/test_build) which I built locally, and if this works for you, we know it's the build process that is the culprit although it beats me as to why it would be different, but we'll cross that bridge when we get there.

If it does not work for you, then probably additional dependencies are the reason.

**Comment by sawdoctor** [comment]
Test build is working perfectly on manjaro, thank you so much really appreciated your time and work. PixelFlasher_Ubuntu_20_04 will launch for me but i can't use it because it will fc with gtk errors so the error whatever it is is only on Ubuntu 22_04

**Comment by badabing2005** [comment]
Honestly I don't know, and am trying to find out, but it's been trial and error, as I'm shooting in the dark, I might have to reach out to wxPython team for answers, I'll get to it when I find some time.

**Comment by sawdoctor** [comment]
Thanks for all your help. I'm really struggling to build it myself again, no matter which wheel I install its giving me errors. I'll keep at it and hopefully figure it out

**Comment by badabing2005** [comment]
Feel free to share the errors you encounter, in case I have any ideas, I'm not sure how helpful I would be :)

**Comment by badabing2005** [comment]
attdict3 is included in the requirements.txt
run the step `pip3 install -r requirements.txt` and see if it resolves it.
Also I'm not sure this URL exists
https://extras.wxpython.org/wxPython4/extras/linux/gtk3/manjaro
Just look here
https://extras.wxpython.org/wxPython4/extras/linux/gtk3/
and pick one that is closest to your platform, I think you chose ubuntu22.04 last time around no?

**Comment by sawdoctor** [comment]
I've tried every wheel on the website and get the same attrdict error. I've tried building the wheel using the build steps on the website and that throws the same attrdict error. Really wish I knew python

**Comment by badabing2005** [comment]
before you do the pip3 install step, please do this
pip3 install attrdict3
pip3 install attrdict

see if it makes a difference.

I know just enough Python to code this application and still don't know why this is such a PITA and why it's not working.

**Comment by sawdoctor** [comment]
I tried
 pip3 install attrdict3
pip3 install attrdict

Still same errors unfortunately. Looking in the ~/.local/share/PixelFlasher  logs there are no logs at all for the version that fails to launch, the only errors I can find are the fatal exception one from my opening posts (hope that makes sense). I

'll try editing the json file tomorrow and give you feedback

On a positive note the test build works great thank you so much I really appreciate it. I also reached out the user on xda who built it on manjaro and he sent me his build instructions where he compiled the wheel from source. There's an awful lot involved but I can definitely follow his build instructions

**Comment by badabing2005** [comment]
If that works, please share the steps, hopefully it can be integrated into Github actions.

**Comment by sawdoctor** [comment]
Can't see any personal information in the steps and not certain all are needed

`15763  cd /tmp
15764  mkdir test
15765  cd test
15766  python3 -m venv builder_py
15767  source builder_py/bin/activate
15768  which python
15769  which pip
15770  pip install -U pip
15771  pip install -U six wheel setuptools
15772  pip download wxPython
15773  pip install attrdict
15774  pip download wxPython
15775  pip install Mapping
15776  pip download wxPython
15777  pip install collections
15778  pip install AttrMap
15779  pip download wxPython
15780  pip install AttrDict
15781  pip install Config
15782  pip install msg
15783  pip install --use-pep517 msg
15784  pip install NoneType
15785  pip install -U six wheel setuptools
15786  pip download wxPython
15787  ps -ef|grep cc1plus
15788  htop
15789  cls
15790  cd /tmp/test/
15791  pip download wxPython
15792  cd /opt/PixelFlasher-5.1.0.2/
15793  ll
15794  python PixelFlasher.py
15795  cd -
15796  pip wheel -v wxPython-4.0.1.tar.gz  2>&1 | tee build.log
15797  ll
15798  pip wheel -v wxPython-4.2.0.tar.gz  2>&1 | tee build.log
15799  ll
15800  pip install wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
15801  python -c "import wx; a=wx.App(); wx.Frame(None,title='hello world').Show(); a.MainLoop();"
15802  pwd
15803  cd -
15804  pip install /tmp/test/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
15805  pip install --force-reinstall /tmp/test/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
15806  ll
15807  python PixelFlasher.py
15808  which adb
15809  python PixelFlasher.py
15810  pacman -Q|grep android
15811  python PixelFlasher.py
15815  yay -Syu android-sdk-platform-tools
15816  yay -S android-sdk-platform-tools
15817  python PixelFlasher.py
15818  pacman -Q|grep android
15819  yay -S android-tools
15820  yay -S android-apktool
15821  yay -S android-udev
15825  yay -S android-sdk
15826  python PixelFlasher.py
15827  pacman -Q|grep android
15828  ll ~/Downloads/
15829  unzip -t ~/Downloads/platform-tools_r34.0.3-linux.zip
15830  cd ..
15831  unzip  ~/Downloads/platform-tools_r34.0.3-linux.zip
15832  sudo unzip  ~/Downloads/platform-tools_r34.0.3-linux.zip
15833  pwd
15834  cd -
15835  PATH=/opt/platform-tools/:$PATH python PixelFlasher.py
15836  python PixelFlasher.py`

(ll is an alias for long list)

Perhaps just building the wheel from source would be all that's needed as your test builds seem to work fine on manjaro/arch and hopefully all linux distros

**Comment by badabing2005** [comment]
There are two issues at hand.

1- I build the same way locally as I build on Github, I build it in Ubuntu 22.04
The one I build locally works for you, whereas the one that is built on Github does not, although it works for other people, at least people running Ubuntu.
I want to stop building manually, so getting this fixed is important.

2- In the absence of a functional build, the only choice user like yourself have is to build it locally, which is where you're running into issues. I much rather have 1 addressed over 2, mainly because it serves a bigger audience, but that does not mean that 2 shouldn't be addressed, some people feel more comfortable building from source then using a pre-build binaries.

To address 1, I need more feedback, because the data I have here is not enough to narrow it down, hence why I asked if you could turn off update check and run the official Ubuntu 22.04 build.

As for 2, I suggest you start fresh. clone the repo to a new directory, create venv, activate it, and follow the build steps as outlined in the readme, don't try anything different, when you encounter an error, stop there and post the exact error and the step that gave you that error, we're resolve one error at a time until we iron out all the issues, then document the steps for others to follow.

The list above is command history list, it does not tell us why a certain command was needed to be executed and if at all resolved the error at that step or if it was a trial and error until one worked.

**Comment by sawdoctor** [comment]
I'll do as much digging as I can and try and give as much feedback as I can. What is strange is mint users seem to have the same issue as me and I can't see why when it's Ubuntu based. 

I'll have a play/try and get as much feedback as I can over the weekend.

Thanks for all your hard work and taking the time to troubleshoot this

**Comment by badabing2005** [comment]
> I'll do as much digging as I can and try and give as much feedback as I can. What is strange is mint users seem to have the same issue as me and I can't see why when it's Ubuntu based.
WxPython depends on system libraries, system libraries are not bundled with the application, and shouldn't as they are system specific, they just need to exist which in general they do.
In your case the linked library is of a version that does not have the necessary symbol that is needed.
> ImportError: /usr/lib/libwx_baseu_net-3.2.so.0: undefined symbol: _ZNK13wxSecretValue11GetAsStringERK8wxMBConv
[32928] Failed to execute script 'PixelFlasher' due to unhandled exception!
Hence why it fails,

> There's no option for me to turn off update check with the official version as it fails to launch, so they only way to turn it off would be for me to compile it myself I think

Please read my previous post, you can turn off the Auto update by editing PixelFlasher.json file.
Or you can use a working version (any) and go to configuration and turn it off from there.

**Comment by sawdoctor** [comment]
So sorry, I was being dumb, you meant in .local/share/PixelFlasher. I was looking in the source code for the json file.

Tried setting to false and also deleted everything PixelFlasher off the pc and did a clean install/run of the latest version with bug fix #78 and unfortunately same error

`[sawdoctor@sawdoctor-gs726qe Downloads]$ ./PixelFlasher_Ubuntu_22_04
Traceback (most recent call last):
  File "PixelFlasher.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Main.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: /usr/lib/libwx_baseu_net-3.2.so.0: undefined symbol: _ZNK13wxSecretValue11GetAsStringERK8wxMBConv
[93678] Failed to execute script 'PixelFlasher' due to unhandled exception!
` 

The folder .local/share/PixelFlasher doesn't even get created. I'm trying to give as much feedback as I can and hope we can find it as its a really strange bug

**Comment by badabing2005** [comment]
Thank you for your feedback, I'm looking at thing from my end as well, if I find anything I'll let you know.

For you to build it locally, it shouldn't be difficult.
What is your Python version?, run these commands.

`python --version`
`which python`
`python3 --version`
`which python3`

**Comment by swebow** [comment]
Can I add, I run Endeavour OS.

I can't run the 22_04
But 20_04 works great!

22_04:
`Traceback (most recent call last):
  File "PixelFlasher.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Main.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: /usr/lib/libwx_baseu_net-3.2.so.0: undefined symbol: _ZNK13wxSecretValue11GetAsStringERK8wxMBConv
[20966] Failed to execute script 'PixelFlasher' due to unhandled exception!
`

20_04:

> Gtk-Message: 15:32:41.884: Failed to load module "xapp-gtk3-module"
> Gtk-Message: 15:32:41.884: Failed to load module "canberra-gtk-module"
> Gtk-Message: 15:32:41.902: Failed to load module "colorreload-gtk-module"
> Gtk-Message: 15:32:41.902: Failed to load module "window-decorations-gtk-module"
> Loading configuration File ...
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): GLib-GObject-WARNING **: 15:32:42.932: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-CRITICAL **: 15:32:42.932: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-WARNING **: 15:32:42.946: Could not load a pixbuf from icon theme.
> This may indicate that pixbuf loaders or the mime database could not be found.
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-WARNING **: 15:32:45.458: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)
> 
> (PixelFlasher_Ubuntu_20_04:20976): Gtk-WARNING **: 15:32:45.458: Negative content height -13 (allocation 1, extents 7x7) while allocating gadget (node button, owner GtkButton)

**Comment by sawdoctor** [comment]
`[sawdoctor@sawdoctor-gs726qe Downloads]$ python --version
Python 3.11.3
[sawdoctor@sawdoctor-gs726qe Downloads]$ which python
/usr/bin/python
[sawdoctor@sawdoctor-gs726qe Downloads]$ python3 --version
Python 3.11.3
[sawdoctor@sawdoctor-gs726qe Downloads]$ which python3
/usr/bin/python3
`
https://github.com/swebow
Does the test build run for you https://github.com/badabing2005/PixelFlasher/releases/tag/test_build

**Comment by badabing2005** [comment]
I was able to reproduce the same error locally and did some changes.
I am very optimistic that this would work. (Fingers crossed)
Try this build, it was built on Github with my changes.

https://github.com/badabing2005/PixelFlasher/releases/download/test_build/PixelFlasher_5.2.0.1_test_build.zip

**Comment by sawdoctor** [comment]
Thanks so much, yes latest test build works great thanks. Really can't thank you enough for your time and hard work

**Comment by badabing2005** [comment]
v5.2.0.2 release to integrate this with release builds.
