### ISSUE TITLE
Please add attrdict3 to python requirements.

### ISSUE THREAD

**Issue by TrainDoctor** [badabing2005/PixelFlasher#77]
Without this package on certain setups the requirements will fail to install flashing errors related to mappings and collections etc when attempting to setup wxPython. It turned out the solution was to install attrdict3 to the venv. This is not currently a direct dependency but I highly suggest it be added.
Thanks.

**Comment by badabing2005** [comment]
Thanks for the tip,

I was looking at this at one point, and when I tried to add it I got this error
```
in <module>
          from attrdict import AttrDict
        File "/__w/PixelFlasher/PixelFlasher/myenv/lib/python3.11/site-packages/attrdict/__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "/__w/PixelFlasher/PixelFlasher/myenv/lib/python3.11/site-packages/attrdict/mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
      [end of output]
```

It caused a conflict with the mapping module in the collections package.
Collections module is a built in module in Python.

It appears that the `collections` module is being referenced in the context of `attrdict` package.

**Comment by badabing2005** [comment]
Added

**Comment by TrainDoctor** [comment]
Thank you very much! Now I will be able to manually do fresh builds ootb on arch.

**Comment by badabing2005** [comment]
Let me know how the build goes, take notes, once done, we probably can replicate it with Github actions to build on each release.
