### ISSUE TITLE
Package Manager column stay unsorted when filtered

### ISSUE THREAD

**Issue by arghfrank** [badabing2005/PixelFlasher#79]
When using "Package Manager" and applying a filter at the top, apparently sorting columns doesn’t work. See screenshot. Not a really big deal though, just .. saying. :-)
![2023-06-18 09_50_43-Window](https://github.com/badabing2005/PixelFlasher/assets/13719504/6b797657-480e-482b-8314-58e82947a18c)
![2023-06-18 09_50_56-Window](https://github.com/badabing2005/PixelFlasher/assets/13719504/304f37a7-3378-46cd-b23b-2a81ddf1b77e)

**Comment by badabing2005** [comment]
Thanks for reporting it, I'll see if it is easy to fix.

**Comment by badabing2005** [comment]
Fixed in 5.3.3.0
