### ISSUE TITLE
req: more flashing options

### ISSUE THREAD

**Issue by nutpantz** [badabing2005/PixelFlasher#8]
It would be nice if there was option for manually adding a  boot.img for those who already have patched the boot image, want to unroot or have a custom kernel they want to use.
Maybe even a separate expert page to flash radio, bootloader or other images some expert may want to flash.

**Comment by badabing2005** [comment]
Perhaps there is a scenario that I'm missing.

If you want to unroot, don't select `Patch boot.img` and you'd be unrooted.
I get that it would flash full image rather than just boot.img, but you'd get what you're looking for.
The more I add such options, the more confusing it would get to regular users, and more chances to shoot themselves on the foot. I'm not adverse to adding features, just want to understand the exact use case.

As for custom kernel, there is an option for custom ROM
if you don't select patch, it will not root, unless the bundled boot.img in the ROM is rooted, which is rare these days.
You still have the option of patching that boot.img if you so desire.

Did I miss something?

Thanks for the feedback.

**Comment by nutpantz** [comment]
Isn't it unnecessary to risk flashing an entire image to unroot of you only need to flash the boot.Img? 
Right now i already have a patched boot.img to flash after the latest update(so i don't need the flasher to patch it), but in April i expect i will want to flash a custom kernel with that update, or even flash a custom kernel with the flasher before. (Just a custom kernel (which is in a "boot.img" if I'm not wrong). There is no option to just flash a boot.img or a custom boot. Img after flashing the factory package. (The custom ROM is for a full ROM and will just go wrong with a custom boot. Img right?)
Maybe I'm not explaining it well.

**Comment by badabing2005** [comment]
> Isn't it unnecessary to risk flashing an entire image to unroot of you only need to flash the boot.Img?
Yes it is unnecessary, but risk is debatable, if you know what you're doing, it's easier to just flash boot and yes less things to do means less risk, however for most people it's the inverse.

Today you ask for flashing boot.img, if we go that route, why wouldn't someone ask for flashing radio / system recover or any other image? what about all the flags that are supported when flashing, in what order those images need to be flashed? at which points the phone needs to rebooted?
You see how this could get out of hand so fast.

As it stands today, the program is quite stateless, or is able to detect the current state, once we go there, we'll just have to assume the user knows what they are doing and trust that they do the right thing.

Like I said, I'm not opposed to adding features that would help, I'd have to see how a feature like this can be added without risking regular users and keeping the interface simple.

**Comment by nutpantz** [comment]
I understand your point of not wanting it to get to complicated. Look at the most often flashed items, roms and kernels flashed both together and separately. 
I don't know about you, but in a well developed device i could try it 5 or six kernels in a month until i found just the right one.
Personally i think support for just flashing kernels is pretty important. That's the boot.Img only.  
I think a lot of people would use that feature, 
I think of your tool much like Odin for Samsung and what it's used like.
People will be updating and downgrading a lot depending on goggles new "features"and bugs

**Comment by badabing2005** [comment]
@n0101 
Thanks for the kind words.

> I realize this is a much greater enhancement than adding a fastboot flash operation since you would need to support Linux shell scripts in order to run AnyKernel3, but imo it would be great feature and also a unique one.

I'm not sure if I follow you about support for Linux shell, wouldn't `fastboot update <the_zip_file>` do the job? if so, then this is coming.

> Since you are using wxPython for the GUI, which is platform agonistic, the challenge would be using adapting the PowerShell script to work on windows and Linux.

Powershell script is no longer being maintained, in any case [Powershell](https://aka.ms/powershell) can be run on all platforms.

**Comment by badabing2005** [comment]
I think I managed to add the requested advanced features (and more) and kept the basic mode UI simple.
See [this](https://github.com/badabing2005/PixelFlasher/releases/tag/v2.0.0-pre) release.
