### ISSUE TITLE
Switch from beta to stock with full wipe did not wipe. Everything incl. root was kept.

### ISSUE THREAD

**Issue by RobertLaffan** [badabing2005/PixelFlasher#80]
[support_2023-06-19_21-46-50.zip](https://github.com/badabing2005/PixelFlasher/files/11796841/support_2023-06-19_21-46-50.zip)

**Comment by badabing2005** [comment]
You're using Android Platform-Tools 34.0.3-10161052
Switch to 33.0.3 and you should be fine.
You can blame Google for that.
