### ISSUE TITLE
5.5.1.0 Cannot read boot img from  "Support/Pixel folder.

### ISSUE THREAD

**Issue by StuartHawkes** [badabing2005/PixelFlasher#86]
5.5.1.0 has a problem reading the patched boot image from the phone during the "Patch" stage of the process. I downgraded to version 5.3.1.2 and patched the boot image successfully, so this is a bug introduced in a more recent version.

The flashed boot file exists on my phone but is not copied to the Application Support/PixelFlasher folder and then cannot be reference in a later step.

The log complains of "failed to access 'Support/PixelFlasher/tmp/.". Is this tripping with an unquoted reference to "~/LibraryApplication Support"?

Phone/ROM/tools:

I’m trying to patch the tq3a.230705 boot image on a Pixel 7 Pro running tq3a.230605.
Platform tools 34.0.4 and 33.0.3 have the same result. Fine on 5.3.1.3, fails on 5.5.1.0.

Log from the console attached.
[console_log.txt](https://github.com/badabing2005/PixelFlasher/files/12059544/console_log.txt)

**Comment by badabing2005** [comment]
Can you please generate support.zip from PixelFlasher and provide that.
It has more information that could help me troubleshoot this.

Based on what I'm seeing above the error is happening [here](https://github.com/badabing2005/PixelFlasher/blob/main/phone.py#L1214-L1215)
But as you can see it's quoted, so I don't understand where it is tripping.
If anything it was not quoted previously and now it is.

**Comment by badabing2005** [comment]
Fixed in 5.5.1.1
