### ISSUE TITLE
Unable to Run ADB Shell

### ISSUE THREAD

**Issue by MidnightJava** [badabing2005/PixelFlasher#96]
I get a permission error when I try to run ADB Shell. Maybe I have something set up wrong, but I've tried everything I can think of. The phone is a rooted Pixel-7 Pro with stock Android.

- I have USB Debugging enabled, and I tried every option of USB Mode.
- I granted permanent superuser permission to ADB Shell via Magisk
-  I'm running PixelFlasher on Ubuntu 22.04. I tried launching it with and without sudo.

Here's the error message:

```
Opening an adb shell command for device: 35021FDH3002UR ...
debug: "/opt/platform-tools/adb" -s 35021FDH3002UR shell
Traceback (most recent call last):
  File "Main.py", line 570, in OnToolClick
  File "Main.py", line 2378, in _on_adb_shell
  File "phone.py", line 2187, in open_shell
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1950, in _execute_child
PermissionError: [Errno 13] Permission denied: ''

```

**Comment by MidnightJava** [comment]
[support_2023-09-09_16-32-41.zip](https://github.com/badabing2005/PixelFlasher/files/12566635/support_2023-09-09_16-32-41.zip)
Here's the support file

**Comment by badabing2005** [comment]
You need to go to the configuration and select the terminal program you want to use.
Same if you want to open a folder, you need to select the explorer application.
You do this once, and it's remembered.

Let me know if that works for you.

**Comment by MidnightJava** [comment]
Thanks, silly of me to miss that. Yes, it's working great now. Thanks for all the work you put into this. It's a very helpful tool.
