### ISSUE TITLE
show/hide buttons not functioning as intended.

### ISSUE THREAD

**Issue by bnee99** [badabing2005/PixelFlasher#98]
I can hide only preset button but not add other buttons, like recovery , safe mode , slot , partition , download to toolbar. 

version 5.7.2.0

**Comment by badabing2005** [comment]
Those are advanced options, have you enabled advanced configuration in the settings?

**Comment by badabing2005** [comment]
This issue was closed due to inactivity.

**Comment by badabing2005** [comment]
This issue was closed due to inactivity.
