### ISSUE TITLE
Settings not opening on linux/arch based distro

### ISSUE THREAD

**Issue by sawdoctor** [badabing2005/PixelFlasher#99]
Hi there's an issue with the latest version on arch based distros where you can't open settings

Traceback (most recent call last):
  File "Main.py", line 615, in OnToolClick
  File "Main.py", line 1101, in _on_advanced_config
  File "advanced_settings.py", line 219, in __init__
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /home/wxpy/wxPython-4.2.1/ext/wxWidgets/src/common/sizer.cpp(1601) in DoInsert(): too many items (19 > 2*9) in grid sizer (maybe you should omit the number of either rows or columns?)

I reported it to the aur maintainer and he confirmed he could reproduce the issue when building from source. Other than that the latest version seems to work fine on arch based distro's. When i saw the wxPython error I thought on no  hahaha

**Comment by badabing2005** [comment]
Thanks for reporting.
I don't have access to arch to be able to test this.
If the aur maintainer can build it from source, can you ask him if this change fixes the issue?

Basically remove the `rows=NUMROWS, ` part from [this line](https://github.com/badabing2005/PixelFlasher/blob/e6eb9096d586efc1a79599752d5803a0c9c929b3/advanced_settings.py#L51).
![image](https://github.com/badabing2005/PixelFlasher/assets/22603312/a6f8ba64-aa5a-4124-973b-0a44f8666d7b)


Alternately this should also fix the issue by setting the NUMROWS to 11 on [this line](https://github.com/badabing2005/PixelFlasher/blob/e6eb9096d586efc1a79599752d5803a0c9c929b3/advanced_settings.py#L50).
But I prefer the former if it works, this way I don't have to keep on updating the count each time I add widgets to the settings.
![image](https://github.com/badabing2005/PixelFlasher/assets/22603312/732c06d2-c75b-4a16-9424-38ae8e0d69f1)

**Comment by MicMun** [comment]
I'm not the aur maintainer but I have a arch linux and tested it with building from source.
I tried the solution with removing `rows=NUMROWS` and build it. I can confirm, it works, I can open the settings with this fix.

**Comment by badabing2005** [comment]
OK thanks for confirming, I'll integrate this into the next release.
